Document EDM to TypeScript type conversion and limitations
SAP/cloud-sdk pull request #1006
Opened 2022-09-09 11:19 UTC by fwilhe

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Check spelling and grammar, e.g., using Grammarly.
- [ ] Verify links still work, e.g., if `id` or the name of a file is changed.
- [ ] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a new feature is added.

2022-09-09 13:55 UTC, florian-richter commented on docs-js/features/odata/common/edm.mdx
> +The SAP Cloud SDK converts EDM types into TypeScript types as described by the following tables.
It should be mentioned that this applies to the default deserializers and can be modified.

2022-09-09 13:58 UTC, florian-richter commented on docs-js/features/odata/common/edm.mdx
> +| `Edm.Time`     | `Time`          |
I think it would be helpful to mention that Time is a custom type from us which is this:

```
/**
 * Interface to represent Time or Duration.
 */
export interface Time {
  /**
   * The number of hours.
   */
  hours: number;
  /**
   * The number of minutes.
   */
  minutes: number;
  /**
   * The number of seconds.
   */
  seconds: number;
}
```

Either a short description or a link to our API reference for this interface would be nice.

2022-09-12 07:22 UTC, fwilhe commented on docs-js/features/odata/common/edm.mdx
> +While converting `Edm.DateTime` to `Moment` the smallest considered unit is milliseconds.
Looks like it supports 7 decimal places for fractions of a second (for whatever erp use-case this might be useful..)

<img width="1167" alt="Screenshot 2022-09-12 at 09 20 08" src="https://user-images.githubusercontent.com/2292245/189595645-bad3fc16-7fef-406f-aebe-41d78e15ebca.png">

2022-09-12 14:41 UTC, marikaner requested changes
I like the structure and have mostly minor feedback + a question whether to put this into its own page.

2022-09-12 14:41 UTC, marikaner commented on docs-js/features/odata/common/edm.mdx
> +The SAP Cloud SDK for JavaScript automatically converts values encoded in EDM to respective types in JavaScript and TypeScript.
[q] Are those values really encoded?
[q] When does the conversion happen? I think it "only" happens when deserializing entities / complex types / primitive types after calling `execute`.

2022-09-12 14:41 UTC, marikaner commented on docs-js/features/odata/common/edm.mdx
> +### OData v2 Specific
[pp] If you add "Types" I find it more consistent.
```suggestion
### OData v2 Specific Types
```

2022-09-12 14:41 UTC, marikaner commented on docs-js/features/odata/common/edm.mdx
> +While converting `Edm.DateTime` to `moment.Moment` the smallest considered unit is milliseconds.
[req] Copy paste error
[q/pp] This error happened because it is duplicated text. I wonder whether we could find a way to put this together with the OData v2 warning. Did you consider this somehow? 
```suggestion
While converting `Edm.DateTime` to `moment.Moment` the smallest considered unit is milliseconds.
```

2022-09-12 14:41 UTC, marikaner commented on docs-js/features/odata/overview.mdx
> +See the [page on edm](./common/edm.mdx) for details and limitations of that conversion.
[pp] I am torn whether it is a good idea to have more pages also for minor topics or not and where to draw the line. For comparison, I looked at the docusauraus docs and I think we are too broad when it comes to the general odata client description, but just edm seems to fine granular.
I think I would prefer something like Serialization and Deserialization as a topic, where EDM is part of it.
However, doing that would be out of scope for this issue...

2022-09-12 14:41 UTC, marikaner commented on docs-js/features/odata/common/edm.mdx
> +While converting `Edm.DateTime` to `moment.Moment` the smallest considered unit is milliseconds.
[nth/q] Consider the following case: A user just looks at the OData v4 section of this article. This suggests, that we only support 3 EDM types. Maybe we should link to the common parts as well?

2022-09-13 10:57 UTC, fwilhe commented on docs-js/features/odata/common/edm.mdx
> +The SAP Cloud SDK for JavaScript automatically converts values encoded in EDM to respective types in JavaScript and TypeScript.
Not sure if we have the same understanding of "encoding" but I would say that every computer representation of values is a type of "encoding", also ascii or unicode.

EDM defines how a date or a number is represented and that representation is "encoding" in my understanding. Also seems to align with [wikipedia's definition](https://en.wikipedia.org/wiki/Code).

But if you have an alternative term to use please suggest that.

2022-09-13 11:55 UTC, marikaner commented on docs-js/features/odata/common/edm.mdx
> +The SAP Cloud SDK for JavaScript automatically converts values encoded in EDM to respective types in JavaScript and TypeScript.
It really was meant as a question, because I imagine url encoding or base 64 encoding when I read that. The word I would suggest would be something in the direction of "represented", but you can just decide what you like most.

2022-09-14 07:59 UTC, marikaner approved these changes
👍 Love it!

2022-09-14 08:01 UTC, florian-richter reviewed
Some spelling and comma findings. Otherwise looks good!

2022-09-14 08:01 UTC, florian-richter commented on docs-js/features/odata/execute-odata-request.mdx
> +For definition of the EDM data types in OData, see [the v2 spec](https://www.odata.org/documentation/odata-version-2-0/overview/) or the [v4 spec](http://docs.oasis-open.org/odata/odata/v4.0/os/part3
```suggestion
For definition of the EDM data types in OData, see [the v2 spec](https://www.odata.org/documentation/odata-version-2-0/json-format/) or the [v4 spec](http://docs.oasis-open.org/odata/odata/v4.0/os/part3-csdl/odata-v4.0-os-part3-csdl.html#_The_edm:Documentation_Element) of OData.
```
[pp] You may want to link the OData-JSON spec or the OData spec overview page instead

2022-09-14 08:08 UTC, fwilhe commented on docs-js/features/odata/execute-odata-request.mdx
> +OData uses the Entity Data Model (EDM) to represent values such as strings, numbers, dates and times.
🇬🇧

2022-09-14 08:16 UTC, merged