chore: Remove references to VDM and pregenerated clients from text
SAP/cloud-sdk pull request #1014
Opened 2022-09-14 12:27 UTC by florian-richter

## What Has Changed?

As the pregenerated clients for JavaScript are de-facto deprecated, references should be removed and replaced with references to the generator.

This is part 1 which removes text references. Code fixes will be done in part 2.

Related to SAP/cloud-sdk-backlog#818

## Manual Checks?

- [x] Check spelling and grammar, e.g., using Grammarly.
- [x] Verify links still work, e.g., if `id` or the name of a file is changed.
- [x] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a new feature is added.

2022-09-15 09:26 UTC, deekshas8 requested changes
[req] I found few code snippets where we still use vdm imports, e.g.
`import { businessPartnerService } from '@sap/cloud-sdk-vdm-business-partner-service';`

Please update them as well.

2022-09-15 09:26 UTC, deekshas8 commented on src/theme/NavbarItem/NavbarNavLink.js
> -export default function NavbarNavLinkWrapper(props) {
[q] Could you please explain why we don't need this anymore?

2022-09-15 13:04 UTC, deekshas8 reviewed
Also found pregenerated used on this [page](https://sap.github.io/cloud-sdk/docs/js/tutorials/getting-started/introduction)

2022-09-16 07:39 UTC, florian-richter commented on src/theme/NavbarItem/NavbarNavLink.js
> -export default function NavbarNavLinkWrapper(props) {
I checked with Tom. Apparently it was considered but never actually used. Docs work as intended even without it.

2022-09-16 07:54 UTC, FrankEssenberger commented on docs-js/guides/how-to-add-resilience.mdx
> +  For example, an HTTP request failing with 401 should not trigger a retry because the user is simply unauthorized.
```suggestion
  For example, an HTTP request failing with 401 should not trigger a retry because the user is unauthorized.
```

2022-09-16 07:55 UTC, FrankEssenberger commented on docs-js/guides/upgrade-to-version-2.mdx
> +  In most cases, the service name can be inferred from the npm package itself, i.e., everything after `@sap/cloud-sdk-vdm-` in camelCase. E.g.:
```suggestion
Usually, the service name can be inferred from the npm package itself, i.e., everything after `@sap/cloud-sdk-vdm-` in camelCase. E.g.:
```

2022-09-16 07:58 UTC, FrankEssenberger commented on docs-js/overview.mdx
> +| Operates dynamically on the metadata and creates an on-the-fly-client. | Uses typed API clients that are generated during design time.                                           |
Perhaps mention the untyped http-client of the SDK here as well. Perhaps:
```
Uses typed API clients that are generated during design time.
A untyped http-client is also available [ref].
```

2022-09-16 07:58 UTC, FrankEssenberger commented on docs-js/overview.mdx
> +| Connectivity needs to be handled manually.                             | The SAP Cloud SDK handles [connectivity](features/connectivity/destination.mdx) on the SAP BTP for you. |
if above is added perhaps add 
```
The SAP Cloud SDK handles [connectivity] for typed and untyped clients.
```

2022-09-16 07:59 UTC, FrankEssenberger approved these changes
LGTM - did we already remove also the links to `@sap/bp-vdm-business-partner` in the tutorials?

2022-09-16 11:09 UTC, merged