Docs style guide
SAP/cloud-sdk pull request #1030
Opened 2022-09-27 12:55 UTC by deekshas8

## What Has Changed?

Added the formatting style guide.

## Manual Checks?

- [ ] Check spelling and grammar, e.g., using Grammarly.
- [ ] Verify links still work, e.g., if `id` or the name of a file is changed.
- [ ] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a new feature is added.

2022-09-28 12:53 UTC, FrankEssenberger commented on style-guide.md
> +✅ More than 100 deprecated methods have been removed.
[q] how do you avoid `we` and also use active language?

2022-09-28 12:55 UTC, FrankEssenberger commented on style-guide.md
> +✅ where _`YOUR_APPLICATION_NAME`_ is replaced by the name you specified.
general: I thought we should use active language. If so would be nice if the examples feature that.

2022-09-28 13:20 UTC, FrankEssenberger approved these changes
LGTM only minor question regarding active/passive vioce.

2022-09-29 13:42 UTC, deekshas8 commented on style-guide.md
> +✅ where _`YOUR_APPLICATION_NAME`_ is replaced by the name you specified.
@FrankEssenberger I used the examples from our text for the formatting so it was not super generic examples but provided more clarity. Since this guide was supposed to be strictly for formatting (scope of the ticket) and not about language and writing style, I decided not to go there.

I can however add a small section still with some examples.

2022-09-29 13:53 UTC, deekshas8 commented on style-guide.md
> +✅ More than 100 deprecated methods have been removed.
In some cases, there can be exceptions as explained [here](https://developers.google.com/style/voice#exceptions) (To de-emphasize a subject or actor.).

2022-09-30 07:23 UTC, FrankEssenberger commented on style-guide.md
> +✅ More than 100 deprecated methods have been removed.
ok, this is good to know. For me as a non native speaker it is hard to judge when it is ok to use passiv form, but this is the problem with normal language with their non strict rules

2022-10-04 09:56 UTC, marikaner requested changes
I find this very helpful already. I left many comments on structure and some missing content in my opinion. I think it could be helpful to add a short sentence to every example why it is correct/incorrect, similar to how we did it in the [code style guide](https://github.com/SAP/cloud-sdk-js/blob/main/STYLEGUIDE.md).

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +## Formatting
[req] The highest level title should be the title of the document. Currently "Formatting" us a section under "About This Guide".
Suggestion: remove the first level and drag all sections one level up.
```suggestion
# Formatting

This style guide covers some general text-formatting conventions that should be applied when writing documentation for the SAP Cloud SDK.
```

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +# About This Guide
[pp] I think it would be nice to be consistent with the naming of our files. In the JS repo, we call it `STYLEGUIDE.md`.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +### User-Replaced Placeholders in Inline Text
[req] I find it a bit confusing that this section and the next section are on the same level as the general place holder section. Suggestion:
Have 1 section on "Placeholders" with some general guidance and below that add 3 sections on:
- Placeholders in Code
- Placeholders in Text
- Placeholder Text (or Placeholder Syntax, but I slightly lean towards Text)

To me that would be the natural order of how I think about that. I first have a code example. Then I have the text that I use to explain the example. From the examples in the guide I probably already have an idea of how the placeholder text should look like, but if I want more details, there is a detailed section on this.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +<!-- vale on -->
I think we should also include the rule that possessive pronouns should not be included.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +### Software Product and their Command Line Utility
[nth]
```suggestion
### Software Products and Command Line Utilities
```

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +# About This Guide
[nth] I think it would be helpful to have a table of contents same as here: (https://github.com/SAP/cloud-sdk-js/blob/main/STYLEGUIDE.md#table-of-contents)

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +Use code font to mark up code, such as class names, method names, HTTP status codes/verbs/content-types, env variables, console output, etc.
[req] I think this should be a list:
```suggestion
Use code font to mark up code, such as:
- class names
- method names
- HTTP status codes/verbs/content-types
- env variables
- console output
- etc.
```

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +For a complete list, see [here](https://developers.google.com/style/code-in-text#some-specific-items-to-put-in-code-font)
[req] I think this section would benefit from a subsection what not to put into code font.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +### Software Product and their Command Line Utility
[pp] I am not sure that these two things need to be put together. Command line utilities could just be mentioned in the "Code Format for Inline Code" or be a separate section.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +✅ where _`YOUR_APPLICATION_NAME`_ is replaced by the name you specified.
[pp] But I agree, we could easily change this example to active voice without making this part of the guide.
```suggestion
✅ Replace _`YOUR_APPLICATION_NAME`_ with your application name.
```

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +✅ where _`YOUR_APPLICATION_NAME`_ is replaced by the name you specified.
[req] However, according to the google guide (and I like this rule) we should not use possessive pronouns, so maybe this example should not use a possessive pronoun either ;)

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +✅ Add your own `package.json` file.
[nth] Maybe add an example for a file path as well?

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +Try to use the formal file type name, not the filename extension.
[req] Can you give an example for this? e.g. XML file vs. .xml file?

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +Enclose error messages in quotation marks when referring to them in text.
[q] I think there can be quite complex cases where the error already includes both " and '. How should this be handled?

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +For generic domain names in examples, use `example.com`, `example.org`, or `example.net`.
[q] Should we restrict this to only `example.com`? I doubt that all three will be needed.
[q] Also, what do I do if I need to use two different domains. I think `example.com` are `example.org` too similar. I guess then something like `other.domain.com` would be OK (or would it not?). Should we document this or rather not?
[q] Strictly speaking this is not about formatting, but naming. Should we move this down to the other non-formatting related aspects?

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +Bold all graphical user interface element names, including, menus, button, dialog box, list items, and window.
[req] I think this should be a list for better readability.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +Don't include the type of UI element, such as button or checkbox, unless it adds needed clarity.
[pp] I think we should either drag this text up to the top of this section or introduce subsections for better overview. I don't know what the best option here is...

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +❌ You can start your application via the "LAUNCH" button.
[req] I think these examples are not enough to understand the requirements well. The main problem is, that we do not see any UI with a button, therefore adding info on the button label would be helpful.
```suggestion
Button label: launch...

✅ To start your application, click **launch**.

✅ **Launch** starts your application.

❌ To start your application, click **launch...**.

❌ To start your application, click **LAUNCH**.

❌ You can start your application via the "launch.." button.
```

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +Use sentence-style capitalization unless you need to match the UI.
[q] When do I not need to match the UI? I really don't understand when this would be the case.

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +❌ In the new version we allow to specify the origin of the header
[req] Remove "we" from these samples ;)

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +## Avoid Using We
[q] I think from here on this is not formatting anymore, maybe this should have another separate heading like "Style"?

2022-10-04 09:56 UTC, marikaner commented on style-guide.md
> +
[req] I think we should have a subsection here for the special case of methods (and functions) => https://developers.google.com/style/code-in-text#method-names
[nth] Maybe it would also be nice to have non-formatting related section below on when to speak of methods and when to call something a function. I have the impression that this is still misunderstood a lot.

2022-10-05 14:26 UTC, deekshas8 commented on style-guide.md
> +Enclose error messages in quotation marks when referring to them in text.
I assume the same. Also I didn't notice any issues in markdown syntax if you add text that includes. When the error message is too complex/large, we can use the  fenced block syntax (which I have seen being used)

2022-10-05 14:53 UTC, deekshas8 commented on style-guide.md
> +Use sentence-style capitalization unless you need to match the UI.
When either the labels themselves are inconsistent or all caps, in that case, change all to sentence style. I improved the text a bit to avoid confusion.

2022-10-05 15:07 UTC, deekshas8 commented on style-guide.md
> +For generic domain names in examples, use `example.com`, `example.org`, or `example.net`.
[1] 👍🏽 
[2] I honestly dont have a good suggestion here. We can leave this point open and document it when we do have such a scenario and have made a decision what to use.  
[3] I agree, but I would keep it here because It also doesn't fit under Language and Style and Punctuation either. Later if we have a general section, we can move it there.

2022-10-05 16:34 UTC, marikaner approved these changes
I still left some comments, but this already looks very good and sensible to me.

2022-10-05 16:34 UTC, marikaner commented on STYLEGUIDE.md
> +Use those terms accordingly.
Thank you 😊

2022-10-05 16:34 UTC, marikaner commented on STYLEGUIDE.md
> +## Placeholders
I find this much more easy to follow now.

2022-10-05 16:34 UTC, marikaner commented on STYLEGUIDE.md
> +✅ This creates a basic class inside `src/business-partners` folder.
```suggestion
✅ This creates a basic class inside the `src/business-partners` folder.
```

2022-10-05 16:34 UTC, marikaner commented on STYLEGUIDE.md
> +- If a label ends with a colon/an ellipsis, don't include that end punctuation.
[q] I still find this a weird rule. From the google docs they say:

> In most cases, follow the capitalization as it appears on the page. However, if labels are inconsistent or they're all uppercase, use sentence case.

I think the first sentence is important, that most of the time it should be used as it appears on the page. Can we add this?
I personally, don't understand why you would change the capitalization in the documentation even if it is inconsistent or all uppercase. It is fine for me to leave this rule however - I just don't see the point of doing that, because if the button is labeled "REFRESH" the docs can also tell me to click "REFRESH", not "Refresh" - that even seems wrong to me... 

Anyways, how I understand the original docs from google, you should only do this if all labels are uppercase...

¯\\_(ツ)_/¯

2022-10-05 16:34 UTC, marikaner commented on STYLEGUIDE.md
> +Avoid your.
[req] Could you please add an example for this?

2022-10-05 16:34 UTC, marikaner commented on STYLEGUIDE.md
> +Use please only when asking for permission or forgiveness—for example, when what you're asking for benefits us, inconveniences a reader, or suggests a potential issue with a product.
[nth] I think there is a typo in this sentence.
Also, please add spaces around the "-".

2022-10-06 11:58 UTC, deekshas8 commented on STYLEGUIDE.md
> +Avoid your.
The first example is for 'your' (and also 'we').

✅ Create an Ingress to make the application available from outside the cluster.

❌ To make your application available from outside the cluster we will create an Ingress.

2022-10-06 12:03 UTC, deekshas8 commented on STYLEGUIDE.md
> +Avoid your.
The second example is for the imperative case. Do you think splitting them into subsections (1. Avoid you/your 2. Imperative case) would be better in this case?

2022-10-06 12:07 UTC, deekshas8 commented on STYLEGUIDE.md
> +Use please only when asking for permission or forgiveness—for example, when what you're asking for benefits us, inconveniences a reader, or suggests a potential issue with a product.
```suggestion
Use 'please' only when asking for permission or forgiveness. For example, when what you're asking for:
- benefits us
- inconveniences a reader
- or suggests a potential issue with a product
```

2022-10-06 12:16 UTC, deekshas8 commented on STYLEGUIDE.md
> +- If a label ends with a colon/an ellipsis, don't include that end punctuation.
I agree. I am also fine if we keep it simple and just say 'follow the capitalization as it appears on the page'. I think it's easier to follow when writing and also for the user.

2022-10-06 15:36 UTC, marikaner commented on STYLEGUIDE.md
> +Avoid your.
I think it would be best to have one correct and incorrect example for each rule. With that you could make the examples shorter (and easier to grasp). You could even consider adding another layer of subsections for each of those rules (so that it comes up in the TOC).

The reader of this document will most likely not read the document as they would read a blog post. Instead they will rather use this as a reference when writing text.
I really like that you wrote very short text, that makes it easy to find. Still, I think this could potentially be even easier. Currently I still have to read text to get the information and if I'm in the wrong section, I have to read more text.
Side note: I think incorrect examples should come first, because in my brain this triggers an aha-effect.

That said, I think this guide is already very helpful, this might be nitpicky again ;)

Direction, of what I meant:

```ts
### Second Person

#### Don't use "we"

Don't use "we" when addressing the reader.

❌ Next, we will create an Ingress.

✅ Create an Ingress.

#### Use the imperative

Use the imperative (implicit you), when you give instructions to the reader.

❌ Next, you will create an Ingress.

✅ Create an Ingress.

#### Avoid "your"

❌ Start your application.

✅ Start the application.

```

2022-10-11 11:44 UTC, marikaner commented on STYLEGUIDE.md
> +```
This should probably be switched 😊

2022-10-11 12:37 UTC, merged