[js] Add multi tenant tutorial
SAP/cloud-sdk pull request #1031
Opened 2022-09-28 12:20 UTC by FrankEssenberger

Relates: https://github.com/SAP/cloud-sdk-backlog/issues/864

## What Has Changed?

Add a tutorial to illustrate multi-tenant application.

2022-09-29 13:01 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Before you can deploy the application you need to create a service instance for the destination and XSUAA service in your account.
```suggestion
Before you can deploy the application, you need to create a service instance for the destination and XSUAA service in your account.
```
[pp] Provider account for clarity

2022-09-29 13:06 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You find a `xs-sercurity.json` in the `service-config` folder to create the XSUAA instance.
```suggestion
There is an `xs-sercurity.json` file in the `service-config` folder to create the XSUAA instance.
```

2022-09-29 13:09 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Also adjust the route to use the region of your CF e.g. `cfapps.us10.hana.ondemand.com` and also adjust the route path to make it unique in the region.
```suggestion
Also, adjust the route to use the region of your CF, e.g., `cfapps.us10.hana.ondemand.com`, and the route path to make it unique in the region.
```

2022-09-29 13:11 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +In our example the service is reachable via (for you the URL will be different depending on landscape):
```suggestion
In our example, the service is reachable via (for you the URL will be different depending on landscape):
```

2022-09-29 13:12 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Let's investigate the implementation of `service-endpoint.ts` above the service will try to obtain a JSON web token (JWT) from the request.
This sentence reads a bit weird. Should the sentences be split?

2022-09-29 13:13 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +After the destination is created the service should return:
```suggestion
After the destination is created, the service should return:
```

2022-09-29 13:14 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +The response shows, that there is no JWT attached to the request.
```suggestion
The response shows that there is no JWT attached to the request.
```

2022-09-29 13:15 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +This task is done by the application router, the XSUAA and the identity provider (IdP).
```suggestion
This task is done by the application router, the XSUAA, and the identity provider (IdP).
```

approuter is mentioned more times than application router, I would use a single term.

2022-09-29 13:16 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +The details would be too much for this guide and you may have a look at [our approuter guide](../guides/how-to-use-the-approuter.mdx).
[nth] shorten then sentence and put it as a note

2022-09-29 13:17 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Once the user entered the credentials, the request is sent to the target with the JWT issued for the user and account.
```suggestion
Once the user enters their credentials, the request is sent to the target with the JWT issued for the user and account.
```

user and account?

2022-09-29 13:19 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +In a productive case the approuter may redirect requests to multiple applications.
```suggestion
In a productive case, the approuter may redirect requests to multiple applications.
```

2022-09-29 13:19 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +In our simple example there is just one route.
```suggestion
In our simple example, there is just one route.
```

2022-09-29 13:22 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You find the application code in the `multi-tenant-app` folder of the [sample repository](https://github.com/SAP-samples/cloud-sdk-js/tree/main/samples/multi-tenant-application).
[req] We mention already at the start of the guide that the code resides here. So we can shorten this to 'You find the application code in the `multi-tenant-app` folder' and then link the exact folder.

2022-09-29 13:23 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You find all files in `approuter` folder of the [samples repository](https://github.com/SAP-samples/cloud-sdk-js/tree/main/samples/multi-tenant-application):
[req] Same as for the multi-tenant folder, link the approuter folder and remove '...of the samples repository'

2022-09-29 13:24 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +- The `manifest.yml` contains the config for the approuter application
```suggestion
- The `manifest.yml` file contains the config for the approuter
```

Some line items end with a period and some don't. Please align lists

2022-09-29 13:24 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +- The `xs-app.json` the config for the route resolution.
```suggestion
- The `xs-app.json` file contains the config for the route resolution.
```

2022-09-29 13:25 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Please adjust the route property in the `manifest.yml`.
```suggestion
Please adjust the route property in the `manifest.yml` file.
```

2022-09-29 13:25 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Log into the provider account using `cf login` and then you call `cf push` from the `approuter` directory.
```suggestion
Log into the provider account using `cf login` and call `cf push` from the `approuter` directory.
```

2022-09-29 13:26 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +GET https://route-prefix-YOUR-SUBDOMAIN.cfapps.YOUR_REGION.hana.ondemand.com/
One placeholder has a - another a _

2022-09-29 13:26 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +When you follow this route you will get redirected to the `welcomeFile` defined in the `xs-app.json`.
```suggestion
When you follow this route you, will get redirected to the `welcomeFile` defined in the `xs-app.json`.
```

2022-09-29 13:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Once the application is deployed you will see a second application running next to your `multi-tenant-app`.
```suggestion
Once the approuter is deployed, you will see it running as a separate application next to your `multi-tenant-app`.
```

2022-09-29 13:31 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +When you open the application you see one route created by the manifest:
Here application refers to the approuter. There is a line below 'The `index.html` is located in the application.' It might be confusing to the user which is which.

2022-09-29 13:31 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +How did the routing work:
```suggestion
How does routing work:
```

2022-09-29 13:32 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +- In our simple scenario the `xs-app.json` defines only one route consisting of a `source`, `target` and `destination`.
```suggestion
- In our simple scenario, the `xs-app.json` file defines only one route consisting of a `source`, `target`, and `destination`.
```

2022-09-29 13:34 UTC, deekshas8 commented on sidebarsDocsJs.js
> +        'tutorials/multi-tenant-application',
[req] This should be the third item

2022-09-29 13:36 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You could imagine a database with a tenantId column to store consumer specific configuration.
```suggestion
You could imagine a database with a `tenantId` column to store consumer specific configuration.
```

2022-09-29 14:04 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +The selection is related to support issues appearing in the past and therefore it is not a complete guide.
[pp] I think lines 45 and 46 can be shortened to something like, This is not a detailed/comprehensive guide on the multi-tenancy topic in SAP BTP but rather covers only ...' and put inside a NOTE admonition.

2022-09-30 15:33 UTC, jjtang1985 commented on docs-js/tutorials/multi-tenant-application.mdx
> +However, the subscribed account does not know anything about the internal details of our application.
```suggestion
However, the subscriber account does not know anything about the internal details of our application.
```

2022-09-30 15:33 UTC, jjtang1985 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Therefore, the dependencies-endpoint provides the information that the destination service may be used also from the subscribed account.
```suggestion
Therefore, the `/dependencies` endpoint provides the information that the destination service may be used also from the subscriber account.
```

2022-10-04 07:58 UTC, FrankEssenberger commented on docs-js/tutorials/multi-tenant-application.mdx
> +The term multi-tenant application is more or less a synonym for a software as a service (SAAS) offering.
good idea, tried to reorder it. Have a look

2022-10-04 08:00 UTC, FrankEssenberger commented on docs-js/tutorials/multi-tenant-application.mdx
> +- The SAP BTP account in which the application is deployed is called the `provider account`.
yes that is nice

2022-10-04 08:22 UTC, FrankEssenberger commented on docs-js/tutorials/multi-tenant-application.mdx
> +- In the `service-endpoint.ts` a small implementation is provided.
Tried to improve it. Have a look

2022-10-04 08:26 UTC, FrankEssenberger commented on docs-js/tutorials/multi-tenant-application.mdx
> +Let's investigate the implementation of `service-endpoint.ts` above the service will try to obtain a JSON web token (JWT) from the request.
Tried to improve it.

2022-10-04 08:42 UTC, FrankEssenberger commented on docs-js/tutorials/multi-tenant-application.mdx
> +When you open the application you see one route created by the manifest:
change it to approuter applicaition and added the folder for the applicaiton containing the index as a link

2022-10-05 23:29 UTC, deekshas8 requested changes
I noticed a few more things (mainly grammatical or sentence structuring).

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +After you created the instance of the `SAAS provisioning service` in the provider account, you can create a subscription via the user interface.
```suggestion
After you have created an instance of the `SaaS provisioning service` in the provider account, you can create a subscription via the user interface.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +A subscription is only a route to the provider application including the unique subdomain of subscriber account.
```suggestion
A subscription is a route to the provider application, including the unique subdomain of the subscriber account.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Hence, a script in the `subscription-endpoint.ts` creates a route automatically:
```suggestion
To automate the onboarding of new accounts, the script in `subscription-endpoint.ts` does the following:
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +The code assume a destination with the name `cf-api` in the sample implementation which contains the access data for the CF API:
```suggestion
The code assumes a destination with the name `cf-api` in the sample implementation which contains the access data for the CF API:
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Once the destination is present you can subscribe the application and routes are created automatically.
```suggestion
Once the destination is present, you can subscribe to the application and routes are created automatically.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Log into your second SAP BTP account and create a subscription to the `multi-tenant-app` in the cockpit under **Service->Instances and Subscriptions**.
[req] 'under' is not a recommended word for [UI interaction](https://developers.google.com/style/ui-elements#verbs). Rephrase the sentence instead as:

Log into your second SAP BTP account. Go to **Service->Instances and Subscriptions** and create a subscription to the `multi-tenant-app`.

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +As an application developer you can use the token to determine the account which currently calls your code.
```suggestion
As an application developer, you can use the token to determine the account which currently calls your code.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +The code will remove the route from the app router and make the application not reachable anymore for that user.
```suggestion
The code will remove the route from the approuter and make the application unreachable for that consumer.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +However, up to know nothing subscriber specific is happening in the implementation.
```suggestion
However, up to now, nothing subscriber-specific is happening in the implementation.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +This chapter tries to elaborate a bit more how an actual multi-tenant application would look like and how the SAP Cloud SDK helps you.
```suggestion
This chapter elaborate a bit on what an actual multi-tenant application would look like and how the SAP Cloud SDK helps you.
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You extract the value from the JWT as shown in the minimal example:
```suggestion
You can extract the value from the JWT as shown in the example:
```

2022-10-05 23:29 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You could imagine a database with a `tenantId` column to store consumer specific configuration.
```suggestion
Imagine a database with a `tenantId` column to store consumer specific configuration.
```

2022-10-07 11:49 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +You find the `saas-registry-config.json` in the [samples repository](https://github.com/SAP-samples/cloud-sdk-js/tree/main/samples/cf-multi-tenant-application).
```suggestion
You can find the `saas-registry-config.json` in the [samples repository](https://github.com/SAP-samples/cloud-sdk-js/tree/main/samples/cf-multi-tenant-application).
```

2022-10-07 11:49 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +Of course, you want to automate onboarding of new accounts as much as possible.
```suggestion
```

2022-10-07 11:49 UTC, deekshas8 commented on docs-js/tutorials/multi-tenant-application.mdx
> +When you follow this route you, will get redirected to the `welcomeFile` defined in the `xs-app.json`.
```suggestion
When you follow this route, you will get redirected to the `welcomeFile` defined in the `xs-app.json`.
```

2022-10-07 11:54 UTC, deekshas8 approved these changes
LGTM. Feel free to merge after adding the code snippets.

2022-10-07 12:56 UTC, merged