[js] rename all `BusinessPartner*s*` to `BusinessPartner`
SAP/cloud-sdk pull request #1033
Opened 2022-09-29 08:59 UTC by shojisoma

## What Has Changed?

Closes https://github.com/SAP/cloud-sdk-backlog/issues/885

This renamed plural `BusinessPatners` to singular `BusinessPatner` 

## Manual Checks?

- [x] Check spelling and grammar, e.g., using Grammarly.
- [x] Verify links still work, e.g., if `id` or the name of a file is changed.
- [ ] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a new feature is added.

2022-09-29 09:51 UTC, deekshas8 requested changes

2022-09-29 09:51 UTC, deekshas8 commented on docs-js/tutorials/getting-started/2-execute-odata-request.mdx
> +import { BusinessPartnerController } from './business-partners/business-partners.controller';
[req] Please also change the file name(business-partners.controller) and directory(business-partners) to singular notation.

2022-09-29 10:31 UTC, shojisoma commented on docs-js/tutorials/getting-started/2-execute-odata-request.mdx
> +import { BusinessPartnerController } from './business-partners/business-partners.controller';
thank you for your checking. I changed the all plural to singular.

2022-10-04 12:58 UTC, deekshas8 approved these changes
LGTM

2022-10-04 13:17 UTC, merged