chore: Improve common docs
SAP/cloud-sdk pull request #1042
Opened 2022-10-04 09:10 UTC by deekshas8

## What Has Changed?

Closes https://github.com/SAP/cloud-sdk-backlog/issues/758

## Manual Checks?

- [ ] Check spelling and grammar, e.g., using Grammarly.
- [ ] Verify links still work, e.g., if `id` or the name of a file is changed.
- [ ] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a new feature is added.

2022-10-04 10:43 UTC, Johannes-Schneider commented
Looks good from the Java side. Thanks for taking care @deekshas8!

2022-10-05 09:13 UTC, MatKuhr commented on docs/about.mdx
> -- [Cloud Application Programming model (CAP)](./related-projects/cap.mdx)
@marikaner We aren't? :D

2022-10-05 09:15 UTC, MatKuhr approved these changes
lgtm from Java side

2022-10-05 16:16 UTC, marikaner requested changes
Wow! 400 lines deleted 😊 Way to go. I believe we may delete more and remove some more of the marketing speech. I may have left some nitpicky comments, we can definitely discuss this. I will run this locally tomorrow and read it in the docs directly (as opposed to on GitHub) to get a big picture of the current state.

2022-10-05 16:16 UTC, marikaner commented on docs/about.mdx
> +Check out the [getting started](/docs/java/guides/cap-sdk-integration) guide or the [step-by-step tutorial](https://developers.sap.com/tutorials/cloudsdk-integrate-cap.html) to use the SAP Cloud SDK
[q] I wonder how relevant this section really is. Does it matter what exactly CAP uses? I think the relevant information is - what is the difference between SDK and CAP.
[q] Why do we link specific Java documentation in the common overview page? Seems incorrect to me.

2022-10-05 16:16 UTC, marikaner commented on docs/about.mdx
>  - Support in [Business Application Studio](https://developers.sap.com/tutorials/appstudio-onboarding.html)
[q] What does this point mean? Is this relevant?

2022-10-05 16:16 UTC, marikaner commented on docs/about.mdx
>  - First-class documentation and [support](./support.mdx)
[pp] Marketing speech: "first-class"

2022-10-05 16:16 UTC, marikaner commented on docs/about.mdx
>  - Modular design and high-level of extensibility
[req] I think what is meant is "high level of extensibility"
[q] Is this a benefit and or capability?

2022-10-05 16:16 UTC, marikaner commented on docs/about.mdx
> +## Well-Integrated With the SAP Cloud Development Ecosystem
[req] I think it should be "well integrated".
[q] Is this section really relevant?

2022-10-05 16:16 UTC, marikaner commented on docs/community-call.mdx
> +id: community
[req] I think this page should be deleted because the community call does not exist anymore.

2022-10-05 16:16 UTC, marikaner commented on docs/support.mdx
> +At the SAP Cloud SDK, we do our best to provide best in class support experience.
[req] WOW! "provide best in class support experience"

2022-10-05 16:16 UTC, marikaner commented on docs/support.mdx
> +The official support language is English.
[q] I am honstely not sure whether any of this is relevant?

2022-10-06 13:56 UTC, deekshas8 commented on docs/about.mdx
> +- Robust connectivity abstractions for SAP BTP for managing destinations, authentication, multitenancy, CSRF, ETags, and more.
Removed those terms.

2022-10-06 14:04 UTC, deekshas8 commented on docs/about.mdx
>  - Modular design and high-level of extensibility
I feel like all of them address SDK 'Capabilities'. I'll remove Benefits.

2022-10-06 14:14 UTC, deekshas8 commented on docs/support.mdx
> +At the SAP Cloud SDK, we do our best to provide best in class support experience.
Removed this line.

2022-10-06 14:19 UTC, deekshas8 commented on docs/about.mdx
>  - Support in [Business Application Studio](https://developers.sap.com/tutorials/appstudio-onboarding.html)
I kept it as it was there. I honestly don't have enough idea about BAS to say/not say that having sdk support in it is a capability worth mentioning.

2022-10-07 09:13 UTC, deekshas8 commented on docs/about.mdx
> +Check out the [getting started](/docs/java/guides/cap-sdk-integration) guide or the [step-by-step tutorial](https://developers.sap.com/tutorials/cloudsdk-integrate-cap.html) to use the SAP Cloud SDK
Removed the Java part. I re-wrote the section with text from this [blog](https://blogs.sap.com/2019/05/06/faq-on-sap-cloud-sdk/#_Toc8017182). Please have a look

2022-10-07 10:19 UTC, deekshas8 commented on docs/about.mdx
> +- Type-safe client code generators for OData and OpenAPI services that seamlessly integrate with other SAP Cloud SDK value-adds.
rewrote this as; - Code generators for generating typed clients for OData and OpenAPI services, which seamlessly integrate with other SAP Cloud SDK features.

2022-10-07 10:19 UTC, deekshas8 commented on docs/about.mdx
> +The goal is to simplify working in the SAP ecosystem by abstracting the complexities of the SAP BTP and allowing you to focus on the application's business logic.
Shortened and re-phrased it: It abstracts the complexities of the SAP BTP, thus allowing you to focus on the application's business logic.

2022-10-07 10:50 UTC, deekshas8 commented on docs-js/video/calm.mdx
> +They put together an amazing demo of creating a locally hosted CAP service and running API calls against it with a type-safe client by SAP Cloud SDK for JavaScript.
Tried to improve it.

2022-10-11 12:00 UTC, marikaner commented on docs/about.mdx
> +## Well-Integrated With the SAP Cloud Development Ecosystem
But it is really true? Has anyone ever tested ariba, fieldglass or sales cloud explicitly? Imagine you would read about the SDK for the first time because you want to understand whether you can use it for your project. Is this a section you would read? For me this reads like an incomplete list that was taken from API Hub. Why isn't Workflow in this list then?

Would you be fine with just removing the section?

2022-10-11 12:22 UTC, marikaner requested changes
I like it much better now!

2022-10-11 12:22 UTC, marikaner commented on docs/about.mdx
> +## Feedback
[q] Do we need this section? Seems duplicate with the support section...

2022-10-11 15:26 UTC, marikaner approved these changes
Much better in my opinion

2022-10-12 08:03 UTC, merged