chore: remove faq
SAP/cloud-sdk pull request #1052
Opened 2022-10-10 03:51 UTC by tomfrenken

## What Has Changed?

This PR removes the JS FAQ page and instead adds the important information to the information page.
Also shuffled some content around for readability purposes.

2022-10-10 09:58 UTC, deekshas8 commented on docs-js/overview.mdx
> +All core libraries are available as open-source npm packages in the @sap-cloud-sdk scope on npm under the Apache 2.0 license.
```suggestion
All core libraries are available as open-source npm packages in the `@sap-cloud-sdk` scope on npm under the Apache 2.0 license.
```

2022-10-10 09:58 UTC, deekshas8 commented on docs-js/overview.mdx
> +## Contributing
[pp] I would put this at the end after all main info sections

2022-10-10 09:58 UTC, deekshas8 commented on docs-js/overview.mdx
> +For details check our [release policy](release-policy.mdx).
```suggestion
For details, check the [release policy](release-policy.mdx).
```

2022-10-10 09:58 UTC, deekshas8 commented on docs-js/overview.mdx
> +You can check our [automated tests](https://github.com/SAP/cloud-sdk-js/actions/workflows/build.yml?query=branch%3Amain) to see a list of all currently supported and tested versions.
```suggestion
You can check the [automated tests](https://github.com/SAP/cloud-sdk-js/actions/workflows/build.yml?query=branch%3Amain) to see a list of all supported and tested versions.
```

[req] Avoid 'current' (it's implied)

2022-10-10 09:58 UTC, deekshas8 commented on docs-js/overview.mdx
> +## Feature Matrix
![image](https://user-images.githubusercontent.com/88374536/194841118-676db36c-54b8-4c09-8f85-061bc65bd775.png)

The Feature Matrix heading shows up like this

2022-10-10 16:01 UTC, FrankEssenberger commented on docs-js/faq.mdx
> -### Do You Support All OData Features?
[q] I do not see thins information in an other section?

2022-10-10 16:03 UTC, FrankEssenberger requested changes
I have a few question once they are answer please merge. From a funcitonal point of view the filter on the side bar works.

2022-10-11 09:18 UTC, tomfrenken commented on docs-js/faq.mdx
> -### What Versions of OData Protocol Do You Support?
It's in the overview:

```
### Supported OData and OpenAPI Versions
The SAP Cloud SDK supports OData v2 and v4, as well as OpenAPI 2.0 and 3.0.
```

2022-10-11 09:19 UTC, tomfrenken commented on docs-js/faq.mdx
> -### Do You Support All OData Features?
Correct, it wasn't part of the information that we want to keep, according to the ticket.

2022-10-11 09:21 UTC, tomfrenken commented on docs-js/overview.mdx
> +
Because licensing is now its own section (which contains more information), therefore it would be a duplicate, or do you think it should be in this section as well?

2022-10-11 09:22 UTC, tomfrenken commented on docs-js/overview.mdx
> +## Contributing
Agreed, I would still put it above the feature matrix though, because I doubt anyone scrolls past the giant table

2022-10-11 09:25 UTC, tomfrenken commented on docs-js/overview.mdx
> +## Feature Matrix
Indeed, the live version has the same issue, I'll see how I can fix it

2022-10-11 09:39 UTC, FrankEssenberger approved these changes

2022-10-11 10:31 UTC, merged