chore: improve slugs
SAP/cloud-sdk pull request #1079
Opened 2022-10-19 08:45 UTC by tomfrenken

## What Has Changed?

This PR improves all our slugs, fixes and introduces new redirects, and removes some deprecated docs.

Part of https://github.com/SAP/cloud-sdk-backlog/issues/759

2022-10-20 06:34 UTC, FrankEssenberger commented
Relates: https://github.com/SAP/cloud-sdk-backlog/issues/759

2022-10-20 06:38 UTC, FrankEssenberger commented on STYLEGUIDE.md
> +Function words are he are words like “a”, “the” and “and”.
```suggestion
Function words are words like “a”, “the” and “and”.
```

2022-10-20 06:45 UTC, FrankEssenberger commented on STYLEGUIDE.md
> +Therefore don’t just filter out unnecessary function words, but really all the words that you don’t need.
```suggestion
Therefore remove not only function words but also other unnecessary words.
```

2022-10-20 06:47 UTC, FrankEssenberger commented on STYLEGUIDE.md
> +Only use lowercase letters only in our slugs, otherwise we could create duplicate content by mixing uppercase and lowercase letters.
```suggestion
Use lowercase letters in our slugs.
```

2022-10-20 06:54 UTC, FrankEssenberger commented on docusaurus.config.js
> +        redirects: [
[q] there are much more changed `ids` in the `.mdx` than redirects here. For example mail-client  has changed but there is no redirect here. Is this correct?

2022-10-20 06:55 UTC, FrankEssenberger requested changes
Content looks good not sure about the redirects.

2022-10-20 07:31 UTC, tomfrenken commented on docusaurus.config.js
> +        redirects: [
Yes, some ids didn't change the slug, as the id matches the file name.

2022-10-20 07:32 UTC, FrankEssenberger commented on docusaurus.config.js
> +        redirects: [
ok if you are sure all necessary redirects are in I approve.

2022-10-20 07:32 UTC, FrankEssenberger approved these changes

2022-10-20 07:51 UTC, jjtang1985 requested changes
Looks good.
My major concern is, the "sap cloud sdk js" keywords should not be used in the slugs.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/features/odata/execute-odata-request.mdx
> +Once the request is configured use the `execute` function and pass a [destination](../connectivity/destination.mdx) to it.
[q] Is this a fix?

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/features/connectivity/destination.mdx
> +id: destinations
```suggestion
id: destination
```
[req] I guess the id and URL should be singular, because they are used as keywords and should be shorter.
[pp]For title, I would also go with singular, as long as it's a page instead of a collection.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/features/connectivity/destination-cache-isolation.mdx
> +id: destination-cache-isolation
```suggestion
id: destination-cache
```
[pp] I would remove `isolation` from the slug, to keep it shorter

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/tutorials/address-manager/read-addresses.mdx
> +In real applications, you would use a real SAP S/4HANA system and the [destination service](../../features/connectivity/destination.mdx) to avoid leaking private or secret information through hard-co
[pp] The current URL looks like:
`https://sap.github.io/cloud-sdk/docs/js/tutorials/address-manager/read-addresses`
where address is duplicate.
We can e.g., use `read` as a shorter slug.

Similarly, there is a page about write operation.
If we touch the "read" page, that can use e.g., "write" as the id.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/video/calm.mdx
> +id: cloud-sdk-with-calm-and-cap
```suggestion
id: calm-cap
```
[req] As one of the AC, we should not put "cloud sdk" in the slug, as they are shown in the base URL.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/bas-external-system.mdx
> +id: connect-external-system-to-bas
```suggestion
id: bas
```
I would just use a short version.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/how-to-add-resilience.mdx
> +id: resilience-with-cloud-sdk
```suggestion
id: resilience
```
[req] cloud sdk should not be shown.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/how-to-use-the-approuter.mdx
> +id: approuter-with-cloud-sdk
```suggestion
id: approuter
```
[req] remove cloud sdk

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +id: migrate-cf-to-kubernetes
```suggestion
id: kubernetes
```
[pp] I would use shorter slug

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/sdk-in-browser.mdx
> +id: sdk-in-browser
```suggestion
id: browser
```
[req] remove sdk

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/upgrade-to-version-2.mdx
> +We introduced a new [(de-)serialization](../features/odata/odata-v2-client#customize-de-serialization) to make this more flexible.
[pp] I would use "update-version-2" as a shorter slug

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/trust-and-key-stores.mdx
> +id: trust-and-key-stores
```suggestion
id: trust-key-store
```
[pp] I would keep it shorter.

2022-10-20 07:51 UTC, jjtang1985 commented on docs-js/guides/migrate-to-os.mdx
> +id: migrate-to-open-source-cloud-sdk
[pp] I would vote for deleting this page, as the open source happened 3 years ago.

2022-10-20 07:51 UTC, jjtang1985 commented on STYLEGUIDE.md
> +## Slugs
[req] Please add a section about "not using 'sap' 'cloud' 'sdk' 'js'", as they are shown in the base URL, which is duplicate.

2022-10-20 08:46 UTC, marikaner requested changes
I think there are some slugs that can be shortend. Otherwise, what @jjtang1985 said 😊

2022-10-20 08:46 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +id: destinations
[q] Are there any rules on this "out there"? I would have intuitively disagreed with @jjtang1985, but when I think of request builders, I would probably rather not make it plural.

2022-10-20 08:46 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +Additional information on how to retrieve JWTs can be found [here](../../guides/how-to-retrieve-jwt.mdx).
[q] Are you sure the '.mdx' is needed??
[q] Shouldn't the slug to the guide be shorter too, e.g. 'jwt' or 'retrieve-jwt'?

2022-10-20 08:46 UTC, marikaner commented on docs-js/features/connectivity/generic-http-client.mdx
> +id: generic-http-client
[req] "generic" is not important, I would just call this "http-client"

2022-10-20 08:46 UTC, marikaner commented on docs-js/features/connectivity/proxy.mdx
> +id: proxy
[q] Same question as above, I would intuitively expect this to be plural, but maybe other smart people have thought about this already?

2022-10-20 08:46 UTC, marikaner commented on docs-js/guides/debug-remote-app.mdx
> +id: debug-remote-app
[pp] I find this misleading. How about 'remote-debugging'?

2022-10-20 08:46 UTC, marikaner commented on docs-js/guides/upgrade-to-version-2.mdx
> +We introduced a new [(de-)serialization](../features/odata/odata-v2-client#customize-de-serialization) to make this more flexible.
[pp] I prefer the current version, but no strong opinion.

2022-10-20 08:46 UTC, marikaner commented on docs-js/tutorials/address-manager/read-addresses.mdx
> +In real applications, you would use a real SAP S/4HANA system and the [destination service](../../features/connectivity/destination.mdx) to avoid leaking private or secret information through hard-co
[pp] I think I disagree here, because it could also be read business partners. However, I think that maybe the address is not really relevant to what people would learn, I guess it is mostly about 'read-requests'. But I doubt that this is better, maybe you have more ideas in this direction...

2022-10-20 08:46 UTC, marikaner commented on docs-js/tutorials/getting-started/introduction.mdx
> +- [destination lookup](../../features/connectivity/destinations#creating-destinations-manually) for destinations created manually or referenced by name.
[req] Currently the page is called "destination". Please make sure to be consistent throughout the docs.

2022-10-20 08:46 UTC, marikaner commented on docs-js/video/calm.mdx
> +id: cloud-sdk-with-calm-and-cap
Or just 'calm'

2022-10-20 08:46 UTC, marikaner commented on docusaurus.config.js
> +            from: '/docs/js/guides/how-to-add-resilience'
[req] I think this is already in some other comments, but those still are very long.

2022-10-20 12:54 UTC, tomfrenken commented on docs-js/features/odata/execute-odata-request.mdx
> +Once the request is configured use the `execute` function and pass a [destination](../connectivity/destination.mdx) to it.
When linking to other pages with a relative path, either a relative path which ends with the id (or slug) can be used, or a relative path which links to the file name can be used, though when it is the file name the `.mdx` has to be appended. In this case the slug changed from `desitnation` to `destinations`, so I appended the .mdx, I could also have linked to `destinations` instead. So not a fix, just a different link was now necessary

2022-10-20 12:55 UTC, tomfrenken commented on docs-js/features/connectivity/destination.mdx
> +Additional information on how to retrieve JWTs can be found [here](../../guides/how-to-retrieve-jwt.mdx).
When linking to other pages with a relative path, either a relative path which ends with the id (or slug) can be used, or a relative path which links to the file name can be used, though when it is the file name the `.mdx` has to be appended. Regarding your 2nd question, the slug is in fact shorter!

2022-10-20 12:58 UTC, tomfrenken commented on docusaurus.config.js
> +            from: '/docs/js/guides/how-to-add-resilience'
Agreed, I will remove the "with-cloud-sdk" part

2022-10-20 12:59 UTC, tomfrenken commented on docusaurus.config.js
> +            from: '/docs/js/guides/how-to-add-resilience'
Actually, I have some ideas to make the others shorter as well, will do so now 👍

2022-10-24 07:05 UTC, tomfrenken commented on docs-js/features/connectivity/proxy.mdx
> +id: proxy
While searching for a preferred way online I didn't find a clear answer to this, however, I think it was somewhat leaning toward the plural form, therefore I will use it

2022-10-24 07:06 UTC, tomfrenken commented on docs-js/tutorials/getting-started/introduction.mdx
> +- [destination lookup](../../features/connectivity/destinations#creating-destinations-manually) for destinations created manually or referenced by name.
It's changed to `destinations` because I changed the slug from destination to destinations, so should be fine 👍

2022-10-24 07:07 UTC, tomfrenken commented on docs-js/tutorials/address-manager/read-addresses.mdx
> +In real applications, you would use a real SAP S/4HANA system and the [destination service](../../features/connectivity/destination.mdx) to avoid leaking private or secret information through hard-co
Since there is no strong opinion I'll just go with Junjie's suggestion here, if it's only `read` / `write` it should be generic enough for both cases you mentioned (IMO)

2022-10-26 08:14 UTC, jjtang1985 commented on docs-js/features/odata/generate-odata-client.mdx
> +id: generate-odata-client
```suggestion
id: generate-client
```
odata is duplicated

2022-10-26 08:14 UTC, jjtang1985 commented on docs-js/features/odata/execute-odata-request.mdx
> +id: execute-odata-request
```suggestion
id: execute-request
```
odată is duplicated

2022-10-26 08:14 UTC, jjtang1985 commented on docs-js/features/openapi/execute-openapi-request.mdx
> +id: execute-openapi-request
```suggestion
id: execute-request
```

2022-10-26 08:14 UTC, jjtang1985 commented on docs-js/features/openapi/generate-openapi-client.mdx
> +id: generate-openapi-client
```suggestion
id: generate-client
```

2022-10-28 15:52 UTC, jjtang1985 approved these changes
LGTM.
Please feel free to merge when the pipeline is green.

2022-11-01 08:34 UTC, marikaner commented on STYLEGUIDE.md
> +<!-- Disable vale off -->
[q] Why is this necessary? And what does it do?

2022-11-01 08:34 UTC, marikaner commented on STYLEGUIDE.md
> +Therefore we should always set the `id` property and consider the following:
[req] Use active voice and do not use "we".
[req] Please add a reason why the `id` should be set.

(also not 100% active)
```suggestion
By default, the slug is based on the filename of your MDX document.
You should overwrite it by setting the `id` in the front matter to avoid unintended changes if the filename is changed.
```

2022-11-01 08:34 UTC, marikaner commented on STYLEGUIDE.md
> +### Function Words
[req] From here on the titles are not in the imperative anymore. Please adjust it, so that in the overview, the rule is clearer.

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/connectivity/generic-http-client.mdx
> +In case you want to use an OpenAPI client, please refer to the [Execute a Request Using a Generated OpenAPI Client](../openapi/execute-openapi-request.mdx) page.
[q] Not sure if I missed this somewhere else, but shouldn't this be:
```suggestion
In case you want to use an OpenAPI client, please refer to the [Execute a Request Using a Generated OpenAPI Client](../openapi/execute-request) page.
```

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/connectivity/generic-http-client.mdx
> +The SAP Cloud SDK for JavaScript can generate clients for [OData](../odata/execute-odata-request.mdx) and [OpenAPI](../openapi/execute-openapi-request.mdx).
Same as above

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/connectivity/proxy.mdx
> +This will trigger the destination lookup as described [here](destination.mdx).
Same here

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/odata/execute-odata-request.mdx
> +Once the request is configured use the `execute` function and pass a [destination](../connectivity/destination.mdx) to it.
[req] I think it is better if we agree to link to the actual links, that keeps it up to date. I would BTW also propose to change the filename to destinations ;)

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/odata/odata-v4-client.mdx
> +For more details on **how to execute requests** using a OData type-safe client by the SAP Cloud SDK, refer to [this guide](./execute-odata-request.mdx).
```suggestion
For more details on **how to execute requests** using a OData type-safe client by the SAP Cloud SDK, refer to [this guide](./execute-request).
```

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/openapi/execute-openapi-request.mdx
> +The usage of the OpenAPI clients is similar to the clients for [OData](../odata/execute-odata-request.mdx).
Same here

2022-11-01 08:34 UTC, marikaner commented on docs-js/features/openapi/execute-openapi-request.mdx
> +You invoke a function of an API, optionally configure your request and then execute it against a [destination](../connectivity/destination.mdx):
Same here.

2022-11-01 08:34 UTC, marikaner commented on docs-js/getting-started.mdx
> +- [Address Manager](./tutorials/address-manager/read-addresses.mdx) - Build an Address Manager with the SAP Cloud SDK.
Same here

2022-11-01 08:34 UTC, marikaner commented on docs-js/guides/bas-external-system.mdx
> +The SAP Cloud SDK has a [destination lookup](../features/connectivity/destination.mdx) priority considering environment variables first.
I'll stop adding comments for those ;)

2022-11-02 10:26 UTC, tomfrenken commented on STYLEGUIDE.md
> +<!-- Disable vale off -->
Removed, I think I added it by accident

2022-11-02 11:04 UTC, tomfrenken commented on docs-js/features/connectivity/generic-http-client.mdx
> +In case you want to use an OpenAPI client, please refer to the [Execute a Request Using a Generated OpenAPI Client](../openapi/execute-openapi-request.mdx) page.
I think referencing by `.mdx` everywhere is the better choice, if you update the slug, you would have to update every single link, whereas if you reference by `.mdx`, the updated slug will automatically be used, which should reduce effort if we decide to change a slug in the future. I'll add it to the style guide!

2022-11-02 14:21 UTC, marikaner approved these changes

2022-11-02 14:26 UTC, merged