Improve and apply style guide (Part 1)
SAP/cloud-sdk pull request #1090
Opened 2022-10-27 08:47 UTC by florian-richter

## What Has Changed?

Add more details to style guide and improve some sections of the documentation.
Please only review the changed parts, not all rules are applied everywhere (but obviously no changed part should be worse now).

Given the size of the original issue, I decided it is better to merge this piece by piece.
Therefore this will only be part 1 of possibly many.

## Manual Checks?

- [x] Check spelling and grammar, e.g., using Grammarly.
- [x] Verify links still work, e.g., if `id` or the name of a file is changed.

2022-10-27 11:19 UTC, deekshas8 requested changes

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/connectivity/destination.mdx
> +Replace `HEADER_KEY` and `QUERY_KEY` with the name of your headers or query parameters and set the respective values.
```suggestion
Replace `HEADER_KEY` and `QUERY_KEY` with the name of the headers or query parameters and set the respective values.
```

Avoid your

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/connectivity/generic-http-client.mdx
> +This guide explains how you can execute arbitrary HTTP requests using the SAP Cloud SDK for JavaScript.
```suggestion
This guide explains how to execute arbitrary HTTP requests using the SAP Cloud SDK for JavaScript.
```

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/connectivity/generic-http-client.mdx
> +If you use OData or OpenAPI, you should use generated clients if possible.
```suggestion
Use generated clients for OData or OpenAPI services, if possible.
```

[info] Imperative

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/connectivity/generic-http-client.mdx
> +The `executeHttpRequest()` function returns a promise of <LinkToLatestJsApiDocs slug="interfaces/sap_cloud_sdk_http_client.HttpResponse" name="HttpResponse" />.
```suggestion
The `executeHttpRequest()` function returns a promise of type<LinkToLatestJsApiDocs slug="interfaces/sap_cloud_sdk_http_client.HttpResponse" name="HttpResponse" />.
```

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/odata/common/batch/changeset.mdx
> +You have to combine them in a changeset, which in turn can be passed to the `batch()` function.
[req] Changeset is a code element I think

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/odata/common/batch/changeset.mdx
> +Once we execute the batch request, we get a list of `BatchResponse`s, which in this example contains one response only, i.e. the one for the changeset.
[info] Don't pluralize code -> Not sure if this was missed or you plan to do it the next PRs.

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/odata/common/batch/responses.mdx
> +- `isSuccess()` - to check that the response is either a `ReadResponse` or of type `WriteResponses`
[info] [Use colon before descriptions.](https://github.com/SAP/cloud-sdk/blob/main/STYLEGUIDE.md#use-description-list-with-headings-for-describing-terms). Just pointing it out since you already formatted this

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/features/odata/common/entity/entity-builder.mdx
> +To achieve this, pass an object the `withCustomFields()` method, where the keys denote the names of the custom fields and the values their respective values.
```suggestion
To achieve this, pass an object to the `withCustomFields()` method, where the keys denote the names of the custom fields and the values their respective values.
```

2022-10-27 11:19 UTC, deekshas8 commented on docs-js/tutorials/address-manager/read-addresses.mdx
> +As for `select()`, you can use the properties of the `BusinessPartner` entity directly for filtering.
```suggestion
As for the `select()` function, you can use the properties of the `BusinessPartner` entity directly for filtering.
```

2022-10-27 14:06 UTC, florian-richter commented on docs-js/features/odata/common/batch/changeset.mdx
> +You have to combine them in a changeset, which in turn can be passed to the `batch()` function.
Changesets are OData concepts. I would assume that it is treated the same as something like "OAuth" which should not be formatted as code (as in the example in line 571 of the styleguide)

2022-10-27 14:07 UTC, florian-richter commented on docs-js/features/odata/common/batch/changeset.mdx
> +Once we execute the batch request, we get a list of `BatchResponse`s, which in this example contains one response only, i.e. the one for the changeset.
This will be part of a follow-up PR. Thanks for pointing it out though 😊

2022-10-27 14:33 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +"[{\"name\": \"TESTINATION\", \"url\": \"http://url.hana.ondemand.com\", \"username\": \"DUMMY_USER\", \"password\": \"EXAMPLE_PASSWORD\"}]"
I am somewhat hesitant to touch this. `hana.ondemand.com` seems reasonable so I would say we can keep it like this for now.

2022-10-27 14:34 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +Note that this approach is **not suitable for multi-tenant scenarios**, because only the destination service can return destinations for different tenants.
I added admonitions but left the critical points in bold to put a lot of focus on this since it is security relevant. I agree it should be part of the guide but I don't have a good rule of thumb in mind... I'll add a ticket to remind us.

2022-10-27 14:38 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +Note that this approach is **not suitable for multi-tenant scenarios**, because only the destination service can return destinations for different tenants.
https://github.com/SAP/cloud-sdk-backlog/issues/940

2022-10-27 14:45 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +The selection strategy can be passed as an optional argument to the `execute()` method.
I think that `execute()` on typed clients are methods, right?

2022-10-28 07:59 UTC, deekshas8 commented on docs-js/features/connectivity/destination.mdx
> +The selection strategy can be passed as an optional argument to the `execute()` method.
Yes, you're right. Please ignore my comment

2022-10-28 08:05 UTC, deekshas8 commented on docs-js/features/odata/common/batch/changeset.mdx
> +You have to combine them in a changeset, which in turn can be passed to the `batch()` function.
Agreed. But in this case however, since we talk about `batch()` as a function in the sdk and not just an OData concept, I thought changeset should be treated the same, since we do have a `changeset()` function in the sdk (which the user should use to combine change requests).

2022-10-28 08:15 UTC, deekshas8 commented on docs-js/tutorials/address-manager/read-addresses.mdx
> +As for the `select()` function, you can use the properties of the `BusinessPartner` entity directly for filtering.
I realized that `select()`, `equals()`, `notEquals()`, `greaterThan()`, `greaterOrEqual()` and `getByKey()` are all methods

2022-10-28 08:16 UTC, deekshas8 approved these changes
LGTM. Left a comment about 'method'.

2022-10-28 14:47 UTC, merged