chore: update instructions for sdk in browser
SAP/cloud-sdk pull request #1091
Opened 2022-10-27 09:03 UTC by deekshas8

## What Has Changed?

Closes: https://github.com/SAP/cloud-sdk-backlog/issues/920

Updated instructions for compiling angular app 

## Manual Checks?

- [ ] Check spelling and grammar, e.g., using Grammarly.
- [ ] Verify links still work, e.g., if `id` or the name of a file is changed.
- [ ] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a new feature is added.

2022-10-27 09:19 UTC, FrankEssenberger commented on docs-js/guides/sdk-in-browser.mdx
> +With webpack, it is possible to [load resources](https://webpack.js.org/plugins/normal-module-replacement-plugin/) for local or productive usage.
[pp] I would prefer to see the switch in action - do you have in one case the `destinationName:XYZ` and set the env somewhere? You could also use the `destinations` environment variable.

2022-10-27 09:22 UTC, FrankEssenberger commented on docs-js/guides/sdk-in-browser.mdx
> +The Angular framework is used to illustrate the usage.
Could you add also a short section on react so that we have both covered?

2022-10-27 09:22 UTC, FrankEssenberger requested changes
Add react section

2022-10-28 06:25 UTC, FrankEssenberger commented on docs-js/guides/sdk-in-browser.mdx
> +- Add the corresponding library of the node.js core modules in `devDependencies` in your `package.json` file
```suggestion
- Add the corresponding library of the node.js core modules or the browserified version in `devDependencies` in your `package.json` file
```

2022-10-28 06:27 UTC, FrankEssenberger commented on docs-js/guides/sdk-in-browser.mdx
> +- Add the corresponding library of the core node.js modules in `devDependencies` in your `package.json` file
[req] Mention the `rewire` dependency and say that the start command needs to be adjusted. Otherwise the config-overrides.js is not considered.

2022-10-28 06:27 UTC, FrankEssenberger commented on docs-js/guides/sdk-in-browser.mdx
> +- Create a custom webpack configuration named `node-webpack.config.js` and list the node modules
[q] Do you need to reference the file-name somewhere so that it is considered? If so mention this.

2022-10-28 06:28 UTC, FrankEssenberger approved these changes
LGTM - Please have a look at my suggestions

2022-10-28 08:22 UTC, deekshas8 commented on docs-js/guides/sdk-in-browser.mdx
> +- Create a custom webpack configuration named `node-webpack.config.js` and list the node modules
It is used in the next step's code snippet. But i'll explicitly mention it 👍🏽

2022-10-28 08:51 UTC, merged