Add documentation on batch
SAP/cloud-sdk pull request #11
Opened 2020-11-10 09:02 UTC by marikaner

Improve and extend batch documentation.

2020-11-10 15:31 UTC, florian-richter requested changes

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Change request cannot be passed to a batch request directly.
Either 
> change requests cannot ...
or
> A change request cannot ...

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +They have to be combined in a changset, which in turn an be passed to the batch request.
```suggestion
They have to be combined in a changset, which in turn can be passed to the batch request.
```

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Those contain the raw response information of each subrequest, the subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
```suggestion
Those contain the raw response information of each subrequest.
The subresponse of a changeset request can either be a `WriteResponse` or an `ErrorResponse`.
```

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Those contain the raw response information of each subrequest, the subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
I changed WriteResponses to the singular form. Not sure if the plural was intended!

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Successful requests can be cast to `WriteResponses` which contains all subresponses for the changeset request.
In the JS context, how do you cast something to a type? (in typescript it's `as NEW_TYPE` but you can always do that, it's just sometimes wrong).

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Each `WriteResponse` contains the HTTP code and can contain the raw body and the constructor of the entity that was parsed from the response, depending on whether there was a response.
> , depending on whether there was a response.

How can the batch succeed if there was no response at all for a part of a changeset? I guess what is meant is that there the response had no body.

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Create requests typically do not return a response.
response or body (aka `204 No Content` or `201 Created` is still a response in my understanding)

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +In order to work with an instance of an entity given in a `WriteResponse`, you can use the `.as` method, that allows you to transform the raw data into an instance of the given constructor.
Consider adding that the raw body is a string for people that may not be as experienced.

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Note that the response cannot exist, so you should only call this method if you know that there is data.
```suggestion
Note that the response may not exist, so you should only call this method if you know that there is data.
```

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Therefore, it is crutial to check responses for success, before casting them to `WriteResponses`.
```suggestion
Therefore, it is crucial to check responses for success, before casting them to `WriteResponses`.
```

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/configure-serialization.mdx
> +Serialize subreqeust path relative to entity:
```suggestion
Serialize subrequest path relative to entity:
```

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/configure-serialization.mdx
> +Serialize subreqeust path as absolute URL:
```suggestion
Serialize subrequest path as absolute URL:
```

2020-11-10 15:31 UTC, florian-richter commented on docs/js/features/odata/common/batch/serialization.mdx
> +Every "atomic" request is serialized to a string of this kind, while GET and DELETE requests do not provide a payload.
```suggestion
Every "atomic" request is serialized to a string of this kind, while `GET` and `DELETE` requests do not provide a payload.
```

2020-11-10 15:57 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Change request cannot be passed to a batch request directly.
```suggestion
Change requests cannot be passed to a batch request directly.
```

2020-11-10 15:58 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Those contain the raw response information of each subrequest, the subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
No it was correct. I know it's weird 🙁

2020-11-10 16:00 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Successful requests can be cast to `WriteResponses` which contains all subresponses for the changeset request.
That is what is meant here, I will rephrase it to 'should'

2020-11-10 16:00 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Those reponses can be accessed by `.responses` and have the type `WriteResponse`.
```suggestion
Those responses can be accessed by `.responses` and have the type `WriteResponse`.
```

2020-11-10 16:01 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Each `WriteResponse` contains the HTTP code and can contain the raw body and the constructor of the entity that was parsed from the response, depending on whether there was a response.
```suggestion
Each `WriteResponse` contains the HTTP code and can contain the raw body and the constructor of the entity that was parsed from the response, depending on whether there was a body in the response.
```

2020-11-10 16:01 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Each `WriteResponse` contains the HTTP code and can contain the raw body and the constructor of the entity that was parsed from the response, depending on whether there was a response.
Correct, I adjusted it.

2020-11-10 16:02 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Create requests typically do not return a response.
```suggestion
Create and delete requests typically do not have a response body.
```

2020-11-10 16:02 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +Create requests typically do not return a response.
Yeah, I fixed it.

2020-11-10 16:03 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +In order to work with an instance of an entity given in a `WriteResponse`, you can use the `.as` method, that allows you to transform the raw data into an instance of the given constructor.
```suggestion
In order to work with an instance of an entity given in a `WriteResponse`, you can use the `.as` method, that allows you to transform the raw string body into an instance of the given constructor.
```

2020-11-10 16:04 UTC, marikaner commented
@florian-richter thanks, I fixed everything, feel free to check again.

2020-11-11 08:12 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +The subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
Maybe this can be improved by pointing out that there could be a collection of responses called `WriteResponses` or in case of failure a single `ErrorResponse`?

2020-11-11 08:12 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +Those contain the raw response information of each subrequest, the subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
Maybe this can be improved by pointing out that there could be a collection of responses called `WriteResponses` or in case of failure a single `ErrorResponse`?

2020-11-11 08:16 UTC, florian-richter approved these changes
See my comments regarding the "WriteResponses" and one improvement. Otherwise LGTM

2020-11-11 08:16 UTC, florian-richter commented on docs/js/features/odata/common/batch/combining-requests.mdx
> +The get requests are added to the batch request directly without wrapping.
```suggestion
The `GET` requests are added to the batch request directly without wrapping.
```

2020-11-11 08:17 UTC, florian-richter commented on docs/js/features/odata/common/batch/changeset.mdx
> +The subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
Maybe this can be improved by pointing out that there could be a collection of responses called `WriteResponses` or in case of failure a single `ErrorResponse`? (sorry if it was posted multiple times... github trolled me a bit)

2020-11-11 08:30 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +The subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
```suggestion
The response to a changeset request can either be a collection of the subresponses to the subrequests of the changeset of type `WriteResponses` or an `ErrorResponse`.
```

2020-11-11 08:32 UTC, marikaner commented on docs/js/features/odata/common/batch/changeset.mdx
> +The subresponse of a changeset request can either be `WriteResponses` or an `ErrorResponse`.
I rephrased it a bit. I found it difficult to express because the name of the type is not so great... Maybe something for the 2.0 discussion...

2020-11-11 08:32 UTC, merged