Branch v3 js docs
SAP/cloud-sdk pull request #1138
Opened 2022-11-21 15:52 UTC by fwilhe

Branched v3 docs for js sdk

Default (for now) is v2. V3 docs have an 'unreleased' marker.

2022-11-21 16:23 UTC, deekshas8 requested changes

2022-11-21 16:23 UTC, deekshas8 commented on docusaurus.config.js
> +            badge: false
```suggestion
            badge: false,
            path: 'v3'
```

The paths have a `next` instead of `v3` (e.g. /cloud-sdk/docs/js/next/overview)

2022-11-21 17:26 UTC, deekshas8 commented on docusaurus.config.js
> +            path: 'v2',
```suggestion
```

[req] From my understanding (also described in the table [here](https://docusaurus.io/docs/versioning#overview)), the latest doc, which is v2 (as v3 is still wip), should still be accessible at `/cloud-sdk/docs/js/features/error-handling` and should not be changed to `/cloud-sdk/docs/js/v2/features/error-handling`. v3 will have the path `/cloud-sdk/docs/js/v3/features/error-handling`. Therefore, we should remove this line here and change back all paths which were changed by adding /v2/ (all redirects, navbar items)

When we finally want to make v3 the default, we just change the `lastVersion` to 'current' and add a `path` to v2 `path: 'v2'`

2022-11-22 08:23 UTC, fwilhe commented on docusaurus.config.js
> +            path: 'v2',
To explain what I did: I followed [option one outlined here](https://docusaurus.io/docs/versioning#configuring-versioning-behavior) because I wanted to use as much default behaviour of docusaurus as possible, and I think that this most closely resembles our situation.

2022-11-22 08:39 UTC, fwilhe commented on docusaurus.config.js
> +            path: 'v2',
Okay I think I got what you meant. I was under the impression that to do what you suggested we would have to tag a v3 now, but that's not the case. I've configured the v3 path for v3, reverted the changed links and v2 is now still available with the same links as before. Makes sense, thanks for the review.

2022-11-22 09:22 UTC, FrankEssenberger commented
Looks good overall with Deekshas suggestion all the links stay the same for v2 and work. I found one small thing. On main I still sse all the API references: 
![Screenshot 2022-11-22 at 10 20 23](https://user-images.githubusercontent.com/56544999/203275788-1cf4722a-a5e2-4157-99bb-bffaa37fe56c.png)
However on this branch I see only one:
![Screenshot 2022-11-22 at 10 21 07](https://user-images.githubusercontent.com/56544999/203275875-946af6ec-b10d-4b94-934a-8d335d4a66ef.png)
For v3 I do not see any references which is fine I think.

2022-11-22 10:44 UTC, fwilhe commented
@FrankEssenberger I think this is a unrelated change we discussed in a recent refinement. Not sure in which commit this was changed, but I'd be surprised if my PR caused that change. Also I think this is now the expected behaviour, so I don't know what to change.

notify @tomfrenken @marikaner @jjtang1985 

anyone diagrees?

2022-11-22 11:15 UTC, deekshas8 approved these changes
LGTM. I also do not see any difference in API Ref dropdown.
Main:
![image](https://user-images.githubusercontent.com/88374536/203300486-eca9c5b3-23b3-49c9-83ba-08cae296a9e6.png)

v3-docs branch:
![image](https://user-images.githubusercontent.com/88374536/203300526-29e75dc1-5b9b-4ca0-9d67-c6256911d6ad.png)

2022-11-22 11:48 UTC, merged