chore: Apply style guide (Part 3)
SAP/cloud-sdk pull request #1151
Opened 2022-11-29 10:21 UTC by florian-richter

## What Has Changed?

Apply some more style guide rules to our documentation.

2022-11-29 19:30 UTC, tomfrenken requested changes
Overall looks good, just some minor findings and a little discussion/comment regarding `ingress` vs `Ingress`, `service` vs `Service` etc.

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/features/odata/v4/expand-select.mdx
> +That's why the SAP Cloud SDK mimic this behavior for select and expand operations in its API for OData v4 type-safe client.
```suggestion
That's why the SAP Cloud SDK mimics this behavior for select and expand operations in its API for OData v4 type-safe clients.
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/features/openapi/overview.mdx
> +If you encounter any problems or errors with OpenAPI tooling giving feedback via the [support channels](/docs/overview/get-support).
```suggestion
If you encounter any problems or errors with the OpenAPI tooling feel free to give us feedback via our [support channels](/docs/overview/get-support).
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/features/openapi/overview.mdx
> +If you encounter any problems or errors with OpenAPI tooling giving feedback via the [support channels](/docs/overview/get-support).
I think this is a rare occasion where "our" is actually appropriate.

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/features/openapi/overview.mdx
> +- Less code boilerplate and better developer experience
```suggestion
- Less boilerplate code and better developer experience
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/features/openapi/overview.mdx
> +  - Automated `CSRF` and `ETag` tokens handling
```suggestion
  - Automated `CSRF` and `ETag` token handling
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/features/openapi/overview.mdx
> +  - Automated management of HTTP Headers
```suggestion
  - Automated management of HTTP headers
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/how-to-retrieve-jwt.mdx
> +This will give a high-level overview:
```suggestion
The following instructions will give a high-level overview:
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +This specifies:
```suggestion
The file specifies:
```

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Kubernetes pods are running container images.
No strong opinion here, but `Pod` is a specific concept from Kubernetes, which isn't referring to a normal pod.
At least in the K8s docs they capitalize it, see: https://kubernetes.io/docs/concepts/workloads/pods/

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +:::danger
Good idea!

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Notice how your ingress uses the SAP Gardener annotations, which is important so that SAP Gardener manages TLS.
Same capitalization issue, as `Ingress` doesn't refer to the normal noun, see:
https://kubernetes.io/docs/concepts/services-networking/ingress/

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +First the deployment:
Same here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

2022-11-29 19:30 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +And the service:
Same here: https://kubernetes.io/docs/concepts/services-networking/service/

2022-11-30 07:45 UTC, florian-richter commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Kubernetes pods are running container images.
I was not aware that Kubernetes capitalizes Pod, Service, Deployment, and Ingress. I like the lowercase spelling better (after all it is not a product but a component/part of K8s), but I am also okay with using caps.

@deekshas8 what is your opinion?

2022-11-30 09:22 UTC, florian-richter commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Kubernetes pods are running container images.
Wikipedia uses mostly lowercase words for pods and services. Deployment and ReplicaSet is sometimes with caps, but depending on context.

2022-11-30 09:40 UTC, tomfrenken commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Kubernetes pods are running container images.
Kubernetes-related literature (books/papers) I've read all used uppercase, however, some qualified them by saying stuff like "the Pod resource", "the Ingress controller", etc.

2022-11-30 09:49 UTC, deekshas8 commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Kubernetes pods are running container images.
This is a bit difficult to judge, since other docs (redhat, google, etc) don't have consistent behavior either. I would be fine with using Caps, just to stress that it's a specific concept in itself.

2022-11-30 09:51 UTC, florian-richter commented on docs-js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Kubernetes pods are running container images.
Alright 👍  I'll adjust to use caps again

2022-11-30 10:28 UTC, tomfrenken approved these changes
LGTM

2022-11-30 10:29 UTC, merged