Release Notes for 3.38.0
SAP/cloud-sdk pull request #116
Opened 2021-02-04 16:15 UTC by Emdee89

## What Has Changed?

Release Notes for SAP Cloud SDK for Java 3.38.0

## Manual Checks?

- [X] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [X] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [X] You formatted all changed files with prettier (`npm run prettier`)
- [X] You tested if the documentation still builds (`npm run build`)
- [] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [X] ~You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~

Open: The Javadoc links is missing still

2021-02-05 18:11 UTC, artemkovalyov requested changes
Great release notes!
I suggest we have to update docs with code-snippets we have here if hasn't been done yet.
They must be discoverable by new users who'd skip the old release notes when starting with some SDK features.

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  For certain authentication types i,e. `NoAuthentication` and `OAuth2ClientCredentials` this API eliminates the need to manually create a destination in the CF account for connecting to services.
```suggestion
- We now support the `SAMLAssertion` authentication type on Cloud Foundry.
  Refer to the [help page](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/d81e1683bd434823abf3ceefc4ff157f.html) for more detail on the `SAMLAssertion` authentication type.
- We introduced a new API to build a `Destination` for connecting to services on Cloud Foundry.
  The information will be read from the `VCAP_SERVICES` environment variable at runtime.
  For certain authentication types i.e. `NoAuthentication` and `OAuth2ClientCredentials` this API eliminates the need to manually create a destination in the CF account for connecting to services.
```

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  ```
Do we also have these examples in the documentation for destinations?

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +          "my-workflow");
Let's add this to the Workflow docs.

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Add support for recursive tables and structures in parameters of `BapiRequest` API for both protocols: _JCo_ and _SOAP_. Example:
```suggestion
- We introduced a new API to construct a `ScpCfDestinationLoader` that allows overriding the default timeout for the Time Limiter resilience pattern.
  If not specified, requests will automatically timeout after 6 seconds.

- We added support for recursive tables and structures in parameters of `BapiRequest` API for both protocols: _JCo_ and _SOAP_. Example:
```

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  ```
Another reason for a quick example on the BAPI/RFC docs if not yet there.

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue with JCo serialization of BAPI requests where adding field parameter values of type `ErpType` led to an exception.
```suggestion
- We fixed an issue with OData V4 update requests where the serialization of primitives with types like Integer, Boolean, and Double leads to null values.
- We fixed an issue with JCo serialization of BAPI requests, where adding field parameter values of type `ErpType` led to an exception.
```

2021-02-05 18:11 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +[Maven Central](https://search.maven.org/search?q=g:com.sap.cloud.sdk*%20AND%20v:3.38.0) | [Javadoc](still-missing)
The broken JavaDoc link will fail the pipeline. If it's not available before merge - we can use the link from the last release we have it for.

2021-02-05 18:17 UTC, newtork commented on docs/java/release-notes.mdx
> +
```suggestion
- As part of the update of the OData VDM to SAP S/4HANA Cloud 2102 a few operations were removed. The operations were never supported by the S/4 system (like CRUD support for some entities), so no existing functionality is affected. The following services are affected:
  - _Nota Fiscal – Create, Update_ - `API_LOGBR_NOTAFISCAL_SRV`
  - _Purchase Contracts_ - `API_PURCHASECONTRACT_PROCESS_SRV`
  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
  
```

2021-02-05 18:18 UTC, newtork commented on docs/java/release-notes.mdx
> +
```suggestion
- Update the OData VDM to the [newest release 2102 of SAP S/4HANA Cloud](https://news.sap.com/2021/02/sap-s4hana-cloud-2102-empowering-businesses-seize-opportunities/). This includes completely new services (available as usual in packages `com.sap.cloud.sdk.s4hana.datamodel.odata.services` and `com.sap.cloud.sdk.s4hana.datamodel.odatav4.services`), new operations in previously existing services, and new entity types. The SDK supports all OData services listed in the [SAP API Business Hub for SAP S/4HANA Cloud](https://api.sap.com/shell/discover/contentpackage/SAPS4HANACloud) with the exception of the following services:
  - (OData V2) _Purchase Requisition_ - `API_PURCHASEREQ_PROCESS_SRV`
  - (OData V2) _Production Order Confirmation_ - `API_PROD_ORDER_CONFIRMATION_2_SRV`
  - (OData V2) _Process Order Confirmation_ - `API_PROC_ORDER_CONFIRMATION_2_SRV`
  - (OData V2) _Attachments_ - `API_CV_ATTACHMENT_SRV`
  - (OData V4) _Contract Accounting: Invoices of Business Partner_ - `API_CABUSPARTINVOICE_0001`
  
```

2021-02-08 09:11 UTC, Emdee89 commented on docs/java/release-notes.mdx
> +[Maven Central](https://search.maven.org/search?q=g:com.sap.cloud.sdk*%20AND%20v:3.38.0) | [Javadoc](still-missing)
I removed it intentionally to avoid forgetting to update the link

2021-02-08 09:15 UTC, Emdee89 commented on docs/java/release-notes.mdx
> +  ```
We lack even simpler examples in the BAPI docu, so it's difficult to start there now with such a complex example.
I'll create a backlog item to extend the docu in that realm overall where this example can be covered.

2021-02-08 09:16 UTC, Emdee89 commented on docs/java/release-notes.mdx
> +          "my-workflow");
It's already there: https://sap.github.io/cloud-sdk/docs/java/features/rest/clients/scp-workflow-rest-api#invoke-the-java-client-library

2021-02-11 11:01 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +[Maven Central](https://search.maven.org/search?q=g:com.sap.cloud.sdk*%20AND%20v:3.38.0) | [Javadoc](still-missing)
```suggestion
[Maven Central](https://search.maven.org/search?q=g:com.sap.cloud.sdk*%20AND%20v:3.38.0) | [Javadoc](https://help.sap.com/doc/cfa38ab94e4f481298556d6fdaf3672b/1.0/en-US/index.html)
```

2021-02-11 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/cloud-sdk?pullRequest=116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/cloud-sdk?pullRequest=116) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Emdee89<br/>:x: Johannes-Schneider<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/cloud-sdk?pullRequest=116) it.</sub>

2021-02-11 14:50 UTC, newtork commented on docs/java/release-notes.mdx
> +  Please use `ResilienceDecorator::clearCache` for tenant aware cache invalidation or `ResilienceDecorator::clearAllCacheEntries` to clear all entries for all tenants and principals.
I'm not sure whether this is good or bad, but i the past we used `#` as type-method delimiter.

```suggestion
- The method `ResilienceDecorator#invalidateCache` is deprecated but still functional.
  Please use `ResilienceDecorator#clearCache` for tenant aware cache invalidation or `ResilienceDecorator#clearAllCacheEntries` to clear all entries for all tenants and principals.
```

2021-02-11 22:07 UTC, artemkovalyov approved these changes
It's good to go. Consider fixing the small issue I have found.

2021-02-11 22:07 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Update the OData VDM to the [newest release 2102 of SAP S/4HANA Cloud](https://news.sap.com/2021/02/sap-s4hana-cloud-2102-empowering-businesses-seize-opportunities/). This includes completely new s
```suggestion
- We updated the [OData type-safe client also known as a VDM](java/features/odata/overview.mdx) to the [newest release 2102 of SAP S/4HANA Cloud](https://news.sap.com/2021/02/sap-s4hana-cloud-2102-empowering-businesses-seize-opportunities/). This includes completely new services (available as usual in packages `com.sap.cloud.sdk.s4hana.datamodel.odata.services` and `com.sap.cloud.sdk.s4hana.datamodel.odatav4.services`), new operations in previously existing services, and new entity types. The SDK supports all OData services listed in the [SAP API Business Hub for SAP S/4HANA Cloud](https://api.sap.com/shell/discover/contentpackage/SAPS4HANACloud) with the exception of the following services:
```

2021-02-11 22:07 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- We fixed an issue with JCo serialization of BAPI requests, where adding field parameter values of type `ErpType` led to an exception.
```suggestion
- We fixed an issue with OData V4 update requests where the serialization of primitives with types like Integer, Boolean, and Double leads to null values.
- We fixed an issue with the JCo serialization of BAPI requests, where adding field parameter values of type `ErpType` led to an exception.
```

2021-02-12 12:09 UTC, merged