[JS] Update Resilience Documentation
SAP/cloud-sdk pull request #1180
Opened 2022-12-20 15:29 UTC by FrankEssenberger

Relates [#669](https://github.com/SAP/cloud-sdk-backlog/issues/669)

Adjusts the old resilience document to feature the new default implementation.

2022-12-22 14:44 UTC, tomfrenken requested changes
Content-wise it looks good, just a few grammar / wording remarks

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +To use the `resilience()` function is the recommended way to build the resilience related middleware.
```suggestion
Using the `resilience()` function is the recommended way to build resilience-related middleware, it ensures the correct order of middlewares.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +Using this method ensure the correct order of middlewares.
```suggestion

```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +The timeout middleware is very simple and based on `Promise.race()`.
```suggestion
The timeout middleware is very simple and based on the `Promise.race()` method, therefore no additional library is used.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +So no additional library is used.
```suggestion

```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +Per default a timeout of 10 seconds is used, but you can set values to change the value:
```suggestion
Per default, a timeout of 10 seconds is used, but you can change the values on demand:
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +- The circuit breaker records all request for a duration of 10 seconds.
```suggestion
- The circuit breaker records all requests for a duration of 10 seconds.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +- After a reset time of 30 seconds the circuit breaker will go to the state half open.
```suggestion
- After a reset time of 30 seconds the circuit breaker will go to the half-open state.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +This state is stored in central circuit breaker instates.
```suggestion
This state is stored in central circuit breaker instances.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +This means the maximum waiting time between the three retries are 2, 4 and 8 seconds.
```suggestion
This means the maximum waiting times between the three retries are 2, 4, and 8 seconds.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +Note that the concept of resilience is not trivial, and you should develop and test your implementation carefully:
```suggestion
Note that the concept of resilience is not trivial, and you should develop and test your implementation thoroughly:
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +- You should keep in mind the order of your middlewares.
```suggestion
- You should keep the order of your middlewares in mind.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +  A retry should be in the end and a timeout or cache implementation in the very beginning.
```suggestion
  A retry should be at the end and a timeout or cache implementation at the very beginning.
```

2022-12-22 14:44 UTC, tomfrenken commented on docs-js/guides/how-to-add-resilience.mdx
> +- If your middleware adds shared state between requests e.g. circuit breaker you must consider isolation between customers in a multi tenant situation.
```suggestion
- If your middleware adds shared state between requests, e.g. a circuit breaker, you must consider isolation between customers in a multi-tenant situation.
```

2022-12-23 11:24 UTC, tomfrenken approved these changes
LGTM

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- Rolling count timeout: 10 seconds.
[req] A period is not needed at the end of each point

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- If in this time window 10 or more requests are recorded the error threshold is calculated.
```suggestion
- If in this time window, 10 or more requests are recorded, the error threshold is calculated.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- If 50% or more of the requests in the time window fail, the circuit breaker opens.
```suggestion
- If 50% or more of the requests in this time window fail, the circuit breaker opens.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +  From this point in time all requests to the target system are blocked directly and not executed anymore.
```suggestion
  From this point in time, all requests to the target system are blocked directly and not executed anymore.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- After a reset time of 30 seconds the circuit breaker will go to the half-open state.
```suggestion
- After a reset time of 30 seconds, the circuit breaker will go to the half-open state.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +Note that requests with `HTTP` status 4XX do not count as failed, because they do not indicate an unhealthy system.
[req] [Use code font](https://github.com/SAP/cloud-sdk/blob/main/STYLEGUIDE.md#use-code-font)

Also, maybe a note admonition?

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +The SAP Cloud SDK offers a retry middleware based on the [async-retry](https://www.npmjs.com/package/async-retry) library.
[pp] I would skip the 1 line. Also not iterate that SDK offers retry middleware.

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +You create a retry middleware using the `retry()` function which will add three retries per default.
```suggestion
You can create a retry middleware using the `retry()` function, which adds 3 retries by default.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- Exponential grow for waiting time using a base of 2.
```suggestion
- Exponential growth for waiting time using a base of 2.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +One central idea to include resilience using a middleware concept is that you can implement your own logic in case the provided one does not fit your needs.
```suggestion
One central idea to include resilience using a middleware concept is that you can implement your logic in case the provided one does not fit your needs.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- You should keep the order of your middlewares in mind.
```suggestion
- You should keep the order of middlewares in mind.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +  For example a 401 or 403 response will not magically work if you do a retry.
```suggestion
  For example, a `401` or `403` response will not magically work if you do a retry.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- If your middleware adds shared state between requests, e.g. a circuit breaker, you must consider isolation between customers in a multi-tenant situation.
```suggestion
- If the middleware adds shared state between requests, e.g. a circuit breaker, you must consider isolation between customers in a multi-tenant situation.
```

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +- Align the parameters of your middlewares if necessary.
```suggestion
- Align the parameters of the middlewares if necessary.
```

avoid your

2022-12-23 11:25 UTC, deekshas8 commented on docs-js/guides/how-to-add-resilience.mdx
> +  Assume your system needs protection from a circuit breaker, and you want to use a retry to execute the request after system recovery.
```suggestion
  Assume the system needs protection from a circuit breaker, and you want to use a retry to execute the request after system recovery.
```

2022-12-23 13:35 UTC, merged