[JS] Update Middleware Docs
SAP/cloud-sdk pull request #1234
Opened 2023-01-26 14:58 UTC by FrankEssenberger

## What Has Changed?

Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/1042

Extends the middleware documentation.

2023-01-27 09:03 UTC, florian-richter requested changes
I have to stop my review due to a meeting conflict now but there is already a lot of feedback. Please make sure to follow the style guide!

2023-01-27 09:03 UTC, florian-richter commented on docs-js/features/middleware.mdx
> +For a list of default resilience middlewares, a timeout should be added first, then a circuit breaker followed by a retry.
```suggestion
The provided default resilience middlewares should be added in the following order:
1. timeout
2. circuit breaker
3. retry.
```
[req] We should introduce our provided middlewares first
[req] Make it easier to understand the order.

2023-01-30 07:40 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +  };
Async await is not possible because then it would return a Promise<MiddlewareFunction>

2023-01-30 11:52 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +Also here the middleware does **not** execute the function but adds functionality.
No it does not it returns a function which will execute it but it does not call it.

2023-01-30 13:09 UTC, FrankEssenberger commented
I add the dark picture once all comments are in

2023-01-30 14:08 UTC, marikaner requested changes

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +## Example Hello World
[req] Now after I looked through the examples a bit, I would like to suggest to actually structure the article such that the examples are there to explain a topic more visually, but the topic itself is more in the center of it.

"Example Multiple Middlewares" basically explains the order of execution when there are multiple middlewares.
I think it would be more natural to have a section on "Order of Execution" (or so) and within this section use the example to better explain the topic.

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +The timout would apply to the time for the original request plus additional time for a potential fallback call (see _g<sub>1</sub>_ and _g<sub>2</sub>_ in the picture above).
```suggestion
The timeout would apply to the time for the original request plus additional time for a potential fallback call (see _g<sub>1</sub>_ and _g<sub>2</sub>_ in the picture above).
```

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +export interface HttpMiddlewareContext {
[pp] As above a high level JS Doc, e.g. "Represents the Execution Context of a Middleware" or something, would help introduce this interface a bit.

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +The fallback middleware could consider the uri:
```suggestion
The fallback middleware could consider the URI:
```

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +The SAP Cloud SDK uses the axios client which has a `timeout` property.
[q] Should it be axios or Axios?

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +export interface HttpMiddlewareContext {
[q] Why is this called `HttpMiddlewareContext` - are there other contexts as well?

2023-01-30 14:08 UTC, marikaner commented on docs-js/features/middleware.mdx
> +Assume you want to replace the HTTP client of the SAP Cloud SDK uses with a different one.
[req] something is wrong in this sentence.

2023-01-30 15:27 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +The second middleware adds a fallback to this new function leading _h<sub>2</sub>_ in the picture below.
I added a picture to the text

2023-01-30 15:28 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +The fallback was added last, so it will execute first.
The problem is it depends if it is a stack or queue on how you implement it.

2023-01-30 15:30 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +export interface HttpMiddlewareContext {
yes this is the concrete Http case wher ethe middleware function is also HttpRequest->HttpResponse

2023-01-30 15:46 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +The SAP Cloud SDK uses the axios client which has a `timeout` property.
most of the time it is used like this

2023-01-30 15:49 UTC, FrankEssenberger commented on docs-js/features/middleware.mdx
> +The SAP Cloud SDK uses the axios client which has a `timeout` property.
it is also in line with the style guide: https://github.com/SAP/cloud-sdk/blob/main/STYLEGUIDE.md#use-ordinary-font-for-software-products

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> + * Type defining the function passed from one middleware to the next one.
[pp] This is very much from the implementation point of view. If I put myself into the shoes of a user maybe the "passing" is not something I have on my radar. This is the function that middlewares return (and we internally pass it as `fn()` to the next one).

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +export type Middleware = (options: MiddlewareOptions) => MiddlewareFunction;
[pp] I'd put this first.

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +  For the last one it is the original HTTP request from the SAP Cloud SDK.
[req] Those two sentences are ambiguous, because in the first we use "previous" in a sense of order of execution. In the second we use "last one" in the order as it appears in the array (aka. "first one" in the order of execution).

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +  Note that the type of the input and return function are the same.
[req/q] Is that true? The "input" is of type `MiddlewareOptions` the return(ed?) function is of type `MiddlewareFunction`. I don't really understand what is meant by this...

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
>  - The `skipNext` will exit all following middlewares
[req] Styleguide

```suggestion
- `skipNext()` will exit all following middlewares
```

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +In this section you learn how to implement a middleware based on a didactic example.
[pp] It's fine, but I just don't like these kinds of introductions ;) 
```suggestion
```

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +const doSomethingBeforeMiddleware = options => {
[pp] General remark: Instead of `options` I would destructure the options to have the `fn` at hand. Reads better in my opinion.

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +If you want to process the result of the function your middleware implement it the following way
[req] Something is missing in this sentence.

2023-02-02 08:29 UTC, marikaner commented on docs-js/features/middleware.mdx
> +    });
[req] Shouldn't we use `await` as we would do according to the style guide (I think)?

2023-02-08 12:47 UTC, marikaner approved these changes
Looks good, the rest will be done in a follow up

2023-02-08 14:27 UTC, merged