Suggest to add the import location for the filter functions
SAP/cloud-sdk pull request #1275
Opened 2023-02-18 14:21 UTC by carlonnheim

## What Has Changed?

It is not obvious for first-time consumers of this help page where the `and`, `or` etc. are to be imported from.

2023-02-20 12:19 UTC, marikaner requested changes
Once you sign the CLA we're good to go.

2023-02-20 12:19 UTC, marikaner commented on docs-js_versioned_docs/version-v2/features/odata/common/query-parameter/filter.mdx
> +const { or, and } = require('@sap-cloud-sdk/core');
The core package only existed in version 1, for version 2 it should be loaded from the correct odata package (either odata-v2 or odata-v4). In this case it would be odata-v2. [=> docs](https://sap.github.io/cloud-sdk/api/v2/modules/sap_cloud_sdk_odata_v2.html#or)
```suggestion
const { or, and } = require('@sap-cloud-sdk/odata-v2');

```

2023-02-20 12:20 UTC, marikaner approved these changes

2023-03-17 13:45 UTC, marikaner commented
@carlonnheim I am not allowed to merge your request as long as the CLA is not signed.

2023-03-17 13:56 UTC, carlonnheim commented
> @carlonnheim I am not allowed to merge your request as long as the CLA is not signed.

Sorry, missed your earlier message on this. I have done that now. Thanks!

2023-04-04 08:25 UTC, merged