Update release-notes.mdx
SAP/cloud-sdk pull request #133
Opened 2021-02-19 17:13 UTC by marikaner

Update release notes for VDM releases

2021-02-19 17:34 UTC, jjtang1985 requested changes

2021-02-19 17:34 UTC, jjtang1985 commented on docs/js/release-notes.mdx
> +  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
The package `@sap/cloud-sdk-vdm-purchasing-inforecord-service` was renamed to `@sap/cloud-sdk-vdm-purchasing-info-record-service`.
Perhaps we can also mention it.

2021-02-19 17:34 UTC, jjtang1985 commented on docs/js/release-notes.mdx
> +
Have we received the doc link from Tobias, which should be added here.

2021-02-19 17:51 UTC, marikaner commented on docs/js/release-notes.mdx
> +
```suggestion
```

2021-02-19 17:51 UTC, marikaner commented on docs/js/release-notes.mdx
> +
```suggestion

- [API documentation] (https://help.sap.com/doc/38ea0a832f064060a834a2d328038ceb/1.0/en-US/index.html)

```

2021-02-19 17:52 UTC, marikaner commented on docs/js/release-notes.mdx
> +
Good point.

2021-02-19 17:52 UTC, marikaner commented on docs/js/release-notes.mdx
> +  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
I thought of this and then forgot. Whoopsie.

2021-02-19 17:53 UTC, marikaner commented on docs/js/release-notes.mdx
> +  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
```suggestion
  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
- The service `@sap/cloud-sdk-vdm-purchasing-inforecord-service` was renamed to `@sap/cloud-sdk-vdm-purchasing-info-record-service`.
```

2021-02-22 09:01 UTC, jjtang1985 approved these changes
LGTM

2021-02-24 00:42 UTC, artemkovalyov commented on docs/js/release-notes.mdx
> +  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
```suggestion
<!-- vale off -->
  - _Nota Fiscal – Create, Update_ - `API_LOGBR_NOTAFISCAL_SRV`
  - _Purchase Contracts_ - `API_PURCHASECONTRACT_PROCESS_SRV`
  - _Outbound Delivery (A2X)_ - `API_OUTBOUND_DELIVERY_SRV_0002`
  <!-- vale on -->
```

2021-02-24 00:46 UTC, merged

2021-02-24 00:47 UTC, artemkovalyov commented
I fixed the build and merging this! Thanks for taking care of the release noted, @marikaner !