docs: Add entity docs
SAP/cloud-sdk pull request #137
Opened 2021-02-22 15:42 UTC by marikaner

## What Has Changed?

This is a general documentation on entities and how to build them.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-02-22 19:47 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData the JSON representation of a single business parter could be something like this:
```suggestion
In OData the JSON representation of a single business partner could be something like this:
```

2021-02-23 13:31 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData entity collections are the resource against which you execute requests and CRUD operations.
To get a better reading flow a comma would help me: In OData, entity collections are the...

2021-02-23 13:36 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData the JSON representation of a single business partner could be something like this:
I would get rid of the `In OData` here because also for REST apis the send or received data is represented in JSON. So perhaps something like: While receiving or sending data, it may be represented by JSON. An example for such a payload in the business partner case may look like:

2021-02-23 13:38 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity.mdx
> +BusinessPartner {
I think there is an assignment missing at least if it is supossed to be TypeScript.

2021-02-23 13:38 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData the JSON representation of a single business partner could be something like this:
This sending data goes also nice with the next sentences below.

2021-02-23 13:39 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity.mdx
> +OData responses, that contain entities are automatically transformed to the respective entity class when using the SAP Cloud SDK.
perhaps use instead of `transform` the term desirialse/serialize we also use in our code.

2021-02-23 13:40 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity.mdx
> +To execute create or update requests you have to build an instance of an entity class, that represents the data to be created or updated.
This sounds a bit like: https://xkcd.com/703/.

2021-02-23 13:59 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/entity-builder.mdx
> +Use the static `.builder()` function to access the builder, set the properties and finally use the `.build` function to yield the entity.
```suggestion
Use the static `.builder()` function to access the builder, set the properties and finally use the `.build()` function to yield the entity.
```

2021-02-23 14:04 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/from-json.mdx
> +This would be the JSON representation for the data above:
I think this section comes after the introduction and entity-builder section so I wonder if it is clear which `data above` you are referring to.

2021-02-23 14:08 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/from-json.mdx
> +You can use this data to build an entity using the `.fromJson` function.
consistency: in some cases you made the () for a function in some you do not. Just make it consistent.

2021-02-23 14:10 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/from-json.mdx
> +The example below shows how you would create the data from above based on a JSON representation.
```suggestion
The example below shows how you would create an instance of the business partner class using the `fromJson` function.
```

2021-02-23 14:11 UTC, FrankEssenberger requested changes
Just minor comments and spell checking is not my strong suit. The only reason I set it to request changes is that I would like to have some content on the `custom fields` and how you would set them using the builder or fromJson.

2021-02-24 00:12 UTC, artemkovalyov requested changes
I found some reading simplifications, let's see if they make sense, otherwise, it's LGTM

2021-02-24 00:12 UTC, artemkovalyov commented on docs/js/features/odata/common/entity/entity-builder.mdx
> +The relation to the business partner address is a one to many relation here.
```suggestion
To set navigation properties, that link to other entities, you have to create the linked entities using their respective builder.
Navigation properties, that are linked through a one-to-many relation have to be assigned in an array - one-to-one relations are assigned as single objects.
The example below shows how you would create the data from above using the entity builder.
The relation to the business partner address is a one-to-many relation here.
```

2021-02-24 10:29 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData entity collections are the resource against which you execute requests and CRUD operations.
```suggestion
In OData, entity collections are the resource against which you execute requests and CRUD operations.
```

2021-02-24 11:26 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData the JSON representation of a single business partner could be something like this:
```suggestion
An OData JSON representation of a single business partner could be something like this:
```

2021-02-24 11:26 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +In OData the JSON representation of a single business partner could be something like this:
This isn't really the gist of what I was trying to say. I wanted to make clear that we are talking about the JSON representation of OData and not our JSON representation. I tried to improve it, let me know if this is better in your opinion.

2021-02-24 11:29 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +BusinessPartner {
I wasn't sure how to show this - this is supposed to be the representation of an instance of the `BusinessPartner` class. (This is the output of `console.log(bupa)`), where `bupa` is an instance of `BusinessPartner`.
I don't want to show the entity builder just yet, only the instance... do you have a better idea?

2021-02-24 11:29 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +OData responses, that contain entities are automatically transformed to the respective entity class when using the SAP Cloud SDK.
```suggestion
OData responses, that contain entities are automatically deserialized to the respective entity class when using the SAP Cloud SDK.
```

2021-02-24 11:33 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +To execute create or update requests you have to build an instance of an entity class, that represents the data to be created or updated.
I thought so too, when writing it ;) But then I also decided, that this is correct, because "executing a create request" requires a representation of the "data to be created". Do you have an idea how to express that better?

2021-02-24 11:34 UTC, marikaner commented on docs/js/features/odata/common/entity/from-json.mdx
> +You can use this data to build an entity using the `.fromJson` function.
I will remove the `()` so that I don't have to deal with params.

2021-02-24 11:34 UTC, marikaner commented on docs/js/features/odata/common/entity/from-json.mdx
> +You can use this data to build an entity using the `.fromJson` function.
I will remove the `()` so that I don't have to deal with params.

2021-02-24 11:37 UTC, marikaner commented on docs/js/features/odata/common/entity/from-json.mdx
> +This would be the JSON representation for the data above:
```suggestion
This would be the JSON representation of a business parter in the SAP Cloud SDK:
```

2021-02-25 00:12 UTC, artemkovalyov reviewed
It's Ok with me. Let @FrankEssenberger  sign off this PR as he had major questions about the semantics.

2021-02-25 08:09 UTC, marikaner commented on docs/js/features/odata/common/entity/entity.mdx
> +OData responses, that contain entities are automatically transformed to the respective entity class when using the SAP Cloud SDK.
done

2021-02-25 08:09 UTC, marikaner commented on docs/js/features/odata/common/entity/from-json.mdx
> +This would be the JSON representation for the data above:
done

2021-02-25 08:09 UTC, marikaner commented on docs/js/features/odata/common/entity/from-json.mdx
> +You can use this data to build an entity using the `.fromJson` function.
done

2021-02-25 08:13 UTC, marikaner commented
> Just minor comments and spell checking is not my strong suit. The only reason I set it to request changes is that I would like to have some content on the `custom fields` and how you would set them using the builder or fromJson.

I added Custom Fields, please take a look.

2021-02-25 09:11 UTC, FrankEssenberger commented on docs/js/features/odata/common/entity/custom-fields.mdx
> +
Can you add sentence that on the `fromJson` construction you can simply set the fields by their name and there is no difference to the other fields.

2021-02-25 09:11 UTC, FrankEssenberger approved these changes
Consider my comment regarding the custom fields in the `fromJson` context and go ahead and merge.

2021-02-25 14:12 UTC, artemkovalyov approved these changes
Thanks, LGTM

2021-02-25 14:12 UTC, merged