Extend destinations docu with localhost setup
SAP/cloud-sdk pull request #14
Opened 2020-11-11 14:34 UTC by Emdee89

Extend destinations docu with localhost setup

2020-11-11 14:53 UTC, newtork commented on docs/java/features/connectivity/destinations.mdx
> +            ...
Question: JSON elements in `default-env.json` > `VCAP_SERVICES` > `destination` have a different format than elements in local environment variable `destinations`, right? They are not interchangeable, correct?

2020-11-11 15:18 UTC, sacnl commented on docs/java/features/connectivity/destinations.mdx
> +#### Destinations with Proxy Type "OnPremise"
This step would only be needed if there is no direct local connection to the system that shall be accessed via the on-premise destination. If I am in the same network and can use basic auth, I do not need to go via connectivity service etc for my local tests but can use the simple destination environment variable.
Maybe add that as a quick hint.

2020-11-12 11:12 UTC, Emdee89 commented on docs/java/features/connectivity/destinations.mdx
> +            ...
Correct. I'll enhance the example to illustrate that more clearly and to avoid such confusion.

2020-11-12 11:23 UTC, Emdee89 commented on docs/java/features/connectivity/destinations.mdx
> +#### Destinations with Proxy Type "OnPremise"
Right, will add a hint about this.

2020-11-12 20:08 UTC, artemkovalyov requested changes
Minor grammar/style for clarity.

2020-11-12 20:08 UTC, artemkovalyov commented on docs/java/features/connectivity/destinations.mdx
> +:::
```suggestion
:::note Are your client and server located on the same Network?
If your localhost (client) resides in the same network zone as the target system (server) you can access it directly. Configuration of SCP connectivity services is not needed. All you have to do is creating a destination via environment variable `destinations`.
:::
```

2020-11-13 08:33 UTC, artemkovalyov approved these changes
LGTM

2020-11-13 08:33 UTC, merged