Deprecated NEO
SAP/cloud-sdk pull request #1405
Opened 2023-06-15 15:25 UTC by CharlesDuboisSAP

## ⚠️ WAIT FOR VERSION `4.17.0` TO BE PUBLICLY AVAILABLE ⚠️

## What Has Changed?

See [Deprecated NEO #8180](https://github.wdf.sap.corp/MA/sdk/pull/8180#top)

## Manual Checks?

- [x] Check spelling and grammar, e.g., using Grammarly.
- [x] Verify links still work, e.g., if `id` or the name of a file is changed.
- [x] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a feature is added.

2023-06-16 07:26 UTC, Johannes-Schneider requested changes

2023-06-16 07:26 UTC, Johannes-Schneider commented on docs-java/faq.mdx
> +We are planning to discontinue support of NEO with SAP Cloud SDK v5 by end of the year.
Who knows when somebody is going to stumble over this sentence ... 😉

```suggestion
We are planning to discontinue support of NEO with SAP Cloud SDK v5 by end of 2023.
```

2023-06-16 07:26 UTC, Johannes-Schneider commented on docs-java/faq.mdx
> +We are planning to discontinue support of NEO with SAP Cloud SDK v5 by end of the year.
Also, to make this stick out even more, why not wrap it inside a `:::warn` box and leave the rest of this paragraph untouched.

2023-06-16 07:26 UTC, Johannes-Schneider commented on docs-java/faq.mdx
> +Therefore, we're announcing module deprecation in advance.
Personally, I don't think this sentence belongs here.

```suggestion
```

2023-06-16 07:26 UTC, Johannes-Schneider commented on src/components/data/features.js
> +      note: 'Deprecated since 4.17'
(minor)

```suggestion
      note: 'Deprecated since 4.17.0'
```

2023-06-16 07:50 UTC, Johannes-Schneider commented on docs-java/faq.mdx
> +We still provide full support for SAP Business Technology Platform Neo.
Let's add this back in:

```suggestion
:::

We still provide full support for SAP Business Technology Platform Neo.
However, we do not recommend starting new projects with SAP BTP for the Neo environment.
```

2023-06-16 07:58 UTC, Johannes-Schneider commented on docs-java/faq.mdx
> -The Cloud Foundry environment is better suited for apps and SAP S/4HANA extension development.
Why are we keep removing sentences? 😅
Just add the box on top of this and we are good IMO.

2023-06-16 08:51 UTC, Johannes-Schneider approved these changes

2023-06-22 12:50 UTC, jjtang1985 commented on docs-java/faq.mdx
> +We are planning to discontinue support of NEO with SAP Cloud SDK v5 by end of 2023.
```suggestion
All the NEO specific classes and functions have been deprecated.
We are planning to discontinue support of NEO with SAP Cloud SDK v5 by end of 2023.
```

2023-07-05 11:24 UTC, merged