Remove indicators to deprecated OData VDM based modules
SAP/cloud-sdk pull request #1412
Opened 2023-06-22 09:51 UTC by newtork

## What Has Changed?

* OData VDM based modules have been deprecated with 4.17.0
* Mentioning it on the documentation portal is no longer recommended.

## Manual Checks?

- [x] Check spelling and grammar, e.g., using Grammarly.
- [x] Verify links still work, e.g., if `id` or the name of a file is changed.
- [x] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a feature is added.

2023-06-27 13:57 UTC, CharlesDuboisSAP requested changes
The dependencies are still mentioned in [getting started](https://sap.github.io/cloud-sdk/docs/java/getting-started#adding-dependencies) for both s4hana-all and the on-premise dependencies

2023-06-29 12:12 UTC, newtork commented
> The dependencies are still mentioned in [getting started](https://sap.github.io/cloud-sdk/docs/java/getting-started#adding-dependencies) for both s4hana-all and the on-premise dependencies

Thanks for the hint. I checked for further occurrence of "s4hana-api-odata" and couldn't find any.

2023-06-29 12:23 UTC, CharlesDuboisSAP approved these changes

2023-07-05 11:48 UTC, CharlesDuboisSAP approved these changes

2023-07-05 11:53 UTC, merged