chore: Update k8s guide
SAP/cloud-sdk pull request #1439
Opened 2023-07-17 09:46 UTC by deekshas8

## What Has Changed?

Restructure and update the JS K8s guide. Moved the guide under an `Environments` section (same as JAVA)

2023-07-24 12:59 UTC, marikaner reviewed
I just looked over the k8s guide. I think in some places the text could be even a bit more structured, so that it is more broken down into smaller digestable pieces.

2023-07-24 13:20 UTC, marikaner requested changes
Kyma is much shorter, I like ;)

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +[Kyma](https://kyma-project.io/docs/kyma/latest/01-overview/) is an open-source project, offering a comprehensive suite of tools and services, specifically created for the development and operation o
[q] Do we say "Open Source" or "open source" in other places in the docs? We should align on how this should be written.

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +[Kyma](https://kyma-project.io/docs/kyma/latest/01-overview/) is an open-source project, offering a comprehensive suite of tools and services, specifically created for the development and operation o
[req] more active!
```suggestion
[Kyma](https://kyma-project.io/docs/kyma/latest/01-overview/) is an open-source project, that offers a comprehensive suite of tools and services, specifically created for the development and operation of cloud-native applications seamlessly integrated with Kubernetes.
```

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +This guide is meant for helping you migrate your existing application built with the SAP Cloud SDK for JavaScript to Kyma.
```suggestion
This guide is helps you to migrate your existing application built with the SAP Cloud SDK for JavaScript to Kyma.
```

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +- [`docker`](https://docs.docker.com/get-docker/) and a publicly reachable Docker repository
[pp] Same is in the k8s guide, I would prefer to have something actionable here, like, "install xy", "have access to z", etc. This also applies to all other items in this list.

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +  This guide assumes you have [Docker](https://www.docker.com/) installed on your local machine and a publicly accessible **Docker repository** where you can store images.
[pp] This seems to be the exact same information as in the sentence before ;) I would prefer to keep just one of those.

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +Finally, package and deploy all your resources together using the Helm Charts created above.
[req] We were talking about "Helm charts" before and after a quick Google search I think it should be lowercase.
```suggestion
Finally, package and deploy all your resources together using the Helm charts created above.
```

2023-07-24 13:20 UTC, marikaner commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +You can view the created resources (application, api rule, etc) by navigating to the Kyma Dashboard, using the **Link to dashboard** link in the subaccount.
```suggestion
You can view the created resources (application, api rule, etc) by navigating to the Kyma dashboard, using the **Link to dashboard** link in the subaccount.
```

2023-07-25 08:32 UTC, deekshas8 commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kyma.mdx
> +[Kyma](https://kyma-project.io/docs/kyma/latest/01-overview/) is an open-source project, offering a comprehensive suite of tools and services, specifically created for the development and operation o
We seem to use both ! I would prefer the simple "open source" (unless the term appears in the headings)

2023-07-25 09:52 UTC, deekshas8 commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +In SAP Gardener you can already specify your desired domain and the TLS will be managed for you, more on that later.
Removed this line since its explained in the section itself, and there is nothing really to link.

2023-07-25 10:28 UTC, deekshas8 commented on docs-js/environments/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +```
Restructured the description a bit. Let me know if it reads better

2023-07-27 15:31 UTC, marikaner approved these changes

2023-08-15 15:29 UTC, tomfrenken approved these changes
LGTM, I've created a follow-up ticket to update the on-premise section once the connectivity and transparent proxy have resolved their issues.

2023-08-15 15:29 UTC, merged