[Java] Update v5 migration guide
SAP/cloud-sdk pull request #1442
Opened 2023-07-20 08:58 UTC by KavithaSiva

## What Has Changed?

Documenting the removed modules and API in v5.

**If you are working on the Java v4 docs, remember to also apply the changes to v5**

2023-07-24 12:53 UTC, CharlesDuboisSAP requested changes
`ErpHttpDestination` is still mentioned in 2 different pages

2023-07-24 12:53 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
> +## List of modules that have been removed with version 5
- The list of modules removed with version 5 is incomplete:
  - `btp-shared-ledger-client`
  - `concurrency-scp-neo`
  - business logging modules
  - MDI mudles
  - SAP Passport
  - ... Please double check with the release notes

2023-07-24 12:53 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
>  There is a good chance that just bumping the version to `4.0.0` is already enough, without the need for any further adjustments.
```suggestion
There is a good chance that just bumping the version to `5.0.0` is already enough, without the need for any further adjustments.
```

Why did you comment the introduction? Also there are still many mentions of v4 in this page.

2023-07-24 12:53 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
>  ## Update Your POM.XML
Why keep the `Update Your POM.XML` chapter?

2023-07-24 12:53 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
>  The `ThreadContext` interface and all related API have received substantial changes.
Why keep the `ThreadContext` chapter?

2023-07-24 12:53 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v5/guides/tutorial-overview-sdk-java.mdx
>      Migrate an existing project to version 3.0 of the SAP Cloud SDK.
You could remove this migration to v3 link, no one uses v2

2023-07-26 07:18 UTC, KavithaSiva commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
>  There is a good chance that just bumping the version to `4.0.0` is already enough, without the need for any further adjustments.
The entire migration guide is commented out, I thought it would be better to publish the full guide while we release v5.
The only parts visible now in the guide is list of modules, API that have been deprecated/removed.
<img width="1453" alt="Screenshot 2023-07-26 at 09 15 39" src="https://github.com/SAP/cloud-sdk/assets/32287936/293fb648-c030-4118-ad35-1f82cdc0c01d">

2023-07-26 07:34 UTC, KavithaSiva commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
> +## List of modules that have been removed with version 5
Removed usages of `ErpHttpDestination` and cleanup migration guide contents to make it easier to add v5 content.

2023-07-26 07:35 UTC, KavithaSiva commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
>  ## Update Your POM.XML
Just to fill required content in later.

2023-07-26 07:35 UTC, KavithaSiva commented on docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
>  The `ThreadContext` interface and all related API have received substantial changes.
Removed.

2023-07-26 08:05 UTC, CharlesDuboisSAP requested changes
I would also remove the three duplicated tables:
- Full list of removed modules
- Full list of deprecated modules
- Full list of deprecated API
And move them into the commented parts of the guide. That way they would not be duplicated anymore and they would be integrated into the guide

2023-07-26 09:36 UTC, KavithaSiva commented
> I would also remove the three duplicated tables:
> 
> * Full list of removed modules
> * Full list of deprecated modules
> * Full list of deprecated API
> 
> And keep only the tables in the commented parts of the guide. That way they would not be duplicated anymore and they would be integrated into the guide

I integrated the contents of the tables into the commented parts of the guide, but would still like to leave out the tables on display in the guide, as a preview of changes we do in v5.

2023-07-26 09:46 UTC, CharlesDuboisSAP approved these changes

2023-07-26 09:47 UTC, merged