Add docu about CAP and SDK integration
SAP/cloud-sdk pull request #15
Opened 2020-11-12 14:50 UTC by Emdee89

This documentation illustrates how the Cloud SDK can be integrated into an existing CAP app.

2020-11-12 14:55 UTC, sacnl requested changes
Component scan annotation is not required?

2020-11-12 14:55 UTC, sacnl commented on docs/java/guides/cap-sdk-integration.mdx
> +Add the respective Cloud SDK dependencies to the POM file under the `srv` directory.
Add a statement that the concrete dependencies to add may be different depending on requirements. (Do we have docs that explain which module to use for what for minimal footprint?)

2020-11-12 14:55 UTC, sacnl commented on docs/java/guides/cap-sdk-integration.mdx
> +In order to integrate the tenant and user concepts between CAP and the Cloud SDK, we'll add a respective integration dependency to the POM file under the `srv` directory.
Do I always have to do that? If not, in which cases? Mention that this goes into the same place as before.

2020-11-12 14:55 UTC, sacnl commented on docs/java/guides/cap-sdk-integration.mdx
> +This document outlines how you integrate the SAP Cloud SDK into an application based on the [SAP Cloud Application Programming Model](https://cap.cloud.sap/docs/) (referred to as *CAP* in the remaind
Mention in how far this differs from adding the SDK to any other Java project. (Do we have documentation for that?)

2020-11-12 15:25 UTC, Emdee89 commented on docs/java/guides/cap-sdk-integration.mdx
> +This document outlines how you integrate the SAP Cloud SDK into an application based on the [SAP Cloud Application Programming Model](https://cap.cloud.sap/docs/) (referred to as *CAP* in the remaind
I find it difficult to mention here at each step "This is relevant for CAP only" or so. I would say we create a document about integration "with any other Java project" in the future and let this CAP integration docu only mention the additional steps.

Meaning, I would leave this mention out here for now.

2020-11-12 15:27 UTC, Emdee89 commented on docs/java/guides/cap-sdk-integration.mdx
> +Add the respective Cloud SDK dependencies to the POM file under the `srv` directory.
I added a note on this topic.

2020-11-12 15:27 UTC, Emdee89 commented on docs/java/guides/cap-sdk-integration.mdx
> +In order to integrate the tenant and user concepts between CAP and the Cloud SDK, we'll add a respective integration dependency to the POM file under the `srv` directory.
Further explanation added

2020-11-12 15:27 UTC, Emdee89 commented
> Component scan annotation is not required?

I added a section about this.

2020-11-12 20:15 UTC, artemkovalyov approved these changes
One obvious example of fine-grained dependencies would be nice. Give just use-case and name of module - no need to provide another extract from the pom.

2020-11-12 20:15 UTC, artemkovalyov commented on docs/java/guides/cap-sdk-integration.mdx
> +:::note
```suggestion
:::tip
```

2020-11-12 20:15 UTC, artemkovalyov commented on docs/java/guides/cap-sdk-integration.mdx
> +:::
I think we need at least one specific example. Otherwise, this sounds very broad to me. Let's at least mention some specific use-case and give module names to use.

2020-11-12 20:16 UTC, artemkovalyov requested changes
Sorry, meant to ask for a change with the last one. Request me again when done.

2020-11-13 08:25 UTC, Emdee89 commented on docs/java/guides/cap-sdk-integration.mdx
> +:::
Let's create a new dedicated page for that in the future.

2020-11-13 08:29 UTC, artemkovalyov approved these changes
Thanks, Marco, let's not forget a BLI about integrating SDK into an existing project.

2020-11-13 08:31 UTC, artemkovalyov commented
@sacnl, take a look if you're ok with changes/suggestions to unblock the merge?

2020-11-13 09:14 UTC, sacnl approved these changes

2020-11-13 09:25 UTC, merged