update bas documentation
SAP/cloud-sdk pull request #154
Opened 2021-03-05 10:30 UTC by FrankEssenberger

## What Has Changed?

Update BAS documentation.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-03-05 13:37 UTC, artemkovalyov requested changes
This is valuable material for improving the support situation with BAS. I left suggestions for the issues I've found. Please, explain what those HTML links are there for?

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +### Technical Background <a name="background"></a>
What's the purpose of these empty links? Navigation?
Docusaurus generated IDs for headers. Can they be used instead?
Same question for other occasions of this pattern.

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +
```suggestion
You have a Cloud Foundry account and a subscription to the BAS.
Via the subscription, the BAS can access all destinations in the subscribed account.

```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +### Prerequisite 1: The Business Application Studio
```suggestion
### Prerequisite 1: The Business Application Studio (BAS)
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +All authorization information from the real destination are used.
```suggestion
All authorization information from the real destination is used.
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +All authorization information from the real destination are used.
Unless you meant "destinations" to be plural.

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +This is done by calling:
```suggestion
If this returns 200 for the service you want to use, you can start the implementation.
The connectivity proxy has a build-in cache that needs to be emptied after you adjusted destinations.
This is done by calling:
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +The SAP Cloud SDK team is currently investigation with the colleagues from BAS if principal propagation is possible and which conditions are needed.
```suggestion
The SAP Cloud SDK team is currently investigating with the colleagues from BAS if principal propagation is possible and which conditions are needed.
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +If not, follow the [steps in the cloud foundry tutorial](https://developers.sap.com/group.s4sdk-js-cloud-foundry.html).
```suggestion
On Cloud Foundry, access to services is granted via the `VCAP_SERVICE` variables.
We assume that you have configured your application so that it can access the destination service.
If not, follow the [steps in the cloud foundry tutorial](https://developers.sap.com/group.s4sdk-js-cloud-foundry.html).
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +Then select the application from which you wan to mirror the variables and select the folder containing the `.env` file to store it.
```suggestion
Then select the application from which you want to mirror the variables and select the folder containing the `.env` file to store it.
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +We recommend to create dedicated development destinations with authentications flows like:
```suggestion
Now your application will fetch the service credentials and call the destination service as in production.
Note that there are certain limitations to this approach.
Within the BAS you will not have a JWT issued for your user.
This means that flows like `OAuth2SAMLBearerAssertion` and `OAuth2UserTokenExchange` can only work if you provide such a JWT.
This is possible in principle, but difficult within the local development environment.
We recommend creating dedicated development destinations with authentications flows like:
```

2021-03-05 13:37 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +Note that for the connection to cloud system the destinations do not need the two properties `WebIDEEnabled` and `HTML5.DynamicDestination`, because the BAS connectivity proxy is not needed.
```suggestion
Note that for the connection to a cloud system the destinations do not need the two properties `WebIDEEnabled` and `HTML5.DynamicDestination`, because the BAS connectivity proxy is not needed.
```

2021-03-05 15:21 UTC, marikaner reviewed
Not much to say, check the comments ;)

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +When such a pattern is found the destination name is extracted and checked against the destinations in the related cloud foundry account.
```suggestion
When such a pattern is found the destination name is extracted and checked against the destinations in the related Cloud 
Foundry account.
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +### Testing <a name="testing"></a>
Testing sounds like generally, how to test something - but this refers to how to check that the connection is correctly configured (I think). Maybe you can be a little more specific?

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +If this returns 200 for the service you want to use, you can start the implementation.
```suggestion
If the request responds with status code 200 for the service you want to use, you can start the implementation.
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +Before you start the implementation it is good to test the connection.
Why is it good? Or:
```suggestion
Before you start the implementation, ensure that the connection is correctly configured.
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +As discussed in the beginning, we need to set the `destinations` environment variable.
I am not a fan of back references (although I think in guides they are ok). In this case I don't think it is needed.
Consider something in this direction:
```suggestion
We have to set the `destinations` environment variable, to provide our destination.
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +destinations="[{"name": "<destinationName>","url": "http://<destinationName>.dest"}]"
```suggestion
destinations="[{"name": "<destinationName>", "url": "http://<destinationName>.dest"}]"
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +As you see you use the same pattern `<name>.dest` we discussed in the [testing section](#testing).
```suggestion
You can use the same pattern `<name>.dest` that you have used for [testing the connection](#testing).
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +On cloud foundry the access to services is granted via the `VCAP_SERVICE` variables.
```suggestion
On Cloud Foundry the access to services is granted via the `VCAP_SERVICE` variables.
```

2021-03-05 15:21 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +If not, follow the [steps in the cloud foundry tutorial](https://developers.sap.com/group.s4sdk-js-cloud-foundry.html).
```suggestion
If not, follow the [steps in the Cloud Foundry tutorial](https://developers.sap.com/group.s4sdk-js-cloud-foundry.html).
```

2021-03-05 16:14 UTC, FrankEssenberger commented
I added `Cloud Foundry` to the SAP product rules

2021-03-05 16:29 UTC, marikaner approved these changes
LGTM

2021-03-08 20:03 UTC, artemkovalyov approved these changes
Looks great

2021-03-09 07:52 UTC, merged