execute raw
SAP/cloud-sdk pull request #155
Opened 2021-03-05 18:25 UTC by jjtang1985

## What Has Changed?

Add doc for `executeRaw`.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-03-07 00:58 UTC, artemkovalyov requested changes
I suggest fixes for better readability.

2021-03-07 00:58 UTC, artemkovalyov commented on docs/js/features/odata/execute-odata-request.mdx
> +There are some valid use cases that the typed response does not meet special requirements like below:
```suggestion
There are some valid use cases with requirements that a typed response doesn't meet:
```

2021-03-07 00:58 UTC, artemkovalyov commented on docs/js/features/odata/execute-odata-request.mdx
> +- in addition to the response, the request built by the SAP Cloud SDK needs also to be returned
```suggestion
- the response cannot be deserialized automatically, so the raw response can work as a workaround
- instead of the response body, additional information is needed like status code or response header
- in addition to the response, the request built by the SAP Cloud SDK needs also to be returned
```

2021-03-07 00:58 UTC, artemkovalyov commented on docs/js/features/odata/execute-odata-request.mdx
> +:::note
```suggestion
:::note typed response from `execute()` is the best practice
```

2021-03-07 00:58 UTC, artemkovalyov commented on docs/js/features/odata/execute-odata-request.mdx
> +The `executeRaw` should only be used for good reasons.
```suggestion
Use `executeRaw` only for workarounds, debugging, logging, and other good reasons where the typed `execute` method doesn't provide enough flexibility.
```

2021-03-08 20:01 UTC, artemkovalyov approved these changes
LGTM, unless you want reviews from Marika and Frank before merging.

2021-03-09 06:14 UTC, marikaner requested changes
Looks mostly good, but I am missing an example.

2021-03-09 06:14 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +- the response cannot be deserialized automatically, so the raw response can work as a workaround
I would like to add an example to this point when this might be the case .

2021-03-09 06:14 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +- in addition to the response, the request built by the SAP Cloud SDK needs also to be returned
I am really sorry for not reviewing your PR on this. I wasn't aware that we also return the ODataRequest instance that we create and I am not sure that this is the best idea. Let's discuss this offline.

2021-03-09 06:14 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +To fulfill the requirement shown above, the SAP Cloud SDK provides the `executeRaw` function that returns the original request and the corresponding raw response.
"the requirement(s) shown above" is quite abstract. I would try to tell from the beginning what this is about and than keep the name up. Maybe:
```suggestion
To retrieve a raw response for your request use the `executeRaw` method.
```

2021-03-09 06:14 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +:::note typed response from `execute()` is the best practice
This should be a title and uppercase
```suggestion
:::note Best Practice: Retrieve typed responses using `execute()`
```

2021-03-09 06:14 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +Use `executeRaw` only for workarounds, debugging, logging, and other good reasons where the typed `execute` method doesn't provide enough flexibility.
Do you think that this is true? Is there anything wrong with `executeRaw` so that we need to speak out this warning?

2021-03-09 08:03 UTC, FrankEssenberger commented on docs/js/features/odata/execute-odata-request.mdx
> +### Getting the Raw Response
Perhaps I would include also the Request like `Getting the Raw Request/Response`

2021-03-09 08:09 UTC, jjtang1985 commented on docs/js/features/odata/execute-odata-request.mdx
> +Use `executeRaw` only for workarounds, debugging, logging, and other good reasons where the typed `execute` method doesn't provide enough flexibility.
This is rather a guidance/recommendation instead of a warning.
Here are some reasons.
- "type-safe" is one of the keywords of the sdk. `execute` gives you a deserialised typed object instead of a raw json. Here are some pros of the typed object:
  - No need for the user to care the response structure. Consider the difference of `get all response` and `get by key response`.
  - No need for the user to deserialise a json, which might be used in e.g., an `update request builder`.
  - IDE auto-completion when you want to get a property value
- For the current main branch (might need to be discussed), the return type contains the `HttpRequest` and the `HttpResponse` (`body` + `header` + ...), which is far more than the typed object from `execute`. For some big entities and consider batch, this might lead to unnecessary performance issue.

2021-03-15 08:24 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +Use `executeRaw` only for workarounds, debugging, logging, and other good reasons where the typed `execute` method doesn't provide enough flexibility.
I see your point, that in most cases we recommend to use the deserialized types. But there are use cases where you might *need* `executeRaw` - e. g. if you want to access the status code. This is not a workaround (or debugging or logging).
This side note sounds like there might be something wrong with `executeRaw`.

Maybe to make it sound less harsh, instead of putting this in a separate note here, you could lead with that, something in that direction: "For most cases we recommend retrieving the deserialized response using `execute`. In some cases..."

2021-03-22 09:30 UTC, marikaner approved these changes
One minor suggestion, otherwise LGTM

2021-03-22 09:30 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +In some cases, on the other hand, you might prefer to retrieve the raw response and the original request:
My english teacher always said you cannot use "on the other hand" if you didn't use "on the one hand". ;)
```suggestion
In some cases, you might prefer to retrieve the raw response and the original request:
```

2021-03-22 10:09 UTC, jjtang1985 commented on docs/js/features/odata/execute-odata-request.mdx
> +In some cases, on the other hand, you might prefer to retrieve the raw response and the original request:
Here is one [answer](https://english.stackexchange.com/questions/352529/can-on-the-other-hand-be-used-without-on-one-hand) with the reference from Cambridge dictionary. But I'm fine without `on the other hand`, which seems to be formal usage.

2021-03-22 13:24 UTC, merged