Update Java Overview page
SAP/cloud-sdk pull request #1695
Opened 2024-02-01 10:30 UTC by newtork

## What Has Changed?

Update graphic for v5, leave old one for v4, remove VDM reference

2024-02-01 10:42 UTC, Johannes-Schneider requested changes

2024-02-01 10:42 UTC, Johannes-Schneider commented on docs-java/overview.mdx
> +You can generate your own API client for [OData](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client) or [OpenAPI](https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate
[major]

Please do not use absolute links for our own pages.

---

[major]

These links are pointing to the JS docs, right? That should be fixed.

2024-02-05 09:21 UTC, newtork commented on docs-java/overview.mdx
> +You can generate your own API client for [OData](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client) or [OpenAPI](https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate
Done. (As I said last week, I'm not a fan of drive-by changes.)

2024-02-05 09:55 UTC, Johannes-Schneider approved these changes
LGTM

2024-02-05 09:55 UTC, merged