Release Notes Java 3.41.0
SAP/cloud-sdk pull request #180
Opened 2021-03-18 22:27 UTC by MatKuhr

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-03-19 09:29 UTC, newtork commented on docs/java/release-notes.mdx
> +      .addReadOperation(readOperationByKey)
Update docs to last minute change:
```suggestion
      .addReadOperations(readOperationAll)
      .addReadOperations(readOperationByKey)
```

2021-03-26 02:52 UTC, artemkovalyov requested changes
Hey @MatKuhr , as I understand the release is through. I have a couple of suggestions. Check if they make sense and we can merge this ASAP.

2021-03-26 02:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- The OData V4 VDM generator now generates static fields for accessible properties on `VdmComplex` types, which can be used exactly like their counterparts on `VdmEntity` when building OData queries.
```suggestion
- The OData v4 type-safe client (VDM) generator now generates static fields for accessible properties on `VdmComplex` types, which can be used exactly like their counterparts on `VdmEntity` when building OData queries.
```

2021-03-26 02:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Update requests via **PATCH** in OData V4 will not contain any changes to complex properties of an entity. This is a feature gap to be overcome in an upcoming release.
```suggestion
- Update requests via **PATCH** in OData V4 will not contain any changes to complex properties of an entity. This is a feature gap we plan to solve in the upcoming release.
```

2021-03-26 02:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue with OData V2 read requests where an error message was incorrectly written to the log when using filters.
```suggestion
- We fixed an issue with OData V2 read requests where an error message was incorrectly written to the log when using filters.
```

2021-03-26 02:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue with OData response handling where deserialization of one-to-many properties failed for primitive and complex data types.
```suggestion
  The error messages are no longer logged unless it is applicable:
  > Registered custom filter expression cannot be used when performing the OData V2 request with toRequest() or executeRequest().
  > Registered custom filter expression cannot be used when performing the OData V2 request with execute().
  
- Fix an issue with OData response handling where deserialization of one-to-many properties failed for primitive and complex data types.
```

2021-03-26 02:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue with OData response handling where deserialization of one-to-many properties failed for primitive and complex data types.
Are those citations representing the situation when the errors are logged?

2021-03-26 02:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Enable new experimental OData V2 reading requests as items in a Batch request. The API is similar to OData V4 Batch request:
```suggestion
- We added a convenience method to configure the proxy authorizations when building a custom `DefaultHttpDestination`.
  The `.proxyAuthorization("value")` will send `value` within the `Proxy-Authorization` header, unless that header is already set.
- The OpenAPI generator now supports the vendor extension field `x-sap-cloud-sdk-api-name` in an OpenAPI specification.
  By default, the OpenAPI generator uses the `tag` of an operation to determine the Java service class name.
  In case you're not happy with the name generated from the `tag` field, and changing it is not possible, you can add `x-sap-cloud-sdk-api-name` vendor extension to the `operation` section of the specification. This vendor extension will be used by the generator to derive the Java service class name.
- Enable OData requests to skip the CSRF token retrieval if the server does not require it.
  Use the method `withoutCsrfToken()` to disable the CSRF token retrieval.
- We provided experimental support for OData v2 read requests as items in a Batch request. The API is unified and similar to the OData v4 Batch request:
```

2021-03-26 16:36 UTC, artemkovalyov approved these changes
Danke!

2021-03-26 16:36 UTC, merged