Java v4.32.0 release notes
SAP/cloud-sdk pull request #1835
Opened 2024-06-12 12:02 UTC by newtork

## What Has Changed?

Added release notes for Cloud SDK for Java 4.32.0

2024-06-12 12:03 UTC, newtork commented on docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
> +- Fix an issue where the current principal wasn't correctly derived from the incoming request in BTP Neo applications.
```suggestion
- Fix an issue where the current principal wasn't correctly derived from the incoming request in SAP BTP Neo applications.
```

2024-06-12 14:25 UTC, CharlesDuboisSAP requested changes

2024-06-12 14:25 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v4/release-notes.mdx
> +To continue using the latest features outlined in the release notes below, please [update to **the SAP Cloud SDK v4**](/docs/java/v4/guides/4.0-upgrade) and [to **the SAP Cloud SDK v5**](https://sap.
Suggestion:

### The SAP Cloud SDK v3 and v4 for Java are Deprecated

:::info Update to the SAP Cloud SDK v5

Version 3.x and 4.x of the SAP Cloud SDK for Java have reached their end of life.
As a consequence, there won't be any updates to the SAP Cloud SDK version 3 or 4 - not even security fixes.
To continue using the latest features outlined in the release notes below, please [update to **the SAP Cloud SDK v4**](/docs/java/v4/guides/4.0-upgrade) then [to **the SAP Cloud SDK v5**](https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps).

2024-06-12 14:25 UTC, CharlesDuboisSAP commented on docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
> +      - Update [Spring Framework](https://central.sonatype.com/artifact/org.springframework/spring-framework-bom/5.3.34) (`org.springframework:spring-framework-bom`) from `5.3.32` to `5.3.34`
```suggestion
      - Update [Spring Framework](https://central.sonatype.com/artifact/org.springframework/spring-framework-bom/5.3.34) (`org.springframework:spring-framework-bom`) from `5.3.32` to `5.3.34`
      - Update [Lombok](https://central.sonatype.com/artifact/org.projectlombok/lombok/1.18.32) (`oorg.projectlombok: lombok `) from `1.18.30` to `1.18.32`
```

2024-06-12 15:35 UTC, newtork commented on docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
> +      - Update [Spring Framework](https://central.sonatype.com/artifact/org.springframework/spring-framework-bom/5.3.34) (`org.springframework:spring-framework-bom`) from `5.3.32` to `5.3.34`
I would not mention Lombok. It's a dependency at compile time (i.e. `provided` scope in parent-pom).
Only exception would be generator modules. but IMHO this doesn't qualify.

2024-06-13 07:01 UTC, CharlesDuboisSAP approved these changes

2024-06-13 07:01 UTC, merged