Rename SAP Cloud Platform to SAP Business Technology Platform
SAP/cloud-sdk pull request #184
Opened 2021-03-21 16:04 UTC by artemkovalyov

## What Has Changed?

It gets a bit longer, but should still make sense. SCP -> SBTP

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [-] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-03-21 19:30 UTC, artemkovalyov commented
I plan to update Vale rules after the renaming is done and we agree on the naming pattern.

2021-03-22 09:16 UTC, MatKuhr reviewed
changes look good, but please also change the abbreviation `SCP` to `BTP` _unless_ it is referring to module, package or class names.

2021-03-22 09:16 UTC, MatKuhr commented on docs/java/faq.mdx
>  SAP Cloud SDK for Java has first-class support for [SCP Cloud Foundry](https://www.sap.com/products/cloud-platform.html).
```suggestion
SAP Cloud SDK for Java has first-class support for [BTP Cloud Foundry](https://www.sap.com/germany/products/business-technology-platform.html).
```

2021-03-22 10:22 UTC, artemkovalyov commented
@MatKuhr, I'd put it to another PR for simpler review. This one is big enough for meaningful cross-check and drives most semantics.

2021-03-22 10:27 UTC, sacnl requested changes
A few corrections according to https://www.sapbrandtools.com/naming-center/#/requests/10022

2021-03-22 10:27 UTC, sacnl commented on docs/js/getting-started.mdx
> +Using the SAP Cloud SDK, you can reduce your effort when developing an application on SAP Business Technology Platform by building on best practices delivered by the SAP Cloud SDK.
```suggestion
Using the SAP Cloud SDK, you can reduce your effort when developing an application on SAP Business Technology Platform (SAP BTP) by building on best practices delivered by the SAP Cloud SDK.
```

... and afterwards you could use SAP BTP instead, at least for compound names.

2021-03-22 10:27 UTC, sacnl commented on docs/js/getting-started.mdx
> +- **`manifest.yml`**: The deployment descriptor file for `Cloud Foundry in SAP Business Technology Platform`.
```suggestion
- **`manifest.yml`**: The deployment descriptor file for `SAP BTP, Cloud Foundry environment`.
```

2021-03-22 10:27 UTC, sacnl commented on docs/js/getting-started.mdx
> +Open the [SAP Business Technology Platform Cockpit](https://account.hana.ondemand.com/) and navigate to the subaccount you are planning to deploy your application to.
```suggestion
Open the [SAP BTP cockpit](https://account.hana.ondemand.com/) and navigate to the subaccount you are planning to deploy your application to.
```

2021-03-22 10:27 UTC, sacnl commented on docs/js/getting-started.mdx
> +Open the [SAP Business Technology Platform Cockpit](https://account.hana.ondemand.com/) and navigate to the subaccount you are planning to deploy your application to.
> cockpit as lower case

2021-03-22 10:27 UTC, sacnl commented on docs/overview/sdk-used-by.mdx
> +## [SAP Business Technology Platform Workflow](https://help.sap.com/viewer/product/WORKFLOW_SERVICE/Cloud/en-US)
This is apparently now called "SAP Workflow service" - without BTP

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
>  sidebar_label: SCP Workflow API
```suggestion
sidebar_label: SAP Workflow service
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +title: Type-Safe Client for SAP Business Technology Platform Workflow REST API
```suggestion
title: Type-Safe Client for SAP Workflow service
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +The [SAP Business Technology Platform (SCP) Workflow service](https://help.sap.com/viewer/product/WORKFLOW_SERVICE/Cloud/en-US) is available on the Cloud Foundry environment [since April 2019](https:
```suggestion
The [SAP Workflow service](https://help.sap.com/viewer/product/WORKFLOW_SERVICE/Cloud/en-US) is available on the Cloud Foundry environment [since April 2019](https://blogs.sap.com/2019/04/03/workflow-and-business-rules-now-available-in-cloud-foundry-environment-of-sap-cloud-platform/).
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +Use SAP Business Technology Platform Workflow service and its REST API.
```suggestion
Use SAP Workflow service and its REST API.
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +## Consume the SAP Business Technology Platform Workflow REST API
```suggestion
## Consume the SAP Workflow REST API in BTP Cloud Foundry environment
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +#### Add SAP Business Technology Platform Workflow Library Dependency To Your Project
```suggestion
#### Add SAP Workflow Library Dependency To Your Project
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
>  - We support SCP Workflow API only on SCP Cloud Foundry.
```suggestion
- We support SAP Workflow service API only on the SAP BTP Cloud Foundry environment.
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +  The SAP Business Technology Platform Neo landscape in **Not supported!**
```suggestion
  The SAP Business Technology Platform Neo environment is **Not supported!**
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
>  - In the current state, it is required to create a destination manually instead of letting the library resolve it for you via VCAP_SERVICES binding available on SCP Cloud Foundry.
```suggestion
- In the current state, it is required to create a destination manually instead of letting the library resolve it for you via VCAP_SERVICES binding available on the BTP Cloud Foundry environment.
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +This video tutorial by the developer advocate team of SAP Business Technology Platform will help you get up to speed with SAP Cloud SDK for Java and Workflow API in 60 minutes.
```suggestion
This video tutorial by the developer advocate team of SAP Business Technology Platform will help you get up to speed with SAP Cloud SDK for Java and Workflow service API in 60 minutes.
```

2021-03-22 11:20 UTC, artemkovalyov commented on docs/java/features/rest/overview.mdx
> +The [SAP Business Technology Platform Workflow API](clients/scp-workflow-rest-api) is an example of a publicly released API module.
```suggestion
The [SAP Workflow service API](clients/scp-workflow-rest-api) is an example of a publicly released API module.
```

2021-03-22 11:21 UTC, artemkovalyov commented on docs/overview/sdk-used-by.mdx
> +## [SAP Business Technology Platform Workflow](https://help.sap.com/viewer/product/WORKFLOW_SERVICE/Cloud/en-US)
I fixed naming around workflow

2021-03-22 11:29 UTC, sacnl approved these changes
There is still one suggestion (by yourself) pending, otherwise lgtm

2021-03-22 11:29 UTC, sacnl commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +#### Add SAP Business Technology Platform Workflow Library Dependency To Your Project
Workflow Service Library?

2021-03-22 11:40 UTC, artemkovalyov commented
This doesn't seem easy to make much sense with our naming bundling 3-5 semantical contexts into each and every one of them. I gave my best.

2021-03-22 12:30 UTC, merged