Javascript: Add documentation for service binding to destination API
SAP/cloud-sdk pull request #1883
Opened 2024-08-06 13:21 UTC by shibeshduw

## What Has Changed?

Added documentation for the 2 new public APIs which were added in [v3.16.0](https://github.com/SAP/cloud-sdk-js/releases/tag/v3.16.0) release:
- `getServiceBinding`
- `transformServiceBindingToDestination`

Closes SAP/cloud-sdk-backlog#1221

2024-08-09 14:23 UTC, KavithaSiva requested changes

2024-08-09 14:23 UTC, KavithaSiva commented on docs-js/features/connectivity/destination.mdx
> +In addition to the default internal transformations, the SAP Cloud SDK provides the `getServiceBinding` function to retrieve a service type from a string input and a public convenience function `tran
```suggestion
The SAP Cloud SDK provides a `getServiceBinding` function to retrieve the first service binding from `VCAP_SERVICES` for a given service type.

It also provides a convenience function `transformServiceBindingToDestination` that simplifies the process of transforming the obtained service binding into a destination.
```

2024-08-09 14:23 UTC, KavithaSiva commented on docs-js/features/connectivity/destination.mdx
> +The function supports the [default service types](#service-binding-environment-variables) as listed above.
```suggestion
`transformServiceBindingToDestination` supports the [default service types](#service-binding-environment-variables) as listed above.
```

2024-08-09 14:23 UTC, KavithaSiva commented on docs-js/features/connectivity/destination.mdx
> +The function supports the [default service types](#service-binding-environment-variables) as listed above.
I would suggest to add the whole section into `:::info Creating destinations from service bindings` admonitions.

And add the code example into a `<details>` block like [this](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/service-bindings#custom-parameters).

2024-08-09 14:23 UTC, KavithaSiva commented on docs-js/features/connectivity/destination.mdx
> +In addition to the default internal transformations, the SAP Cloud SDK provides the `getServiceBinding` function to retrieve a service type from a string input and a public convenience function `tran
Additionally, it is also important to mention that the created destinations will always have the token obtained using the `OAuth2ClientCredentials` flow for most service types except for `s4-hana-cloud`

2024-08-12 13:52 UTC, marikaner reviewed
generally looks good to me, just details

2024-08-12 13:52 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +It also provides a convenience function `transformServiceBindingToDestination` that simplifies the process of transforming a service binding to a destination.
```suggestion
It also provides the`transformServiceBindingToDestination()` function to transform known service bindings to a destinations.
```

2024-08-12 13:52 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +The SAP Cloud SDK provides the `getServiceBinding` function to retrieve the first service binding from `VCAP_SERVICES` for a given service type.
[req] Follow the style guide: https://github.com/SAP/cloud-sdk/blob/main/STYLEGUIDE.md#use-code-format-for-method-names
```suggestion
The SAP Cloud SDK provides the `getServiceBinding()` function to retrieve the first service binding from `VCAP_SERVICES` for a given service type.
```

2024-08-12 13:52 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +`transformServiceBindingToDestination` supports the [default service types](#service-binding-environment-variables) as listed above.
```suggestion
`transformServiceBindingToDestination()` supports the [default service types](#service-binding-environment-variables) as listed above.
```

2024-08-12 13:52 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +The created destinations will consistently include the token obtained through the `OAuth2ClientCredentials` flow for all service types, except for `s4-hana-cloud`.
[req] This sounds like we do everything for you except in the s4-hana-cloud case. I would phrase this differently.
Please also leave out fill words like "consistently". I also suggest to keep the same wording as above (transform instead of create).

```suggestion
The transformation includes auth token flows for destinations with type `OAuth2ClientCredentials` and adds retrieved tokens to the destination.
```

2024-08-12 13:52 UTC, marikaner commented on docs-js/features/connectivity/destination.mdx
> +If the provided service binding is not supported, an error will be thrown indicating the unsupported service type.
```suggestion
If the provided service binding is not supported, an error is thrown.
```

2024-08-12 15:05 UTC, merged