SCP -> BTP, Cloud Foundry - Cloud Foundry environment
SAP/cloud-sdk pull request #199
Opened 2021-04-01 10:25 UTC by artemkovalyov

## What Has Changed?

Renaming according to SAP naming brand book:

SCP -> BTP
Cloud Foundry -> Cloud Foundry environment
## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-04-01 10:53 UTC, marikaner requested changes
I think the naming entry refers to usage with SAP BTP only, not in general.
You are allowed to use natural language in text, e.g. "SAP BTP for the Cloud Foundry environment".

Cloud Foundry in general is open source and can be used as we used it in many places, it does not require adding "environment" and in many places it even breaks the sentence. I think to make this change correctly you have to really go through each occurrence and check it for correctness.

FYI: See usage of "Cloud Foundry": https://www.cloudfoundry.org/

2021-04-01 10:53 UTC, marikaner commented on docs/java/extensions/currency-conversion.mdx
> +If you want to run the library in the Cloud Foundry environment environment, use the following:
This is duplicate. I have seen this in a few places when scrolling through. Please check that this is correct everywhere.

2021-04-01 10:53 UTC, marikaner commented on docs/java/faq.mdx
> +SAP Cloud SDK for Java has first-class support for [BTP Cloud Foundry environment](https://www.sap.com/germany/products/business-technology-platform.html).
```suggestion
The SAP Cloud SDK for Java has first-class support for [BTP Cloud Foundry environment](https://www.sap.com/germany/products/business-technology-platform.html).
```

2021-04-01 10:53 UTC, marikaner commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +9. [Create Cloud Foundry environment App with Blockchain Features of SAP Cloud SDK](https://developers.sap.com/tutorials/blockchain-sdk-sample.html)
I think here environment doesn't make sense - I saw some other places where this is the case. I think we would have to go through each occurence and check whether the sentence still makes sense...

2021-04-01 10:53 UTC, marikaner commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +2. [Create a Sample Application on Cloud Foundry environment Using SAP Cloud SDK](https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html)
Here it also doesn't really make sense. It should be "on Cloud Foundry" or "in the Cloud Foundry environment".

2021-04-01 10:53 UTC, marikaner commented on docs/java/faq.mdx
> +### Do You Support SAP Business Technology Platform - Cloud Foundry environment?
According to the naming guidelines this should be:
```suggestion
### Do You Support SAP BTP, Cloud Foundry environment?
```

2021-04-01 10:53 UTC, marikaner requested changes
I think the naming entry refers to usage with SAP BTP only, not in general.
You are allowed to use natural language in text, e.g. "SAP BTP for the Cloud Foundry environment".

Cloud Foundry in general is open source and can be used as we used it in many places, it does not require adding "environment" and in many places it even breaks the sentence. I think to make this change correctly you have to really go through each occurrence and check it for correctness.

FYI: See usage of "Cloud Foundry": https://www.cloudfoundry.org/

2021-04-02 09:45 UTC, artemkovalyov reviewed
Manual review

2021-04-02 09:45 UTC, artemkovalyov commented on docs/related-projects/xsuaa.mdx
> +It greatly extends capabilities for Cloud Foundry environment UAA service by providing:
```suggestion
It greatly extends capabilities for SAP BTP Cloud Foundry environment UAA service by providing:
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/related-projects/xsuaa.mdx
> +## What is User Account and Authentication for Cloud Foundry environment?
```suggestion
## What is User Account and Authentication for Cloud Foundry Environment?
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/guides/sdk-in-browser.mdx
> +## Run on Cloud Foundry environment
```suggestion
## Run on SAP BTP Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +You have a Cloud Foundry environment account and a subscription to the BAS.
```suggestion
You have an SAP BTP Cloud Foundry environment account and a subscription to the BAS.
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/guides/bas-external-system.mdx
> +The Business Application Studio (BAS) is a development environment offered as a service on Cloud Foundry environment (CF).
```suggestion
The Business Application Studio (BAS) is a development environment offered as a service on the SAP BTP Cloud Foundry environment (CF).
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/getting-started.mdx
> +You can find installation instructions for all common platforms in the [`Cloud Foundry environment documentation`](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html).
```suggestion
You can find installation instructions for all common platforms in the [`Cloud Foundry documentation`](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html).
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/getting-started.mdx
> +## Deploy the Project on Cloud Foundry environment
```suggestion
## Deploy the Project on SAP BTP Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/features/cli/init.mdx
> +#### Push to Cloud Foundry environment
```suggestion
#### Push to Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/features/cli/init.mdx
> +According to the [Cloud Foundry environment documentation](https://docs.cloudfoundry.org/buildpacks/node/node-tips.html) your app needs to listen to the `PORT` variable.
```suggestion
According to the [Cloud Foundry documentation](https://docs.cloudfoundry.org/buildpacks/node/node-tips.html) your app needs to listen to the `PORT` variable.
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/js/faq.mdx
> +### Do You Support SAP Business Technology Platform - Cloud Foundry environment?
```suggestion
### Do You Support SAP Business Technology Platform - Cloud Foundry Environment?
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/troubleshooting.mdx
> +  Please check the latest details about [SCP Cloud Foundry environment quotas and limitation](https://help.sap.com/viewer/3504ec5ef16548778610c7e89cc0eac3/Cloud/en-US/9c7092c7b7ae4d49bc8ae35fdd0e0b18
```suggestion
  Please check the latest details about [SAP BTP Cloud Foundry Environment quotas and limitation](https://help.sap.com/viewer/3504ec5ef16548778610c7e89cc0eac3/Cloud/en-US/9c7092c7b7ae4d49bc8ae35fdd0e0b18.html#loio9809fa4f02cb4696baea5c23d6eaac94)
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/troubleshooting.mdx
> +## The Java App Has Good Performance on Your Local Machine but Utilizes 100% CPU on SAP Business Technology Platform Cloud Foundry environment
```suggestion
## The Java App Has Good Performance on Your Local Machine but Utilizes 100% CPU on SAP Business Technology Platform Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +9. [Create Cloud Foundry environment App with Blockchain Features of SAP Cloud SDK](https://developers.sap.com/tutorials/blockchain-sdk-sample.html)
```suggestion
9. [Create an App in Cloud Foundry environment with Blockchain Features of SAP Cloud SDK](https://developers.sap.com/tutorials/blockchain-sdk-sample.html)
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +2. [Create a Sample Application on Cloud Foundry environment Using SAP Cloud SDK](https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html)
```suggestion
2. [Create a Sample Application in Cloud Foundry environment Using SAP Cloud SDK](https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html)
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +2. [Create a Sample Application on Cloud Foundry environment Using SAP Cloud SDK](https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html)
Here it makes sense. I'm not sure in this virtual sense if it's in or on. No difference for me either.

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +- [Create a Simple Cloud Foundry environment App Using SAP Cloud SDK](https://developers.sap.com/group.s4sdk-cloud-foundry.html)
```suggestion
- [Create a Simple App in Cloud Foundry environment Using SAP Cloud SDK](https://developers.sap.com/group.s4sdk-cloud-foundry.html)
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/tutorial-overview-sdk-java.mdx
> +- [Create a Cloud Foundry environment App Using SAP Cloud SDK](https://developers.sap.com/mission.cloudsdk-cf-app.html)
```suggestion
- [Create an App in Cloud Foundry environment Using SAP Cloud SDK](https://developers.sap.com/mission.cloudsdk-cf-app.html)
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/logging-overview.mdx
> +#### On Cloud Foundry environment
```suggestion
#### On Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/logging-overview.mdx
> +When running on BTP CloudFoundry using the SAP Java Buildpack the logging implementation is provided at runtime by the container.
```suggestion
When running on the BTP Cloud Foundry environment using the SAP Java Buildpack the logging implementation is provided at runtime by the container.
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/linux-how-to.mdx
> +Provide your credential for SAP Cloud Foundry environment by running:
```suggestion
Provide your credentials for the SAP BTP Cloud Foundry environment by running:
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/linux-how-to.mdx
> +### Bind your Command-Line Interface to SAP Cloud Foundry environment
```suggestion
### Bind your Command-Line Interface to the SAP BTP Cloud Foundry environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/linux-how-to.mdx
> +### Cloud Foundry environment Command Line Interface
```suggestion
### Cloud Foundry Environment Command Line Interface
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-xsuaa.mdx
> +Several services on BTP Cloud Foundry environment require a dedicated OAuth2 access token, e.g. _Connectivity Service_ and _Destination Service_.
```suggestion
Several services on the BTP Cloud Foundry environment require a dedicated OAuth2 access token, e.g. _Connectivity Service_ and _Destination Service_.
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-xsuaa.mdx
> +## SAP Business Technology Platform Cloud Foundry environment XSUAA Key Use-Cases
```suggestion
## SAP Business Technology Platform Cloud Foundry Environment XSUAA Key Use-Cases
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-xsuaa.mdx
> +When developing and deploying an application it quickly becomes important to understand how authentication and authorizations work on BTP Cloud Foundry environment.
```suggestion
When developing and deploying an application it quickly becomes important to understand how authentication and authorizations work on the BTP Cloud Foundry environment.
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-deploy.mdx
> +## Push Application to Cloud Foundry environment
```suggestion
## Push Application to Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-cli.mdx
> +For more details on `SAP Cloud Foundry environment CLI` follow this [official tutorial](https://developers.sap.com/tutorials/cp-cf-download-cli.html).
```suggestion
For more details on `SAP BTP Cloud Foundry environment CLI` follow this [official tutorial](https://developers.sap.com/tutorials/cp-cf-download-cli.html).
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-cli.mdx
> +Provide your credential for SAP Cloud Foundry environment by running:
```suggestion
Provide your credential for SAP BTP Cloud Foundry environment by running:
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-cli.mdx
> +## Bind Your Command-Line Interface To SAP Cloud Foundry environment
```suggestion
## Bind Your Command-Line Interface To SAP BTP Cloud Foundry environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/guides/cf-cli.mdx
> +## Cloud Foundry environment Command-Line Interface
```suggestion
## Cloud Foundry Environment Command-Line Interface
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +### Cloud Foundry environment Configuration
```suggestion
### Cloud Foundry Environment Configuration
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/features/connectivity/destinations.mdx
> +#### Skip Destination Creation Step for Certain Authentication Types on Cloud Foundry environment
```suggestion
#### Skip Destination Creation Step for Certain Authentication Types on Cloud Foundry Environment
```

2021-04-02 09:45 UTC, artemkovalyov commented on docs/java/features/bapi-and-rfc/overview.mdx
> +We build an app that we deploy to BTP Cloud Foundry environment.
```suggestion
We build an app that we deploy to the BTP Cloud Foundry environment.
```

2021-04-02 09:51 UTC, artemkovalyov commented
@marikaner, I did a manual review. In many cases environment makes sense or I re-phrased it. Give suggestions where you disagree. As far as I understood environments is a distinguished and has to be mentioned with BTP renaming.

2021-04-06 10:54 UTC, marikaner requested changes
I went through it manually as well and removed all occurences of "environment" where Cloud Foundry was not used with SAP BTP, I added SAP in front of BTP and added commas and "the" where necessary. I will just merge my changes, please review them afterwards.

I didn't touch the java release notes, but there are some errors in it. I would consider leaving it  as was. @artemkovalyov please assign someone from java to take a look at the release notes as well.

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +sidebar_label: Cloud Foundry environment CLI
```suggestion
sidebar_label: Cloud Foundry CLI
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +description: Configure you Cloud Foundry environment CLI and bind it to SAP Business Technology Platform
```suggestion
description: Configure you Cloud Foundry CLI and bind it to SAP Business Technology Platform
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +## Cloud Foundry Environment Command-Line Interface
```suggestion
## Cloud Foundry Command-Line Interface
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +To deploy your app developed with SAP Cloud SDK to [SAP Business Technology Platform](https://www.sap.com/products/cloud-platform.html) you'll need Cloud Foundry environment command-line interface (C
```suggestion
To deploy your app developed with SAP Cloud SDK to [SAP Business Technology Platform](https://www.sap.com/products/cloud-platform.html) you'll need Cloud Foundry command-line interface (CLI).
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +## Bind Your Command-Line Interface To SAP BTP Cloud Foundry environment
```suggestion
## Bind Your Command-Line Interface to an API Endpoint
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +Let's associate you Cloud Foundry environment CLI to your SAP account by providing an API endpoint and logging in with your account.
```suggestion
Let's associate your Cloud Foundry CLI to your SAP account by providing an API endpoint and logging in with your account.
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +Provide your credential for SAP BTP Cloud Foundry environment by running:
```suggestion
Provide your credentials for SAP BTP:
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +For more details on `SAP BTP Cloud Foundry environment CLI` follow this [official tutorial](https://developers.sap.com/tutorials/cp-cf-download-cli.html).
```suggestion
For more details on the Cloud Foundry CLI and SAP BTP follow this [official tutorial](https://developers.sap.com/tutorials/cp-cf-download-cli.html).
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-cli.mdx
> +Find out more about `SAP Business Technology Platform` and `Cloud Foundry environment` from [official documentation](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/73beb06e1
```suggestion
Find out more about the SAP Business Technology Platform, Cloud Foundry environment in the [official documentation](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/73beb06e127f4e47b849aa95344aabe1.html).
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/guides/cf-deploy.mdx
> +title: Deploy to Cloud Foundry environment
```suggestion
title: Deploy to Cloud Foundry
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/troubleshooting.mdx
> +## The Java App Has Good Performance on Your Local Machine but Utilizes 100% CPU on SAP Business Technology Platform Cloud Foundry Environment
```suggestion
## The Java App Has Good Performance on Your Local Machine but Utilizes 100% CPU on SAP Business Technology Platform, Cloud Foundry Environment
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/troubleshooting.mdx
> +- The performance significantly drops after the app is deployed to SAP Business Technology Platform - Cloud Foundry environment and CPU utilization is always around 100%.
```suggestion
- The performance significantly drops after the app is deployed to SAP Business Technology Platform - Cloud Foundry and CPU utilization is always around 100%.
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/troubleshooting.mdx
> +- BTP Cloud Foundry environment provides 1/4 of CPU unit per every GB of memory.
```suggestion
- SAP BTP, Cloud Foundry environment provides 1/4 of CPU unit per every GB of memory.
```

2021-04-06 10:54 UTC, marikaner commented on docs/java/troubleshooting.mdx
> +  Please check the latest details about [SAP BTP Cloud Foundry Environment quotas and limitation](https://help.sap.com/viewer/3504ec5ef16548778610c7e89cc0eac3/Cloud/en-US/9c7092c7b7ae4d49bc8ae35fdd0e
```suggestion
  Please check the latest details about [SAP BTP, Cloud Foundry Environment quotas and limitations](https://help.sap.com/viewer/3504ec5ef16548778610c7e89cc0eac3/Cloud/en-US/9c7092c7b7ae4d49bc8ae35fdd0e0b18.html#loio9809fa4f02cb4696baea5c23d6eaac94)
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/faq.mdx
> +### Do You Support SAP Business Technology Platform - Cloud Foundry Environment?
```suggestion
### Do You Support SAP Business Technology Platform, Cloud Foundry Environment?
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/faq.mdx
> +SAP Cloud SDK for JavaScript has first-class support for [SCP Cloud Foundry environment](https://www.sap.com/products/cloud-platform.html).
```suggestion
SAP Cloud SDK for JavaScript has first-class support for the [SAP BTP, Cloud Foundry environment](https://www.sap.com/products/cloud-platform.html).
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/faq.mdx
> +Let us know if you're missing any features about BTP Cloud Foundry environment support from SAP Cloud SDK for JavaScript.
```suggestion
Let us know if you miss functionality of the SAP BTP in the SAP Cloud SDK for JavaScript.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +The project name is relevant for the Cloud Foundry environment repository.
```suggestion
The project name is relevant for the Cloud Foundry repository.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +When deploying to Cloud Foundry environment, it calls the entered command to start your application.
```suggestion
When deploying to Cloud Foundry, it calls the entered command to start your application.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> + - Push to Cloud Foundry environment (`cf push`)
```suggestion
 - Push to Cloud Foundry (`cf push`)
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +After the initialization is finished, the CLI displays the necessary steps to deploy your application to Cloud Foundry environment.
```suggestion
After the initialization is finished, the CLI displays the necessary steps to deploy your application to Cloud Foundry.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +#### Push to Cloud Foundry Environment
```suggestion
#### Push to Cloud Foundry
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +Once your project is prepared, you can use the [Cloud Foundry environment CLI](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html) to deploy your application.
```suggestion
Once your project is prepared, you can use the [Cloud Foundry CLI](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html) to deploy your application.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +You may need to log in to your Cloud Foundry environment account first.
```suggestion
You may need to log in to your Cloud Foundry account first.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +On BTP this abstraction is provided by a so-called destination object.
```suggestion
On SAP BTP this abstraction is provided by a so-called destination object.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +This option is present for deployment and testing in a local environment outside the BTP where no destination services are available.
```suggestion
This option is present for deployment and testing in a local environment outside the SAP BTP where no destination services are available.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +A customer is represented by an account on BTP and a service considering the account is a `tenant aware service`.
```suggestion
A customer is represented by an account on the SAP BTP and a service considering the account is a `tenant aware service`.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +Tenant aware services on BTP are offered to customers via a `subscription` which works on a high level as follows:
```suggestion
Tenant aware services on the SAP BTP are offered to customers via a `subscription` which works on a high level as follows:
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/connectivity/on-premise.mdx
> +Only applications running in the connected Cloud Foundry environment account can access the services.
```suggestion
The Cloud Connector works like a reverse proxy opening a connection between some allowlisted service endpoints of the On-premise system, and the connected Cloud Foundry account.
Only applications running in the connected Cloud Foundry account can access the services.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/connectivity/on-premise.mdx
> +The proxy is only reachable from the Cloud Foundry environment space, so you cannot use that flow for applications running outside of Cloud Foundry environment.
```suggestion
The proxy is only reachable from the Cloud Foundry space, so you cannot use that flow for applications running outside of Cloud Foundry.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/features/logging.mdx
> +If `VCAP_SERVICE` variables are present in the environment variables the `kibana` format is used, because the SAP Cloud SDK assumes your application is running on Cloud Foundry environment.
```suggestion
If `VCAP_SERVICE` variables are present in the environment variables the `kibana` format is used, because the SAP Cloud SDK assumes your application is running on Cloud Foundry.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +#### Cloud Foundry environment
```suggestion
#### Cloud Foundry
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +## Deploy the Project on SAP BTP Cloud Foundry Environment
```suggestion
## Deploy the Project on SAP BTP, Cloud Foundry Environment
```
```suggestion
## Deploy the Project to the SAP BTP Cloud Foundry Environment
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +The Cloud Foundry environment CLI comes in handy when you want to deploy your application to the SAP Business Technology Platform.
```suggestion
The Cloud Foundry CLI comes in handy when you want to deploy your application to the SAP Business Technology Platform.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +To deploy our application, we first need to login to Cloud Foundry environment in SAP Business Technology Platform using the `cf` CLI.
```suggestion
To deploy our application, we first need to login to Cloud Foundry in the SAP BTP using the `cf` CLI.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +Dependencies will instead be installed automatically when deploying to `Cloud Foundry environment`.
```suggestion
Dependencies will instead be installed automatically when deploying to Cloud Foundry.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +The Cloud Foundry environment CLI will automatically pick up the `manifest.yml` of the project when deploying your application.
```suggestion
The Cloud Foundry CLI will automatically pick up the `manifest.yml` of the project when deploying your application.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +- The specified `path` instructs Cloud Foundry environment to upload all the files from the `deployment/` folder.
```suggestion
- The specified `path` instructs Cloud Foundry to upload all the files from the `deployment/` folder.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +This tells `Cloud Foundry environment in SAP Business Technology Platform` to create an instance of the destination service with service plan `lite` and make it accessible under the name `my-destinat
```suggestion
This tells Cloud Foundry to create an instance of the destination service with service plan `lite` and make it accessible under the name `my-destination` on the SAP BTP.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/getting-started.mdx
> +The value for `xsappname` again has to be unique across the whole of `Cloud Foundry environment in SAP Business Technology Platform`, so make sure to choose a unique name or prefix.
```suggestion
The value for `xsappname` again has to be unique across the whole of SAP BTP, so make sure to choose a unique name or prefix.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +The Business Application Studio (BAS) is a development environment offered as a service on the SAP BTP Cloud Foundry environment (CF).
```suggestion
The Business Application Studio (BAS) is a development environment offered as a service on the SAP BTP, Cloud Foundry (CF) environment .
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +You have an SAP BTP Cloud Foundry environment account and a subscription to the BAS.
```suggestion
You have an SAP BTP account and a subscription to the BAS.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +On Cloud Foundry environment, the access to services is granted via the `VCAP_SERVICE` variables.
```suggestion
On Cloud Foundry, the access to services is granted via the `VCAP_SERVICE` variables.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +If not, follow the [steps in the Cloud Foundry environment tutorial](https://developers.sap.com/group.s4sdk-js-cloud-foundry.html).
```suggestion
If not, follow the [steps in the Cloud Foundry tutorial](https://developers.sap.com/group.s4sdk-js-cloud-foundry.html).
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/guides/bas-external-system.mdx
> +You can mirror the `VCAP_SERVICE` variables from your Cloud Foundry environment account to your local BAS.
```suggestion
You can mirror the `VCAP_SERVICE` variables from your Cloud Foundry account to your local BAS.
```

2021-04-06 10:54 UTC, marikaner commented on docs/js/guides/sdk-in-browser.mdx
> +## Run on SAP BTP Cloud Foundry Environment
```suggestion
## Run on SAP BTP, Cloud Foundry Environment
```

2021-04-06 10:54 UTC, marikaner commented on docs/related-projects/cap.mdx
> +  - The SAP Business Platform - Cloud Foundry environment Abstractions
```suggestion
  - The SAP Business Platform, Cloud Foundry environment abstractions
```

2021-04-06 10:54 UTC, marikaner commented on docs/related-projects/xsuaa.mdx
> +## What is User Account and Authentication for Cloud Foundry Environment?
```suggestion
## What are the User Account and Authentication for Cloud Foundry?
```

2021-04-06 10:54 UTC, marikaner commented on docs/related-projects/xsuaa.mdx
> +[Cloud Foundry environment](https://help.sap.com/viewer/3504ec5ef16548778610c7e89cc0eac3/Cloud/en-US/9c7092c7b7ae4d49bc8ae35fdd0e0b18.html) is one of the key environments of the [SAP Business Technol
```suggestion
[Cloud Foundry](https://help.sap.com/viewer/3504ec5ef16548778610c7e89cc0eac3/Cloud/en-US/9c7092c7b7ae4d49bc8ae35fdd0e0b18.html) is one of the key environments of the [SAP Business Technology Platform](https://www.sap.com/products/cloud-platform.html).
```

2021-04-06 10:54 UTC, marikaner commented on docs/related-projects/xsuaa.mdx
> +[User Account and Authentication (UAA)](https://docs.cloudfoundry.org/concepts/architecture/uaa.html) is the identity and management service for Cloud Foundry environment.
```suggestion
[User Account and Authentication (UAA)](https://docs.cloudfoundry.org/concepts/architecture/uaa.html) is the identity and management service for Cloud Foundry.
```

2021-04-06 10:54 UTC, marikaner commented on docs/related-projects/xsuaa.mdx
> +It greatly extends capabilities for SAP BTP Cloud Foundry environment UAA service by providing:
```suggestion
It greatly extends capabilities for the SAP BTP UAA service for the Cloud Foundry environment by providing:
```

2021-04-06 11:38 UTC, artemkovalyov commented
@marikaner, I don't understand why we need a comma. Is it like this in naming guidance?

2021-04-06 13:53 UTC, artemkovalyov commented
Java colleagues are assigned. Generally, we can skip release notes for now.

2021-04-06 13:53 UTC, marikaner commented
> @marikaner, I don't understand why we need a comma. Is it like this in naming guidance?

Yes, it mentions that you can leave out the comma in specific places when the context is clear, to my understanding this does not cover titles (it isn't really specified exactly). We often used dashes instead, which is incorrect.

I tried to use more natural language in the text bodies, but I didn't do it everywhere. Whenever I didn't, I think the comma helps readability. ;) 
Naming Entry: https://www.sapbrandtools.com/naming-center/#/requests/10022

2021-04-07 08:39 UTC, artemkovalyov commented
Yeah, I've also found the comma is there. Well, then we comply. Do you see smth still from my side or should we approve this?

2021-04-07 10:32 UTC, marikaner approved these changes

2021-04-07 10:34 UTC, merged