Custom Axios options (request config)
SAP/cloud-sdk pull request #213
Opened 2021-04-12 16:27 UTC by jjtang1985

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-04-12 16:32 UTC, jjtang1985 commented on docs/js/features/odata/execute-odata-request.mdx
> +MyEntity.requestBuilder()
The example cannot be used as this is odata like. For openapi, we need a similar but different example.

2021-04-12 16:40 UTC, jjtang1985 commented
@artemkovalyov, currently all pipelines failed to install vale with 403, is it a known issue?

2021-04-12 17:40 UTC, artemkovalyov requested changes
@jjtang1985 , check my suggestion for correctness. This should improve the readability a bit.

2021-04-12 17:40 UTC, artemkovalyov commented on docs/js/features/common/custom-request-config-note.mdx
> +To avoid unexpected behaviour, basic options are not allowed to be customized and should only be handled by the SAP Cloud SDK.
```suggestion
To ensure API consistency we do not allow to override the following options:
```

2021-04-12 17:40 UTC, artemkovalyov commented on docs/js/features/common/custom-request-config-note.mdx
> +Here is a list of the basic options:
```suggestion
```

2021-04-12 17:40 UTC, artemkovalyov commented on docs/js/features/common/custom-request-config.mdx
> +By default, the SAP Cloud SDK uses `axios` as HTTP client for executing requests.
```suggestion
By default, the SAP Cloud SDK uses `[axios](https://github.com/axios/axios)` as an HTTP client backend for executing requests.
```

2021-04-12 17:40 UTC, artemkovalyov commented on docs/js/features/common/custom-request-config.mdx
> +The example below demonstrates how to indicate the response data type, which is typically used when downloading a file from an endpoint.
```suggestion
The example below demonstrates how to configure the response data type, which is typically used when downloading a file from an endpoint.
```

2021-04-12 17:40 UTC, artemkovalyov commented on docs/js/features/common/custom-request-config.mdx
> +In addition to basic options like `url` and `headers`, being generated by the SAP Cloud SDK under the hood, you are also allowed to provide custom request configuration, which is then used as custom
```suggestion
The SAP Cloud SDK derives and configures most of the request options like `url`, `headers`, and others for you. In certain cases passing additional options to `axios` might be required. To achieve this you can provide a custom request configuration that will be passed down to `axios` and in turn, applied to your requests down with the SAP Cloud SDK.
```

2021-04-12 17:40 UTC, artemkovalyov commented on docs/js/features/odata/execute-odata-request.mdx
>  Executing the example request above against a destination with URL `https://my.s4-system.com` would then execute the request against something like this: `https://my.s4-system.com/my/custom/service/p
```suggestion
Executing the example request above against a destination with URL `https://my.s4-system.com` would result in a request against URI like this: `https://my.s4-system.com/my/custom/service/path/MyEntity`.
```

2021-04-12 17:41 UTC, artemkovalyov commented
> @artemkovalyov, currently all pipelines failed to install vale with 403, is it a known issue?

Nope, this is new. I'll take a look. Maybe some version update happened.

2021-04-12 17:46 UTC, artemkovalyov commented
@jjtang1985 , I understand that we manage headers, but having an option to add or override them makes sense to me. You often might require additional headers or overriding the ones set by SDK. Can we have smth like merging header objects with spread operator or similar? This is of course "Know what you're doing" type of thing but might be super useful for workarounds as proven by Java team.

2021-04-12 21:54 UTC, artemkovalyov commented
@jjtang1985 , I think after my PRs are merged this build should succeed.

2021-04-13 06:29 UTC, jjtang1985 commented
> I understand that we manage headers, but having an option to add or override them makes sense to me. You often might require additional headers or overriding the ones set by SDK. Can we have smth like merging header objects with spread operator or similar? This is of course "Know what you're doing" type of thing but might be super useful for workarounds as proven by Java team.

@artemkovalyov , custom headers definitely makes sense. Since we have this [API](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-odata-request/#setting-custom-request-headers), I would not allow users to do it in the custom options. If so, it will confuse users and ourselves, as you have to decide which configuration wins when reaching conflicts.

2021-04-13 11:13 UTC, marikaner requested changes
@jjtang1985 I left some minor suggestions.

2021-04-13 11:13 UTC, marikaner commented on docs/js/features/common/custom-request-config.mdx
> +By default, the SAP Cloud SDK uses `[axios](https://github.com/axios/axios)` as an HTTP client backend for executing requests.
```suggestion
By default, the SAP Cloud SDK uses `[axios](https://github.com/axios/axios)` as an HTTP client for executing requests.
```

2021-04-13 11:13 UTC, marikaner commented on docs/js/features/common/custom-request-config.mdx
> +To achieve this you can provide a custom request configuration that will be passed down to `axios` and in turn, applied to your requests down with the SAP Cloud SDK.
```suggestion
To achieve this you can provide a custom request configuration that will be passed down to `axios`.
```

2021-04-13 11:13 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +Executing the example request above against a destination with URL `https://my.s4-system.com` would result in a request against URI like this: `https://my.s4-system.com/my/custom/service/path/MyEntit
```suggestion
Executing the example request above against a destination with URL `https://my.s4-system.com` would result in a request against something like this: `https://my.s4-system.com/my/custom/service/path/MyEntity`.
```

2021-04-13 11:13 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +Executing the example request above against a destination with URL `https://my.s4-system.com` would result in a request against URI like this: `https://my.s4-system.com/my/custom/service/path/MyEntit
```suggestion
Executing the example request above against a destination with URL `https://my.s4-system.com` would result in a request against a URL like this: `https://my.s4-system.com/my/custom/service/path/MyEntity`.
```

2021-04-13 11:13 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +Executing the example request above against a destination with URL `https://my.s4-system.com` would result in a request against URI like this: `https://my.s4-system.com/my/custom/service/path/MyEntit
I left two suggestions, your choice ;) You can also adjust it differently, what is important to me is the missing "a".

2021-04-13 11:13 UTC, marikaner commented on docs/js/features/odata/execute-odata-request.mdx
> +<CustomRequestConfigNote />
As you have touched this file consider fixing the warnings below.

2021-04-13 11:16 UTC, marikaner approved these changes
As discussed, only minor findings, feel free to merge when you are ready.

2021-04-13 11:22 UTC, merged