Guide About Business Rules Client Lib
SAP/cloud-sdk pull request #260
Opened 2021-05-06 10:12 UTC by Johannes-Schneider

## What Has Changed?

This PR adds a guide on how to use the pre-generated Business Rules client library.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-05-06 10:13 UTC, Johannes-Schneider commented on docs/java/features/rest/clients/btp-business-rules-rest-api.mdx
> +      <!-- Business Rules API is supported in ver 3.45.0 of the SDK and above. Please, always use the latest version -->
Wait for this version to hit Maven Central before merging this PR.

2021-05-07 14:43 UTC, artemkovalyov requested changes
I added some suggestions. It's clear the docs are copied from Workflow and in many cases, it still seems to require an update. Or do I miss smth? Check my initial notes.

2021-05-07 14:43 UTC, artemkovalyov commented on docs/java/features/rest/clients/btp-business-rules-rest-api.mdx
> +This ensures that the `VCAP_SERVICES` environment variable of the CF application gets enhanced with an additional entry containing the connection details of the newly bound workflow service.
```suggestion
This ensures that the `VCAP_SERVICES` environment variable of the CF application gets enhanced with an additional entry containing the connection details of the newly bound SAP BTP Business Rules service.
```

2021-05-07 14:43 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +Once the app is bound to the workflow service (here in our example) and app deployment has finished, go to your CF space and navigate to `Services\Instances and Subscriptions`.
```suggestion
Once the app is bound to the SAP BTP Business Rules service (here in our example) and app deployment has finished, go to your CF space and navigate to `Services\Instances and Subscriptions`.
```

2021-05-07 14:43 UTC, artemkovalyov commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
>  Click on the service instance name, for instance `my-workflow`, in the upcoming screen you should see the headline `Service Instance: my-workflow - Referencing Apps`.
```suggestion
Click on the service instance name, in our case `my-business-rules`, in the upcoming screen you should see the headline `Service Instance: my-business-rules - Referencing Apps`.
```

2021-05-10 13:37 UTC, Johannes-Schneider commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
> +Once the app is bound to the workflow service (here in our example) and app deployment has finished, go to your CF space and navigate to `Services\Instances and Subscriptions`.
This is in the `scp-workflow-rest-api` documentation, so here the "workflow service" is actually correct.

2021-05-10 13:37 UTC, Johannes-Schneider commented on docs/java/features/rest/clients/scp-workflow-rest-api.mdx
>  Click on the service instance name, for instance `my-workflow`, in the upcoming screen you should see the headline `Service Instance: my-workflow - Referencing Apps`.
Same as above.

2021-05-12 04:57 UTC, artemkovalyov commented on docs/java/features/rest/clients/btp-business-rules-rest-api.mdx
> +After you created an SDK-based Java app, you can invoke the SAP BTP Business Rules REST API in your business logic.
```suggestion
After you created an SAP Cloud SDKSDK-based Java app, you can invoke the SAP BTP Business Rules REST API in your business logic.
```

2021-05-12 04:58 UTC, artemkovalyov approved these changes
LGTM

2021-05-12 05:44 UTC, artemkovalyov commented on docs/java/features/rest/clients/btp-business-rules-rest-api.mdx
> +After you created an SDK-based Java app, you can invoke the SAP BTP Business Rules REST API in your business logic.
```suggestion
After you created an SAP Cloud SDK-based Java app, you can invoke the SAP BTP Business Rules REST API in your business logic.
```

2021-05-12 06:01 UTC, merged