[OData V2] Document function import calls in batch change sets
SAP/cloud-sdk pull request #261
Opened 2021-05-06 10:40 UTC by Emdee89

## What Has Changed?

Mentioning the availability of `addFunctionImport(...)` for the OData V2 batch functionality.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-05-06 14:53 UTC, artemkovalyov requested changes
I tried to improve the readability. Take a look.

2021-05-06 14:53 UTC, artemkovalyov commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +Multiple single requests (like `createBusinessPartnerAddress`) can be wrapped into so-called changesets.
```suggestion
Multiple single requests like `createBusinessPartnerAddress` and others can be wrapped into an [OData BATCH  ChangeSet](https://www.odata.org/documentation/odata-version-2-0/batch-processing/). 
```

2021-05-06 14:53 UTC, artemkovalyov commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +Changesets are meant to wrap transactional requests together.
```suggestion
OData BATCH ChangeSets are meant to wrap transactional requests together for better performance.
```

2021-05-06 14:53 UTC, artemkovalyov commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +Additionally, changesets can also contain function import calls (use the method `addFunctionImport(...)`).
```suggestion
OData Function Import can be also used inside of OData Batch ChangeSets, for that use the method `addFunctionImport(...)`.
```

2021-05-07 11:06 UTC, artemkovalyov approved these changes
LGTM

2021-05-07 11:24 UTC, Emdee89 commented
@artemkovalyov any idea why the build fails? The vale linter did not find anything in type-safe-client-odata-v2.mdx, which is the only changed file in this PR.

2021-05-07 11:45 UTC, artemkovalyov commented
@Emdee89 , my assumption is that with your fork the PR builds based on it. And your fork is not updated with the latest state of the original repos. Might that be the case? I think the errors it produces were fixed alreaady.

2021-05-07 11:45 UTC, artemkovalyov commented
Can we try with an updated or new fork to test it?

2021-05-07 13:33 UTC, Emdee89 commented
@MatKuhr Sure, but the file I am changing is not included in the vale output. So no idea what I need to fix in my file.

2021-05-07 15:06 UTC, MatKuhr commented
> Sure, but the file I am changing is not included in the vale output. So no idea what I need to fix in my file.

Nothing. That means the main branch should also have the same issue.

2021-05-12 08:25 UTC, merged