Note about OData upsert
SAP/cloud-sdk pull request #264
Opened 2021-05-06 19:18 UTC by artemkovalyov

## What Has Changed?

A note on upserting

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-05-06 19:19 UTC, artemkovalyov commented
@newtork , this a promised note about UPSERT that should link to your example of executing it with Generic OData client.

2021-05-11 14:51 UTC, MatKuhr requested changes

2021-05-11 14:51 UTC, MatKuhr commented on docs/java/features/odata/type-safe-client-odata-v4.mdx
> +You can implement `UPSERT` by combining `UPDATE` and `CREATE` requests mentioned above together with custom logic required to handle the upserting.
For that the user needs to know whether or not the entity already exists. I think UPSERT is instead achieved by simply always using `updateXyz`. @newtork correct me if I am wrong here.

2021-05-11 14:51 UTC, MatKuhr commented on docs/java/features/odata/type-safe-client-odata-v4.mdx
> +If `UPSERT` is mission critical for you application, you can use our Generic OData client to construct an `UPSERT` call yourself by example.
> by example

where is the example?

2021-05-12 04:52 UTC, artemkovalyov commented
@newtork , do you still plan to provide a workaround? I assume even POST would work as you can choose a method when dealing with a generic client?

@MatKuhr, if you'd like you can help @newtork with that. I'll leave the PR open and link to an example when it's ready.

2021-05-12 08:09 UTC, closed without merging