Java Release Notes 3.45.0
SAP/cloud-sdk pull request #279
Opened 2021-05-17 17:57 UTC by MatKuhr

## What Has Changed?

See title

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-05-17 18:55 UTC, newtork commented on docs/java/release-notes.mdx
> +- Using `null` in OData v2 filter expressions does no longer lead to a `NullPointerException` upon executing the request.
```suggestion
- Using `null` in OData v2 filter expressions does no longer lead to a `NullPointerException` when executing the request.
```

2021-05-17 18:55 UTC, newtork commented on docs/java/release-notes.mdx
> +- Fix an edge case where `BigDecimal` values where not serialised correctly in OData V2 requests.
```suggestion
- Fix an edge case where `BigDecimal` values where not serialized correctly in OData V2 requests.
```

2021-05-18 07:18 UTC, MatKuhr commented on docs/java/release-notes.mdx
> +- Fix an edge case where `BigDecimal` values where not serialised correctly in OData V2 requests.
> serialization (US spelling) or serialisation (UK spelling)

I always wondered which of the two is correct, seems like both are :D

2021-05-20 09:16 UTC, Johannes-Schneider requested changes

2021-05-20 09:16 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +  ```
```suggestion
  ```java
```

2021-05-20 09:20 UTC, Johannes-Schneider approved these changes

2021-05-20 09:21 UTC, merged