doc: Add workflow documentation
SAP/cloud-sdk pull request #294
Opened 2021-05-28 11:50 UTC by marikaner

## What Has Changed?

I added a simple use case for the workflow usage.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-05-28 14:26 UTC, florian-richter requested changes
Please consider my points as suggestions.

2021-05-28 14:26 UTC, florian-richter commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +It is technically separated into two services per environment: the Inbox API (OData) and the Workflow API (OpenAPI).
I think a bulleted list looks nicer after a colon.

2021-05-28 14:26 UTC, florian-richter commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +The first SAP Cloud SDK pregenerated OpenAPI client is for the OpenAPI Workflow API.
Open**API** client is for the Open**API** Workflow **API**

At least the second `OpenAPI` could be removed as it's implied...

2021-05-28 14:26 UTC, florian-richter commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +For this exemplary use case, assume a simple workflow definition:
```suggestion
For this example, assume following workflow definition:
```

2021-05-28 14:26 UTC, florian-richter commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +The following use case shows how to initiate a workflow, retrieve its tasks, complete a task and retrieve the execution logs for this workflow.
```suggestion
The use case shows how to initiate a workflow, retrieve its tasks, complete a task and retrieve the execution logs.
```

2021-05-28 14:26 UTC, florian-richter commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +The function above returns an instance of a task, that looks as follows:
```suggestion
The function above returns an instance of a task.
```

2021-05-28 14:26 UTC, florian-richter commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +The form to fulfill this task has one boolean field, `approve`:
```suggestion
The form to fulfill this task has one boolean field, `approve`.
```

2021-05-28 14:26 UTC, florian-richter commented on sidebars.js
> +                label: 'Pre-generated Clients',
```suggestion
                label: 'Pregenerated Clients',
```

2021-05-28 15:40 UTC, marikaner commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +The form to fulfill this task has one boolean field, `approve`:
I like it if there is a connection to images or code. Without the colon I would have to reference it in the text somehow. Why do you think a fullstop is better here?

2021-05-28 15:44 UTC, marikaner commented on docs/js/features/openapi/execute-openapi-request.mdx
> +  - REST
I can also change it back. Somehow "rest" just didn't make sense to me. I don't know too exactly what this is relevant for anyways.

2021-05-28 16:03 UTC, marikaner commented on sidebars.js
> +                label: 'Pre-generated Clients',
Fixed it, I will also add a rule in the next PR

2021-05-28 16:04 UTC, marikaner commented on docs/js/features/openapi/generate-openapi-client.mdx
> +description: How to generate a client from a service definition.
I reverted my change, I don't think it is important.

2021-05-28 16:04 UTC, marikaner commented on docs/js/features/openapi/pre-generated-clients/workflow.mdx
> +description: This article describes what the Workflow API for Cloud Foundry is and how
```suggestion
description: This article describes what the Workflow API for Cloud Foundry is and how to consume it with the SAP Cloud SDK.
```

2021-05-28 16:06 UTC, marikaner commented on docs/js/features/openapi/pregenerated-clients/workflow.mdx
> +description: This article describes what the Workflow API for Cloud Foundry is and how
```suggestion
description: This article describes what the Workflow API for Cloud Foundry is and how to consume it with the SAP Cloud SDK.
```

2021-05-31 14:51 UTC, florian-richter approved these changes
LGTM

2021-05-31 14:51 UTC, florian-richter commented on docs/js/features/openapi/overview.mdx
> +- You'll benefit from less code boilerplate, and better developer experience.
```suggestion
- You'll benefit from less code boilerplate and better developer experience.
```
I think the Oxford comma is not needed if there are only 2 options, right?

2021-05-31 14:51 UTC, florian-richter commented on docs/js/features/openapi/pregenerated-clients/workflow.mdx
> +:::
```suggestion
:::note Prerequisites

The following documentation explains how to use the pregenerated client for:

- An existing instance of the SAP Workflow service
- A user, who has the necessary roles to make the requests
- An existing workflow definition that contains one simple user task

To learn how to set up your environment for the SAP Workflow service, see the [Workflow service documentation](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/fc3d44872c354742afd672aa8d9c16b4.html).

:::
```

2021-05-31 21:10 UTC, jjtang1985 approved these changes
LGTM

2021-06-01 07:17 UTC, merged