Add release notes for Java SDK 3.46.0
SAP/cloud-sdk pull request #300
Opened 2021-05-31 11:55 UTC by Emdee89

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-05-31 12:07 UTC, newtork approved these changes

2021-06-01 11:53 UTC, artemkovalyov requested changes
Mostly LGTM, but some minors need to be tackled.

2021-06-01 11:53 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  **Caution:** The service introduced some intended **breaking changes** with the latest update which are now, in consequence, also present in the VDM.
```suggestion
- We updated the (OData V2) Trial Balance - Read (`C_TRIALBALANCE_CDS`) VDM to the [newest release 2105 of SAP S/4HANA Cloud](https://news.sap.com/2021/05/sap-s4hana-cloud-release-2105/)
  
  **Caution:** The service introduced some intended **breaking changes** with the latest update which are now, in consequence, also present in the type-safe client (VDM) by the SDK.
```

2021-06-01 11:53 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  Check out the full documentation of the feature for more information.
I couldn't find the related docs. Can we provide a link here?

2021-06-01 13:12 UTC, Emdee89 commented on docs/java/release-notes.mdx
> +  Check out the full documentation of the feature for more information.
@artemkovalyov I am afraid this docu is still in progress, see https://github.com/SAP/cloud-sdk/pull/284

2021-06-01 14:29 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  Check out the full documentation of the feature for more information.
Yep, I found the PR. We can see if we can merge it by Thu.

2021-06-03 09:23 UTC, MatKuhr commented
Could you please also merge #284 when merging this?

2021-06-03 09:24 UTC, MatKuhr commented on docs/java/release-notes.mdx
> +  Check out the full documentation of the feature for more information.
yeah if we merge the PR first we can link to the docs here.

2021-06-03 14:38 UTC, artemkovalyov approved these changes
LGTM

2021-06-04 07:47 UTC, merged