Update Info about community calls
SAP/cloud-sdk pull request #328
Opened 2021-06-14 14:21 UTC by KavithaSiva

## What Has Changed?

I have explicitly added the series registration link inside the [upcoming dates section.](https://sap.github.io/cloud-sdk/docs/community/community-call#upcoming-dates-2020). Also, added in a word to say that we would enable registering for individual sessions soon.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x ] You tested if the documentation still builds (`npm run build`)
- ~[x] You verified all new and changed links still work (changing the `id` or name of a file can break links)~
- ~[x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~

2021-06-14 14:25 UTC, KavithaSiva commented
@artemkovalyov I decided to add the registration link explicitly again to the upcoming session section in our community call page. Was there any other specific place in the documentation where you wanted to advertise our community call?

2021-06-14 15:16 UTC, artemkovalyov approved these changes
I think a much better place would be a landing page. This wouldn't harm but I don't expect much traction from here. Let's also set up a reminder to remove it after the call.

2021-06-14 15:18 UTC, artemkovalyov commented
> @artemkovalyov I decided to add the registration link explicitly again to the upcoming session section in our community call page and to the OpenAPI generator page of JS.
> 
> Was there any other specific place in the documentation where you wanted to advertise our community call?

I think a landing page banner is the best place. We can add an extra section there. Would be nice to have redesigned a bit to have a permanent spot for future invitations but we have what we have at the moment.

2021-06-14 15:39 UTC, marikaner requested changes
I know most of the text was already there, but I applied some of the learnings from the technical writing workshop here ;)
Please consider my suggestions.

2021-06-14 15:39 UTC, marikaner commented on docs/community/community-call.mdx
> +In this series of calls for SAP Community, we will give you regular updates on the latest releases of the SAP Cloud SDK, its roadmap and topics around extensibility of SAP Business Suite, SAP S/4HANA
There is a warning from vale for this sentence. If I am honest I don't fully understand the second half of this sentence - is it about providing the roadmap for S/4HANA?
Please convert this to an unordered list as this is the recommended way to treat lists.
I added the in-depth part from below and actually removed the last sentence, because in my eyes it was just empty marketing talk ;) Feel free to adjust as you like.
```suggestion
In this series of calls for SAP Community you will learn about:
- the latest releases of the SAP Cloud SDK
- in-depth focus topics around the SDK
- the SDK's roadmap
```

2021-06-14 15:39 UTC, marikaner commented on docs/community/community-call.mdx
>  The call series will be conducted by the SAP Cloud SDK development and product management team.
Use present tense
```suggestion
The call series is conducted by the SAP Cloud SDK development and product management team.
```

2021-06-14 15:39 UTC, marikaner commented on docs/community/community-call.mdx
> +We will introduce the SAP Cloud SDK and cover its latest updates along with a deep dive on the topic chosen for the day.
We don't really "introduce" the SDK, those are rather updates for people who already know the SDK on a high level.
The fact that we cover the latest updates was already mentioned above. I would remove this sentence and add it to the list above.

2021-06-14 15:39 UTC, marikaner commented on docs/community/community-call.mdx
> +On this page, you can find the schedule as well as recordings of past sessions below.
```suggestion
On this page, you can find the schedule as well as recordings of past sessions.
```

or

```suggestion
On this page, you can find the schedule as well as recordings of past sessions (see below).
```

2021-06-14 15:39 UTC, marikaner commented on docs/community/community-call.mdx
> +We are working on enabling registering for individual sessions instead of a series, we will keep you posted on the progress.
```suggestion
We are working on enabling registration for individual sessions instead of a series, we will keep you posted on the progress.
```

2021-06-14 15:39 UTC, marikaner commented on docs/js/features/openapi/generate-openapi-client.mdx
> +There is an upcoming community call on using the OpenAPI Client Generator of SAP Cloud SDK for JS on June 23rd 2020.
```suggestion
There is an upcoming community call on using the OpenAPI client generator of the SAP Cloud SDK for JS on June 23rd 2020.
```

2021-06-15 10:58 UTC, KavithaSiva commented on docs/community/community-call.mdx
> +We will introduce the SAP Cloud SDK and cover its latest updates along with a deep dive on the topic chosen for the day.
Yes, you are right, removing this line.

2021-06-15 11:04 UTC, KavithaSiva commented
> I know most of the text was already there, but I applied some of the learnings from the technical writing workshop here ;)
> Please consider my suggestions.

Thanks for the detailed review Marika.

2021-06-16 08:02 UTC, merged

2021-06-16 14:47 UTC, MatKuhr commented on docs/community/community-call.mdx
> +- The SDK's roadmap
@artemkovalyov @KavithaSiva something is off with our build pipeline I think. These changes should cause the pipeline to fail, because the Value check should fail, because `The SDK` is not allowed. It must be `the SAP Cloud SDK` instead.

In fact it causes subsequent PR builds to fail, but I am clueless why Vale didn't pick up on this already in this PR. 
@KavithaSiva could you fix it in a follow up PR?