Documentation Count
SAP/cloud-sdk pull request #36
Opened 2020-11-27 13:37 UTC by FrankEssenberger

Here the documentation for the `count` method in getAll requests.

2020-11-27 14:13 UTC, jjtang1985 requested changes
Please consider my comments.

2020-11-27 14:13 UTC, jjtang1985 commented on docs/js/features/odata/common/operations/count.mdx
> +BusinessPartner.requestBuilder().count().getAll();
```suggestion
BusinessPartner.requestBuilder().getAll().count();
```
I think the `count()` will return `CountRequestBuilder`, which cannot call `getAll()` any more.

2020-11-27 14:13 UTC, jjtang1985 commented on docs/js/features/odata/common/operations/count.mdx
> +BusinessPartner.requestBuilder().count().getAll();
Same as the previous one, `count()` is only valid at the end of the chain.
Also, `top()` and `skip()` are only possible under the `getAll()` context.

2020-11-27 14:13 UTC, jjtang1985 commented on docs/js/features/odata/common/operations/count.mdx
> +Note that we currently do not support the usage of count within a filter condition as described in the [OData v4 specifiation](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conve
Question: since this file is under the common folder, I assume it will be shared for both v2 and v4 pages.
The limit is only about v4, should we then consider moving it to v4 page?

2020-12-01 17:16 UTC, FrankEssenberger commented on docs/js/features/odata/common/operations/count.mdx
> +Note that we currently do not support the usage of count within a filter condition as described in the [OData v4 specifiation](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conve
I move the sentence regarding v4 out to the v4 file.

2020-12-03 15:05 UTC, artemkovalyov reviewed
Check if my suggestions make sense

2020-12-03 15:05 UTC, artemkovalyov commented on docs/js/features/odata/common/operations/count.mdx
> +As defined in the OData spec `count` is not affected by `top`, `skip` and `orderBy`.
```suggestion
As defined in the OData spec `count` is not affected by `top`, `skip`, and `orderBy`.
```

2020-12-03 15:05 UTC, artemkovalyov commented on docs/js/features/odata/common/operations/count.mdx
> +As defined in the OData spec `count` is not affected by `top`, `skip` and `orderBy`.
Getting nerdy with Oxford comma:)

2020-12-03 15:05 UTC, artemkovalyov commented on docs/js/features/odata/common/operations/count.mdx
> +If you include these methods in a count request they will be ignored by the SDK.
```suggestion
:::note "top() and skip() are ignored for count
If you include these methods in a count request they will be ignored by the SDK.
```

2020-12-03 15:05 UTC, artemkovalyov commented on docs/js/features/odata/common/operations/count.mdx
> +If you include these methods in a count request they will be ignored by the SDK.
A bit verbosity for attention.

2020-12-03 15:05 UTC, artemkovalyov commented on docs/js/features/odata/odata-v4-client.mdx
> +  Note that we currently do not support the usage of count within a filter condition as described in the [OData v4 specifiation](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-con
```suggestion
:::note Count within a filter not supported
Note that we currently do not support the usage of count within a filter condition as described in the [OData v4 specifiation](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheCountofaCollection).
:::
```

2020-12-03 15:05 UTC, artemkovalyov commented on docs/js/features/odata/odata-v4-client.mdx
> +  Note that we currently do not support the usage of count within a filter condition as described in the [OData v4 specifiation](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-con
I would also make it an admonition.

2020-12-03 15:36 UTC, jjtang1985 approved these changes

2020-12-03 16:44 UTC, FrankEssenberger commented on docs/js/features/odata/common/operations/count.mdx
> +As defined in the OData spec `count` is not affected by `top`, `skip` and `orderBy`.
really this is correct? Die spinnen die briten. But if you say so.

2020-12-03 16:50 UTC, artemkovalyov approved these changes
Thanks

2020-12-03 16:50 UTC, merged