Extend caching docu on cache filters
SAP/cloud-sdk pull request #369
Opened 2021-07-09 11:05 UTC by Emdee89

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-07-13 12:32 UTC, Emdee89 commented on docs/java/features/resilience/caching.mdx
> +CacheFilter tenantFilter = ( configuration, cacheKey, cacheEntry ) -> cacheKey.getTenantId().isDefined() && cacheKey.getTenantId().get().equals("tenant1");
I know that this can be abbreviated with `keyMatchesTenant(...)`, but I find this good enough to illustrate how to create your own custom filter.

2021-07-13 14:54 UTC, Johannes-Schneider approved these changes
Very detailed explanation with a lot of examples - I like it!

2021-07-13 20:06 UTC, artemkovalyov requested changes
Looks good. I like the plentitude of examples!
Please, check minor suggestions. I  also believe committing a package-lock.json from your local env is not the best idea in this case.
Can you remove it?

2021-07-13 20:06 UTC, artemkovalyov commented on docs/java/features/resilience/caching.mdx
> +If you need fine-grained influence on which cache entries to remove, you may write your custom `CacheFilter`.
```suggestion
If you need fine-grained control over invalidating of cache entries, you may write your custom `CacheFilter`.
```

2021-07-14 07:14 UTC, Emdee89 commented
@Johannes-Schneider @artemkovalyov Pls review again shortly

2021-07-14 07:21 UTC, Johannes-Schneider reviewed
Minor suggestion.

2021-07-14 07:21 UTC, Johannes-Schneider commented on docs/java/features/resilience/caching.mdx
> +If you need fine-grained control over invalidating of cache entries, you may write your custom `CacheFilter`.
I think we should stick with one term for "clearing"/"invalidating" cache entries.

```suggestion
If you need fine-grained control over which cache entries to clear, you may write your custom `CacheFilter`.
```

2021-07-14 12:31 UTC, Johannes-Schneider approved these changes
LGTM.

2021-07-14 12:40 UTC, merged