A starter for the K8s docs
SAP/cloud-sdk pull request #374
Opened 2021-07-14 15:40 UTC by artemkovalyov

## What Has Changed?

@tomfrenken, please, continue here

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-07-23 08:36 UTC, artemkovalyov commented
Amazing, I'll try to take a look today.

2021-07-27 15:45 UTC, florian-richter reviewed
Please check the vale findings 😊 I fixed some via suggestions below, but you should go through the full list.

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +# How to migrate a CloudFoundry application to a Kubernetes Cluster
```suggestion
# How to Migrate a CloudFoundry Application to a Kubernetes Cluster
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Roughly, it comprises of three steps:
```suggestion
It comprises of three steps:
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- [Short PoC Environment](#short-poc-environments)
There is no header for this list...

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +  - If you only do a short PoC this kind of environment will be sufficient for you. But it is not recommended for future use or long running PoCs.
```suggestion
  - If you only do a short PoC this kind of environment will be sufficient for you. 
    But it is not recommended for future use or long running PoCs.
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +  - For staging environments we will take a look at a way to create and bind services manually. This is primarily meant to try out different service setups.
```suggestion
  - For staging environments we will take a look at a way to create and bind services manually. 
    This is primarily meant to try out different service setups.
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- [kubectl](https://kubernetes.io/docs/tasks/tools/)
```suggestion
- [`kubectl`](https://kubernetes.io/docs/tasks/tools/)
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +### Create and bind services
```suggestion
### Create and Bind Services
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +If you want to create and bind _new_ services, simply deploy a hello-world app to CloudFoundry and then bind services to this app.
```suggestion
If you want to create and bind _new_ services, you can deploy a `hello-world` app to CloudFoundry and then bind services to this app.
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- [smctl](https://github.com/Peripli/service-manager-cli)
```suggestion
- [`smctl`](https://github.com/Peripli/service-manager-cli)
```
Same applies below...

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Next you need to login to the service manager ctl and register your cluster
```suggestion
Next you need to login to the service manager control and register your cluster
```
Actually Im not sure if this is the right word for the abbreviation

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +With the service operator, all services are deployed via yaml files, which makes the management of services a lot easier in the longterm.
```suggestion
With the service operator, all services are deployed via YAML files, which makes the management of services a lot easier in the long term.
```

2021-07-27 15:45 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Notice that we used `imagePullSecrets`, which is using the `regcred` secret, the `regcred` secret contains our own registry credentials that we previously bound as a secret, you can do this either by
```suggestion
Notice that we used `imagePullSecrets`, which is using the `regcred` secret, the `regcred` secret contains our own registry credentials that we previously bound as a secret, you can do this either by writing a `secret.yml` or directly in the CLI (though this will be in your `.bashrc`) like this:
```

2021-07-27 16:30 UTC, tomfrenken commented
Thanks for the suggestions, I'll look into it as well as the Vale findings 👍

2021-07-28 11:00 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Save the `service-manager-credentials.txt` somewhere save, as you will need it later on, especially the username and password.
```suggestion
The `service-manager-credentials.txt` is sensitive data, keep it in a safe place. You will need it later on, especially the `username` and `password`.
```

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To make the services available to us we need to register the service broker, in CloudFoundry called `Service Manager` to the service catalog `svcat`.
```suggestion
To make the services available in the Kubernetes cluster we need to register a service broker, in the SAP BTP Cloud Foundry.  It's named `Service Manager` and is available in the service catalog `svcat`.
```

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To do this with the `Service Manager`, we just need to install the service-broker-proxy with the following code:
```suggestion
To access the `Service Manager` on BTP CF, we need to install the `service-broker-proxy` in our K8s cluster. Here's how you do it:```

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +After installing the proxy you have to wait a few seconds until the it is fully operational.
```suggestion
After installing the proxy you have to wait a few seconds until it is fully operational.
```

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Once the proxy is working use `svcat marketplace`, all CloudFoundry services should now be listed.
```suggestion
Once the proxy is up, try running `svcat marketplace`, all the services available on SAP BTP CF should now be listed.
```

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Once the proxy is working use `svcat marketplace`, all CloudFoundry services should now be listed.
Where do you run this `svcat`? In your K8s console? Or on your local machine? I didn't get this. Do you need `kubectl` to make a call?

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Notice how `destination-service` is just the name we give this particular service instance, it could be anything.
```suggestion
Notice how `destination-service` is just the name we give to this particular service instance, it could be anything.
```

2021-07-28 11:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally we just need to bind the services to make them available to our application.
```suggestion
Finally, we just need to bind the services to make them available to our application.
```

2021-07-28 11:42 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Once the proxy is working use `svcat marketplace`, all CloudFoundry services should now be listed.
`svcat` has a server-side (which runs in the cluster) and a client-side, when we use `svcat` on our local machine, we call the service catalog inside the cluster. This question is probably answered when clicking the `svcat` link in the prerequisites link, it contains installation information for the cluster as well as the local CLI.

2021-08-02 16:27 UTC, artemkovalyov reviewed
Please, take a look at my suggestions. We can bundle most of them in one commit.
Where clarity was missing I left comments.

2021-08-02 16:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally download the CA certificate with the following line:
```suggestion
The private key and public certificate are also stored in our TLS secret, use the previous code snippet to retrieve it from the secret and save them in separate files.
Finally, download the CA certificate with the following line:
```

2021-08-02 16:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- Our public certificate
Is it a public cert or a key?

2021-08-02 16:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally download the CA certificate with the following line:
Same question here, a public cert or a key?

2021-08-02 16:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +5. Create a secret that contains credentials which have access to the docker image that the `Connectivity Proxy` is using.
```suggestion
5. Create a secret that contains credentials to access to the docker image that the `Connectivity Proxy` is using.
```

2021-08-02 16:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +For the specific content of the configuration refer to the [configuration guide](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?spaceKey=NGP&title=Configuration+guide).
```suggestion
6. Create a `values.yml` containing the configuration that suits your desired operational mode, for the available operational modes refer to the [documentation](https://wiki.wdf.sap.corp/wiki/display/NGP/Operational+modes#Operationalmodes-Singletenantinatrustedenvironment).
For the specific content of the configuration refer to the [configuration guide](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?spaceKey=NGP&title=Configuration+guide).
```

2021-08-02 16:27 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +7. For your application to reach On-Premise destinations, it needs the proxy settings, currently these have to be added manually to the secret containing the service binding.
```suggestion
7. For your application to reach On-Premise destinations, it needs the proxy settings, currently, these have to be added manually to the secret containing the service binding.
```

2021-08-03 15:05 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To make the services available in the Kubernetes cluster we need to register a service broker, in the SAP BTP Cloud Foundry named `Service Manager`, to the service catalog `svcat`.
We register the broker, which is called Service Manager in SAP BTP,  to the service catalog, which is called `svcat`, what part of the sentence is confusing to you exactly?

2021-08-03 15:16 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To make the services available in the Kubernetes cluster we need to register a service broker, in the SAP BTP Cloud Foundry named `Service Manager`, to the service catalog `svcat`.
I thought `svcat` is a CLI to access the catalog. Or is it both? https://svc-cat.io/docs/cli/

2021-08-03 15:26 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To make the services available in the Kubernetes cluster we need to register a service broker, in the SAP BTP Cloud Foundry named `Service Manager`, to the service catalog `svcat`.
I updated the suggestion based on my understanding

2021-08-03 15:32 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To make the services available in the Kubernetes cluster we need to register a service broker, in the SAP BTP Cloud Foundry named `Service Manager`, to the service catalog `svcat`.
I think you are right in that `svcat` is the service catalog's cli, but it is kind of both since its a literal abbreviation for Service Catalog, I guess that's where the confusion stemmed from - thanks for the adapted suggestion 👍

2021-08-03 15:37 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Next you need to login to the service manager control and register your cluster
the service manager control (`smctl`) is the command-line tool that is used in the code block below this, I guess when the user clicks through the `required` links they will eventually end up at their docs page, that's why I didn't specify it further, I guess I could add "(`smctl`) into the sentence to clarify it

2021-08-03 15:52 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +For this example, we will take a look at our [e2e Kubernetes app](https://github.tools.sap/cloudsdk/k8s-e2e-app) app.
Yeah I agree, I'm thinking about our GH samples repository

2021-08-03 19:07 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Next you can see in the `spec.tls.hosts` part that we expose 2 routes, the first one is just our default domain, it is important that this is our first domain, since the first domain is only allowed
Indeed, I should just use domains in this case I guess.

2021-08-03 19:23 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- Our public certificate
it's a certificate

2021-08-03 19:24 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally download the CA certificate with the following line:
same as previous, it's actually a public certificate

2021-08-03 20:09 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally download the CA certificate with the following line:
Actually reading further into it, for some reason, Gardner calls it public certificate, however everyone else calls it public key 🤔

2021-08-03 20:13 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally download the CA certificate with the following line:
*reading even further into it, the difference is that the public certificate contains more than just the public key, but also the signature by the CA, therefore public certificate is true in this case

2021-08-03 20:17 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +In this how-to, we will show step by step how to migrate an application from CloudFoundry to Kubernetes.
Agreed, however, I think it fits well at the start, I'll use your suggestion on some of the other occurences

2021-08-04 00:29 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +You can now use the service account in your automation to connect to the cluster:
I'm not 100% sure what you are referring to, but I think you mean the technical user? In that case its 2 different technical users, one is a technical user for the docker registry, another one is a technical user for the Kubernetes cluster (doesn't matter if its Gardener or plain Kubernetes)

2021-08-04 00:42 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +If you use the PoC environment just save the binding as a secret, use the below example, otherwise you need to retrieve the binding first and then format it in `JSON` to save it as a secret, for that
I added that I meant the code snipped that was used in the previous step to the description now.

2021-08-04 00:45 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +You can now use the service account in your automation to connect to the cluster:
Regarding the Docker repository, it doesn't matter if its the artifcatory or public Docker repo, a technical user is required either way

2021-08-04 00:51 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +You can now use the service account in your automation to connect to the cluster:
I changed the phrasing from Docker image to container image now though, since theoretically Kubernetes can also use all other kinds of container images besides Docker.

2021-08-08 10:26 UTC, artemkovalyov commented
Are we merging this, @tomfrenken ?

2021-08-09 07:42 UTC, florian-richter requested changes
Seems like the vale scan did not really run successfully on the whole file. So maybe check if you can run it locally and go through to fix all the findings. Also I found it only somewhat helpful because some dificult sections where only very shortly explained and someone new to K8s could get stuck or get the wrong idea.

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +1. First we decide what kind of environment we are creating. Is it a PoC, a Staging, or a Productive environment?
This should render the same but keeps every sentence on it's own line.
Also each acronym should be spelled out at least once (in this case PoC)
```suggestion
1. We decide what kind of environment we are creating. 
   Is it a proof-of-concept (PoC), staging, or productive environment?
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +In this how-to, we will show step by step what is necessary to migrate an application from CloudFoundry to Kubernetes.
https://www.merriam-webster.com/dictionary/step-by-step

```suggestion
In this how-to, we will show step-by-step what is necessary to migrate an application from CloudFoundry to Kubernetes.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +2. Then we prepare and set up our cluster with the sufficient services and service bindings to satisfy the environment's requirements.
```suggestion
2. We prepare and set up our cluster with the sufficient services and service bindings to satisfy the environment's requirements.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +3. Finally, we adapt our application to deploy to Kubernetes and make sure it can consume bound services from within our Kubernetes cluster.
```suggestion
3. We adapt our application to deploy to Kubernetes and make sure it can consume bound services from within our Kubernetes cluster.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Select an environment you're planning to build and click on it to jump to a corresponding section:
```suggestion
Select the type of environment you're planning to build and click on it to jump to the corresponding section:
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +  - If you only do a simple PoC this kind of environment will be sufficient for you.
```suggestion
  - If you want to create a PoC, this kind of environment will be sufficient for you. 
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +The secret has to be in YAML format like in the example below. Use the values from service binding's JSON data to fill respective fields.
```suggestion
The secret has to be in YAML format like in the example below. 
Use the values from service binding's JSON data to fill respective fields.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- [docker](https://docs.docker.com/get-docker/)
```suggestion
- [`svcat`](https://svc-cat.io/docs/cli/)
- [`helm`](https://helm.sh/docs/intro/install/)
- [`kubectl`](https://kubernetes.io/docs/tasks/tools/)
- [`docker`](https://docs.docker.com/get-docker/)
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- [docker](https://docs.docker.com/get-docker/)
I would monospace each tool to stay consistent.

```suggestion
- [`kubectl`](https://kubernetes.io/docs/tasks/tools/)
- [`docker`](https://docs.docker.com/get-docker/)
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +First, create a Service Manager instance in CloudFoundry with the `subaccount-admin` plan.
```suggestion
First, create a service manager instance in CloudFoundry with the `subaccount-admin` plan. 
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +First, create a Service Manager instance in CloudFoundry with the `subaccount-admin` plan.
Also this should probably be lower case in the whole following section

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +  uri: <uri>
Is this supposed to be copied 1 to 1 or should the `<...>` parts be replaced and with what? I would expect a sentence like:
> Use the data from the JSON file to replace the corresponding value in the `stringData` section of the YAML.

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +The `service-manager-credentials.txt` is sensitive data, keep it in a safe place. You will need it later on, especially the `username` and `password`.
```suggestion
The `service-manager-credentials.txt` is sensitive data, keep it in a safe place. 
You will need it later on, especially the `username` and `password`.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +The `service-manager-credentials.txt` is sensitive data, keep it in a safe place. You will need it later on, especially the `username` and `password`.
Why especially username and password? Are those the only ones that I will need later?

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To make the services available in the Kubernetes cluster we need to register a service broker into the Service Catalog of our Kubernetes cluster.  In SAP BTP Cloud Foundry the role of a service broke
One line per sentence and stay consistent with naming (e.g. service manager should always be 
in monospace or lowercase or spelled as a proper noun...)

```suggestion
To make the services available in the Kubernetes cluster, we need to register a service broker into the Service Catalog of our Kubernetes cluster.  
In SAP BTP Cloud Foundry the role of a service broker is fulfilled by the service manager.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Now we can create service instances with the service catalog. Let's create a destination service instance first.
```suggestion
Now we can create service instances with the service catalog. 
Let's create a destination service instance first.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To deploy the `cert-manager` into your cluster, install the `cert-manager` CRDs with
What is `CRDs`?

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Finally, add a self-signed certificate issuer to your cluster. It can be done by adding the following YAML configuration:
```suggestion
Finally, add a self-signed certificate issuer to your cluster. 
It can be done by adding the following YAML configuration:
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- After creating an instance we also need to bind it. The binding `JSON` should look similar to this:
```suggestion
- After creating an instance we also need to bind it. 
  The binding `JSON` should look similar to this:
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +- Once you have the data from the Service Manager's binding, provide it to `helm` and deploy the service operator. Helm is a package manager for Kubernetes.:
```suggestion
Once you have the data from the Service Manager's binding, provide it to `helm` and deploy the service operator. 
Helm is a package manager for Kubernetes.:
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +To figure out what has to be migrated we just have to take a look at the `manifest.yml`
```suggestion
To figure out what has to be migrated we just have to take a look at the `manifest.yml`.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +This information is important in the following steps
```suggestion
This information is important in the following steps.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Run the command below to expose your application to the internet. It will use your cluster's IP address and port your application listens on. Exposing an application this way is good only for testing
```suggestion
Run the command below to expose your application to the internet. 
It will use your cluster's IP address and port your application listens on. 
Exposing an application this way is good only for testing. 
**Don't use it in production.**
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Run the command below to expose your application to the internet. It will use your cluster's IP address and port your application listens on. Exposing an application this way is good only for testing
Also why is this part of the "production environment" section?

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Next, check your shoot-cluster YAML for the currently configured DNS.
> Next, check your shoot-cluster YAML for the currently configured DNS.

What is a "shoot-cluster YAML"? It should be explained clearly beforehand.

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +This is how your Ingress file should look like:
ingress is not a proper noun (to my knowledge)
```suggestion
This is how your ingress file should look like:
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +This is how your Ingress file should look like:
This appears many times in this section.

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +The first one is our default domain, it's limited to a maximum of 64 haracters.
```suggestion
The first one is our default domain, it's limited to a maximum of 64 characters.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Your basic authentication should now work. Accessing any path should open an authentication window.
```suggestion
Your basic authentication should now work. 
Accessing any path should open an authentication window.
```

2021-08-09 07:42 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +kubectl create secret docker-registry <your-registry-secret> \                                                                                                   ✔  12402  13:33:05
```suggestion
kubectl create secret docker-registry <your-registry-secret> \                                                                                                   ✔  12402  13:33:05
```
This renders pretty badly on my machine (weird boxes or ascii chars...). Is that intended?
<img width="548" alt="Screen Shot 2021-08-09 at 09 40 05" src="https://user-images.githubusercontent.com/26565533/128673435-d5f35e43-e865-47f3-8372-6c8273c350e0.png">

2021-08-11 11:10 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +First, create a Service Manager instance in CloudFoundry with the `subaccount-admin` plan.
I'm not sure if lower case applies here since `Service Manager` is the name of the service 🤔

2021-08-11 11:24 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Run the command below to expose your application to the internet. It will use your cluster's IP address and port your application listens on. Exposing an application this way is good only for testing
Indeed, I'll put it in its own section

2021-08-11 11:26 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +This is how your Ingress file should look like:
yes, but Ingress is a name of a component, therefore I'd use a capital I

2021-08-11 11:37 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Next, check your shoot-cluster YAML for the currently configured DNS.
Agreed, it is a Gardener specific component, I'll add some explanation

2021-08-11 11:42 UTC, tomfrenken commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +This is how your Ingress file should look like:
Yeah I guess when you are not familiar with the k8s lingo that makes sense, here is a reference to the Ingress docs https://kubernetes.io/docs/concepts/services-networking/ingress/

2021-08-11 14:03 UTC, tomfrenken approved these changes
LGTM

2021-08-11 15:00 UTC, florian-richter reviewed
Some more small changes 🙈

2021-08-11 15:06 UTC, florian-richter commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Next, check your shoot-cluster YAML for the currently configured DNS.
I didn't see the explanation. Did you forget to add it or did I miss it? 😅

2021-08-11 15:20 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +Once you are done, run `kubectl apply -f <your-binding>.yml` to create the secret in your cluster.
It's somewhat explained above how to fetch the data for the secret. Feedback is taken, we'll refine it with the iterations to come.

2021-08-11 15:20 UTC, artemkovalyov commented on docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
> +smctl register-platform <name-you-want-to-give-the-cluster> kubernetes > service-manager-credentials.txt
Good hint. We'll update to mention the guide aims at Posix env.

2021-08-11 19:11 UTC, florian-richter approved these changes

2021-08-11 19:11 UTC, merged