doc: Additional headers and query parameters
SAP/cloud-sdk pull request #384
Opened 2021-07-20 17:04 UTC by marikaner

## What Has Changed?

Added documentation on how the SDK treats headers and query parameters on destinations.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-07-20 23:43 UTC, artemkovalyov requested changes
Thanks for the comprehensive rewrite and additions. It's mostly good to go.
Consider my suggestions and minor fixes.

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SAP Cloud SDK helps you to authenticate against the destination service and retrieve destinations in your application.
```suggestion
The SAP Cloud SDK helps you to authenticate against the destination service and retrieve destinations into your application.
```

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SAP Cloud SDK searches for the destination with the given name in the following locations, in order:
```suggestion
The SAP Cloud SDK searches for the destination by its name in the following order:
```

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SAP Cloud SDK searches for the destination with the given name in the following locations, in order:
Maybe resolver is a better term in this context. But I also like search.

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +In case the same destination name occurs in multiple of the locations, destinations defined in local environment precede service bindings, which in turn precede the destination service.
```suggestion
If the destination name can be found in multiple locations the precedence rules are the same as the search order. Local environment variables have the highest priority while SAP BTP's destination service has the lowest.
```

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +In case the same destination name occurs in multiple of the locations, destinations defined in local environment precede service bindings, which in turn precede the destination service.
I think passive is justified here.

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +In case the same destination name occurs in multiple of the locations, destinations defined in local environment precede service bindings, which in turn precede the destination service.
Basically, we use the first occurrence of the destination found. We can stop searching after the first variant of the destination is found, right?

2021-07-20 23:43 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +This does not apply to query **parameter names**`.
```suggestion
The destination service has a convention to define static headers and query parameters on destinations.
Create additional properties in your destination and define their values as follows:

- `URL.headers.<header-key>` for headers
- `URL.queries.<query-key>` for query parameters

For every header or query parameter create an additional property and replace `<header-key>` or `<query-key>` with the name of your header or query parameter and set the respective value.
The SAP Cloud SDK adds those additional headers and query parameters for every communication with the given destination.

:::note

Other headers or query parameters built by the SAP Cloud SDK are overwritten by additional headers and query parameters on the destination.
Custom headers and query parameters, however, precede the additional properties.

**Header names** keep their casing but overwrite other headers independent of the casing, e.g. `AUTHORIZATION` overwrites `authorization`.
This does not apply to query **parameter names**`.
```

2021-07-22 10:20 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +For every header or query parameter create on additional property and replace `<header-key>` or `<query-key>` with the name of your header or query parameter and set the according value.
`<header-key>` or `<query-key>` to `<header-key>` and `<query-key>`

2021-07-22 10:21 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +You can construct a destination object manually and pass the destination information directly the `execute()` method.
```suggestion
You can construct a destination object manually and pass the destination information directly to the `execute()` method.
```

2021-07-22 10:22 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +For every header or query parameter create on additional property and replace `<header-key>` or `<query-key>` with the name of your header or query parameter and set the according value.
```suggestion
For every header or query parameter create on additional property and replace `<header-key>` and `<query-key>` with the name of your header or query parameter and set the according value.
```

2021-07-22 10:22 UTC, FrankEssenberger approved these changes
LGTM only minor comments

2021-07-29 10:41 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +In case the same destination name occurs in multiple of the locations, destinations defined in local environment precede service bindings, which in turn precede the destination service.
Correct, I tried to bring this in and explain it better.

2021-07-29 10:48 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +This does not apply to query **parameter names**`.
Done.

2021-07-30 08:45 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SAP Cloud SDK adds those additional headers and query parameter for every communication with the given destination.
Is there always only one parameter? I just don't get all the singular/plural conjunction here

2021-07-30 08:45 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SAP Cloud SDK adds those additional headers and query parameter for every communication with the given destination.
```suggestion
The SAP Cloud SDK adds those additional headers and query parameters for every communication with the given destination.
```

2021-07-30 08:45 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +For every header or query parameter create an additional property and replace `<header-key>` and `<query-key>` with the name of your header or query parameter and set the respective value.
```suggestion
Create an additional property for every header or query parameter and replace `<header-key>` and `<query-key>` with the name of your header or query parameter and set the respective value.
```

2021-07-30 09:30 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The destination service has a convention to define static headers and query parameters on destinations.
Let's make it clear this is done on the SAP BTP Cockpit side

2021-07-30 09:30 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +- `URL.headers.<header-key>` for headers
I think a screenshot to explain this would be really helpful.

2021-08-01 12:28 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +:::
I'd convert it into a section with a subheading going smth like:

#### Rules of precedence for headers and query parameters

Such subheadings will also help to refer to this part in support via a qualified link.

Then I'd go through the points you provided having an example dummy destination to demonstrate them. The example goes a long way to explain daunting abstractions, especially with multiple special cases.

No hard feelings if you keep it like it is of course. It's just to show that I broke my legs keeping all the entities in my head. I find TS and RUST docs as good examples of this approach.

2021-08-02 10:00 UTC, artemkovalyov approved these changes
Looks really good:) Thanks!

2021-08-02 10:00 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +Headers or query paramters built by the SAP Cloud SDK are overwritten by additional headers and query parameters on the destination.
```suggestion
Headers or query parameters built by the SAP Cloud SDK are overwritten by additional headers and query parameters on the destination.
```

2021-08-02 10:00 UTC, merged