Filter functions
SAP/cloud-sdk pull request #39
Opened 2020-12-03 11:04 UTC by artemkovalyov

I added a bit info about filter functions. Please, take a look and give suggestions for corrections. This was asked by a customer in today's feedback session.

2020-12-07 07:13 UTC, Emdee89 commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +Please, check what filter options are supported by [OData v2 standard](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/). Search for: **4.5. Filter System Query Option ($filter)
```suggestion
We recommend to check what filter options are supported by [OData v2 standard](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/). Search for: **4.5. Filter System Query Option ($filter)** after navigation to the link.
```

2020-12-07 07:19 UTC, Emdee89 commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +For more details check our [API documentation](https://help.sap.com/doc/b579bf8578954412aea2b458e8452201/1.0/en-US/com/sap/cloud/sdk/datamodel/odata/helper/package-summary.html) or use `autocomplete`
I would directly refer to the Javadoc of the class "EntityField" (https://help.sap.com/doc/b579bf8578954412aea2b458e8452201/1.0/en-US/com/sap/cloud/sdk/datamodel/odata/helper/EntityField.html) as it contains the list of supported filter functions.

2020-12-08 10:26 UTC, MatKuhr commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +For more details check our [API documentation](https://help.sap.com/doc/b579bf8578954412aea2b458e8452201/1.0/en-US/com/sap/cloud/sdk/datamodel/odata/helper/package-summary.html) or use `autocomplete`
Agreed, and I would do the same for OData V4.

2020-12-08 10:30 UTC, MatKuhr commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +For more details check our [API documentation](https://help.sap.com/doc/b579bf8578954412aea2b458e8452201/1.0/en-US/com/sap/cloud/sdk/datamodel/odata/helper/package-summary.html) or use `autocomplete`
e.g. https://help.sap.com/doc/b579bf8578954412aea2b458e8452201/1.0/en-US/com/sap/cloud/sdk/datamodel/odatav4/expression/FilterableValue.html

2020-12-08 13:45 UTC, artemkovalyov commented
Thanks for the review @Emdee89  and @MatKuhr, I'll give it a thought and get back to it later this week.

2021-03-09 16:23 UTC, florian-richter reviewed
Some formatting recommendations:

2021-03-09 16:23 UTC, florian-richter commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +We recommend to check what filter options are supported by [OData v2 standard](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/). Search for: **4.5. Filter System Query Option (
```suggestion
We recommend to check what filter options are supported by [OData v2 standard](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/). 
Search for: **4.5. Filter System Query Option ($filter)** after navigation to the link.
```

2021-03-09 16:23 UTC, florian-richter commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +We are working on supporting string filtering function like `SubstringOf`, `endsWith`, `startsWith`, etc.
```suggestion
We are working on supporting string filtering function like `substringOf`, `endsWith`, `startsWith`, etc.
```

2021-03-09 16:23 UTC, florian-richter commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +Batch requests allow wrapping multiple OData requests into one single batch call. Thereby we reduce the number of roundtrips to the remote server. Refer to the [official OData V2 spec](https://www.od
```suggestion
Batch requests allow wrapping multiple OData requests into one single batch call to reduce the number of roundtrips to the remote server. 
Refer to the [OData v2 standard](https://www.odata.org/documentation/odata-version-2-0/batch-processing/).
```

2021-03-11 12:43 UTC, MatKuhr commented on docs/java/features/odata/type-safe-client-odata-v2.mdx
> +We are working on supporting string filtering function like `SubstringOf`, `endsWith`, `startsWith`, etc.
Support for this is already implemented

2021-03-11 12:45 UTC, MatKuhr requested changes
I am not sure how meaningful it is to document the filter functions here. We are mainly copy/pasting the OData docs. Also we would have to repeat it again for V4.

I would rather create a note for any operations we don't yet support. To my knowledge that would be e.g. `in` for OData V4.

As far as I have seen the main source for people missing the functionality is if they are on an older version where it's not included.

2021-03-19 13:20 UTC, closed without merging