Feature: Nested Expand
SAP/cloud-sdk pull request #404
Opened 2020-08-20 14:01 UTC by FrankEssenberger

## Context

I did test driven design and it seems like nested expands are already working? I added 

## Definition of Done

Please consider all items and remove only if not applicable.

- [ ] Tests created/adjusted for your changes.
- [ ] Release notes updated.
  * Provide sufficient context so that each entry can be understood on its own.
  * Be specific about names of functions, classes, modules, etc.
  * Describe when or where this is relevant
  * Use indicative and present tense. For example, write "Provide function `name` that does X in order to Y" over "Now X can be done by calling a new function".
- [ ] PR title adheres to [conventional commit guidelines](https://www.conventionalcommits.org) (please note that only `fix:` and `feat:` will end up in the release notes)
- [ ] If applicable: Properly documented (JSDoc of public API)
- [ ] If applicable: Check if `node run doc` still works.

2020-08-26 21:42 UTC, jjtang1985 requested changes
The expand was implemented recursively, so it's possible all the existing functions are working properly.
The 3rd level expand looks good for quality assurance.
However, in `test-packages`, I see lots of "new" files, which are not new at all.
Could you please check?

2020-08-26 21:42 UTC, jjtang1985 commented on test-packages/test-services-e2e/TripPin/microsoft-o-data-service-sample-trippin-in-memory-models-service/Airlines.d.ts
> +import { AirlinesRequestBuilder } from './AirlinesRequestBuilder';
I'm a bit confused.
All the changes in this folder are about adding `.d.ts` files and `.d.ts.map` files, which do exist in the current master branch.

2020-08-26 21:42 UTC, jjtang1985 commented on test-packages/test-services-e2e/v4/admin-service/TestEntity.d.ts
> +import { TestEntityRequestBuilder } from './TestEntityRequestBuilder';
Changes in this folder have the similar situation as the ones in `TripPin`

2020-08-26 21:42 UTC, jjtang1985 commented on test-packages/test-services/v2/multiple-schemas-service/MultiSchemaTestEntity.d.ts
> +import { MultiSchemaTestEntityRequestBuilder } from './MultiSchemaTestEntityRequestBuilder';
This folder as well.

2020-08-26 21:42 UTC, jjtang1985 commented on test-packages/test-services/v2/test-service/TestEntity.d.ts
> +import { TestEntityRequestBuilder } from './TestEntityRequestBuilder';
This folder as well

2020-08-27 07:00 UTC, FrankEssenberger commented
I think this could be related starting from the different branches. Once the big PR is merged I changed to Master and check your comments.

2020-08-27 14:40 UTC, FrankEssenberger commented
Ok after merging master it looks ok from the changes. Have a look @Junjie adn @marikaner

2020-08-27 15:41 UTC, jjtang1985 approved these changes
Ok, so all the strange `d.ts` file changes are gone.

2020-08-27 15:43 UTC, FrankEssenberger commented
I am also not sure what happened there.

2020-08-27 15:43 UTC, merged