Add upgrade strategy document
SAP/cloud-sdk pull request #422
Opened 2021-08-17 13:40 UTC by florian-richter

## What Has Changed?

Add agreed-upon upgrade strategy document with minimal changes (to adhere to vale style guide and using admonitions).

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)

2021-08-17 13:42 UTC, florian-richter commented
@artemkovalyov Do you think we should have a banner or something like that to notify readers that this was added? I am unsure what would be an appropriate choice (especially since some readers may only be interested in the Java SDK).

2021-08-18 15:02 UTC, marikaner approved these changes

2021-08-19 08:22 UTC, artemkovalyov commented
@florian-richter, this is good and detailed. On the other hand, it's too much for the customers.
I wouldn't bring our internal reasoning to the public. Let's just explain how our releases work:

1. The SAP Cloud SDK for JavaScript releases Major versions to keep up with the development of the SAP Business Technology Platform that requires breaking changes.
2. The new version is released every 6 to 12 months depending on the speed of accumulating necessary breaking changes.
3. We communicate the next Major release 3 months before the actual release date and list all the planned breaking updates.
4. We provide a detailed migration guide for every Major release. We plan releases so that most of the projects using the SDK can be migrated to a new version within 1-3 days.
5. We establish 3 months migration window after the release of a  new major version. During this window, the previous release will receive bug fixes and maintenance updates if necessary.
5. We stop active development of the previous version immediately after a new Major release. To benefit from the new functionality migration is mandatory.
6. We recommend always migrating early to ensure compatibility with the SAP Business Technology Platform at all times.

I'd see it as smth like this. Customers shouldn't be aware of our internal kitchen. I'd appreciate it if we establish proper release notes in our documentation portal and refer to them from here. An initial chat with the next 2 releases coming would be nice to have as well. This all helps customers to make up their own plans and us to be clear in communications with other stakeholders.

I like the simplicity of Node's Releases page:) https://nodejs.org/en/about/releases/

2021-08-19 08:47 UTC, florian-richter commented
@artemkovalyov 

> I wouldn't bring our internal reasoning to the public.

This document was always intended as external communication. What part would you consider "internal reasoning"?

> 3. We communicate the next Major release 3 months before the actual release date and list all the planned breaking updates.

We will likely do this but I would be hesitant to promise to "list every breaking change 3 months in advance". We could forget something or the timeline could change.

> 5. We establish 3 months migration window after the release of a  new major version. During this window, the previous release will receive bug fixes and maintenance updates if necessary.

We mutually AGREED that we will not support old version after a major release. This would put a lot of effort on the team to support an old version which customers should use anymore.

> An initial chat with the next 2 releases coming would be nice to have as well. 

You mean we should already set the scope and timeline for version 3??

2021-08-20 15:39 UTC, artemkovalyov reviewed
Looks good. Check my improvement ideas.

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +id: announcing-version-2
This can be skipped if file name is equal to the ID

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +This upgrade strategy only applies to the SAP Cloud SDK for JavaScript and is not applicable to the SAP Cloud SDK for Java!
```suggestion
This upgrade only applies to the SAP Cloud SDK for JavaScript and is not applicable to the SAP Cloud SDK for Java!
```

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +So far, we always stayed backwards compatible to avoid migration efforts for you.
```suggestion
We have always stayed backward compatible to avoid migration efforts for you.
```

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +Making these changes will have many benefits for the usability of the SAP Cloud SDK and our development speed.
This sounds a bit like an excuse.

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +Making these changes will have many benefits for the usability of the SAP Cloud SDK and our development speed.
```suggestion
Our decision to release the next major version is connected to unavoidable breaking changes we have to make to keep the SAP Cloud SDK fulfill its mission. 
```

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +Please [reach out to us](https://github.com/SAP/cloud-sdk-js/discussions/1518) if you have feedback, suggestions or improvements!
I'd put it to the end for the doc. Here it's too early for feedback.

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +We will continuously publish beta versions and would appreciate feedback on these releases.
```suggestion
We will continuously publish beta versions and would appreciate feedback from early adopters.
```

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +This feedback will be included in later beta releases.
```suggestion
We'll use this feedback to improve version 2.0 before releasing it as Generally Available.
```

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +Between these major releases, we will continue with a biweekly release cycle to deliver non-breaking changes.
I'd link to our release strategy from here instead.

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +## Will Old Major Versions Be Updated?
```suggestion
## Will You Maintain Version 1.x?
```

2021-08-20 15:39 UTC, artemkovalyov commented on docs/js/announcing-version-2.mdx
> +If something is not covered in our upgrade guide or otherwise prevents you from upgrading, we will happily support you to resolve that issue.
I think a link to the release strategy makes sense here.

2021-08-20 15:39 UTC, artemkovalyov commented on sidebars.js
> +      'js/upgrade-strategy',
I think we need a foldable menu section for this. Or we'll make top links too busy.

2021-08-23 23:03 UTC, artemkovalyov commented
![image](https://user-images.githubusercontent.com/10460752/130530258-1651c6db-23db-4fed-a64b-894d0b9a2cad.png)

2021-08-23 23:04 UTC, artemkovalyov commented
![image](https://user-images.githubusercontent.com/10460752/130530306-6e047abc-cad9-4ec7-bc1c-ae66aa4085fa.png)

2021-08-24 08:23 UTC, artemkovalyov commented
As we agreed with @florian-richter, I'll take care of this PR. We decided to split between the strategy and announcements.
I also added a table with base info about current and planned major releases.
@marikaner, @sacnl, give your feedback.

2021-08-24 09:10 UTC, artemkovalyov commented on docs/js/release-policy.mdx
> +| 2.x     | January 2022         | [Version 2.x](announcing-version-2.mdx) | [Version 2.x](announcing-version-2.mdx#what-will-change-in-version-2) | First major version bump since initial release of
```suggestion
| 2.x     | January 2022         | [Version 2.x](announcing-version-2.mdx) | [Version 2.x](announcing-version-2.mdx#what-will-change-in-version-2) | First major version bump since initial release of the SAP Cloud SDK for JavaScript |
```

2021-08-24 10:39 UTC, FrankEssenberger commented on docs/js/announcing-version-2.mdx
> +- We will release a new major version every 6 to 12 months with version 2.x expected in January 2022
A few things need to be moved to the policy document I guess. I would also link the document here in the beginning with something like: `Our general release strategy can be found....`

2021-08-24 10:42 UTC, FrankEssenberger approved these changes
In general I was happy with the document as it was, but I also see the benefits of splitting it in two parts. Please make sure the intros of both documents reads nice and does not repeat content.

2021-08-24 11:40 UTC, marikaner reviewed
@artemkovalyov

I think we now have some duplicate information between the guides and I think we should remove redundancy for a more interesting read and link the policy somewhere instead.
I also noticed, that we are using the word "migration" in many places. We agreed to stay with "update" or "upgrade", rather than "migration" because people have a negative connotation with that and tend to be afraid of the effort of migrating.
Please adjust those phrases.

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +Making these changes will have many benefits for the usability of the SAP Cloud SDK and our development speed.
@artemkovalyov What about this suggestion? I don't have a problem with the original version and I don't think it sounds like an excuse (so I would be fine keeping it). If you would like to change it, please take into consideration that in my opinion "we have to make to keep the SAP Cloud SDK fulfil its mission" sounds a bit too general and maybe you can include some of the points originally made by Florian.
(Also note that it should be fulfil with one "l" in the end, I also do that wrong all the time.)

2021-08-24 11:40 UTC, marikaner commented on docs/js/release-policy.mdx
> +| 3.x     | July 2022            | TBD                                     | TBD                                                                   | TBD
I think the "Notes" column is unnecessary, because it does not contain any additional information. Can we just remove it?

2021-08-24 11:40 UTC, marikaner commented on docs/js/release-policy.mdx
> +### Migration to a New Major Version
We agreed not to scare anyone with the word "migration". Learning from Java ;)

```suggestion
### Upgrading to a New Major Version
```

2021-08-24 11:40 UTC, marikaner commented on docs/js/release-policy.mdx
> +- The documentation is always up to date with the latest major release
I find the "only" in the middle of the sentence a bit odd and "only" sounds a little negative.
Also, lists should be parallel, therefore, please add a full stop in the end.

```suggestion
- We provide fixes and new features for the latest version of the SAP Cloud SDK, exclusively.
- The documentation is always up to date with the latest major release.
```

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +- We will release a new major version every 6 to 12 months with version 2.x expected in January 2022
I think we should just remove this "Abstract" as it only contains duplicate information from the general policy.

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +Between major releases, we will continue with a biweekly release cycle to deliver minor version updates with non-breaking changes.
This can also be removed.

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +With this document, we want to share our plans regarding timeline, content, and support.
I think after this sentence could be a good place to link the policy.

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +We aim at making migration possible within 1 day regardless of the project size.
Again, "migration" should be avoided.
```suggestion
Upgrading should be possible in less than a day regardless of the project size.
```

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +You can always count on our [support and advice](../overview/support.mdx) with migration.
This sounds a bit weird and kind of duplicate (with a different tone) of the tip before. I would just leave it out, why make it longer than necessary...

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +## Will Old Major Versions Be Maintained?
This section belongs in the policy in my opinion.

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +We will provide a few popular options including a `Moment.js` - based middleware for the easiest possible migration.
```suggestion
We will provide a few popular options including a `Moment.js` - based middleware for the easiest possible upgrade.
```

2021-08-24 11:40 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +As long as you don't use undocumented methods, this change should not need any migration.
```suggestion
As long as you don't use undocumented methods, this change should not need any changes on your side.
```

2021-08-24 11:43 UTC, marikaner requested changes
One more thing

2021-08-24 11:43 UTC, marikaner commented on docs/js/announcing-version-2.mdx
> +# Announcing Version 2.x for the SAP Cloud SDK for JavaScript
I think it would look nicer in the documentation if there was no additional heading here. There is no additional information in this title and I would always avoid two headings in a row (even though there is the info thingy on top).
```suggestion
```

2021-08-24 11:43 UTC, marikaner commented on docs/js/release-policy.mdx
> +## Versioning Standards
Same here, I would remove the additional title.
```suggestion
```

2021-08-24 14:47 UTC, marikaner approved these changes
LGTM

2021-08-24 15:39 UTC, merged