Patch 2
SAP/cloud-sdk pull request #433
Opened 2021-08-24 15:26 UTC by andrastemesi-sap

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-08-30 15:54 UTC, andrastemesi-sap commented on docs/java/features/connectivity/destinations.mdx
> +Only the remaining part of the key will be used to create the header.
Makes sense, thanks for pointing it out!

2021-08-30 15:55 UTC, andrastemesi-sap commented on docs/java/features/connectivity/destinations.mdx
> +Here is one simple example implementation which adds "key1=value1" to the query string when calling the destination:
Thanks, same as above.

2021-08-30 15:56 UTC, andrastemesi-sap commented on docs/java/features/connectivity/destinations.mdx
> +To include headers into every call to a target system you can define them as properties on the destination.
Could be both, tried to clarify it.

2021-08-30 15:59 UTC, andrastemesi-sap commented
> please, run `npm run prettier` another time. 

Hm I believe that I ran it, and when I did it now, there were no changes. This time I made sure to do so, please let me know if the alignment is still broken. That would mean something's wrong on my side.

2021-08-30 19:40 UTC, artemkovalyov requested changes
Check my suggestion. I hope it would add clarity.
Ping me for approval when done.

2021-08-30 19:40 UTC, artemkovalyov commented on docs/java/features/connectivity/destinations.mdx
> +The method `.property()` can be called on the destination.
```suggestion
For that, call the `.property()` method on the destination. It expects a key-value pair with a key formatted as `URL.headers.<key>` and an arbitrary value string. 
```

2021-08-30 19:40 UTC, artemkovalyov commented on docs/java/features/connectivity/destinations.mdx
> +Only the remaining part of the key will be used to create the header.
```suggestion
```

2021-08-30 19:40 UTC, artemkovalyov commented on docs/java/features/connectivity/destinations.mdx
> +Only the remaining part of the key will be used in the query string.
Update this according to the example above, please.

2021-09-01 13:28 UTC, MatKuhr commented on docs/java/features/connectivity/destinations.mdx
> +You can also add headers to a specific destination using properties so they will be always included when calling the target system.
I would remove this here, because it doesn't explain how it works. Or you supply a link to the section below. A link to a section can be done like in this example from our troubleshooting docs: 
```
See [JWT validation fails](#jwt-validation-fails).
```

2021-09-01 13:28 UTC, MatKuhr approved these changes
lgtm from my side

2021-09-01 13:52 UTC, andrastemesi-sap commented on docs/java/features/connectivity/destinations.mdx
> +You can also add headers to a specific destination using properties so they will be always included when calling the target system.
Added a link.

2021-09-01 13:58 UTC, MatKuhr approved these changes

2021-09-01 16:49 UTC, artemkovalyov approved these changes
LGTM

2021-09-01 16:49 UTC, merged