Add mtls doc
SAP/cloud-sdk pull request #449
Opened 2021-08-31 08:17 UTC by KavithaSiva

## What Has Changed?

I added a section for Certificate based Authentication

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-09-01 08:00 UTC, MatKuhr commented on docs/java/features/connectivity/mtls.mdx
> +You can find more details on X.509 certificates [here](https://github.wdf.sap.corp/pages/CPSecurity/Knowledge-Base/03_ApplicationSecurity/X509Authentication/).
I don't know of any external documentation, so what can we do :/

2021-09-01 08:10 UTC, MatKuhr approved these changes
lgtm, minor suggestions

2021-09-01 08:10 UTC, MatKuhr commented on docs/java/features/connectivity/mtls.mdx
> +  "credential-types": ["instance-secret",...]
I think if `x509` was added here in place of the `...` both would be available and the SDK would take the certificate. So maybe remove the dots.

2021-09-01 08:10 UTC, MatKuhr commented on docs/java/features/connectivity/mtls.mdx
> +:::caution
```suggestion
:::danger
```

2021-09-01 08:11 UTC, Johannes-Schneider requested changes

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +When a service or an application is protected using [`XSUAA`](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/6373bb7a96114d619bfdfdc6f505d1b9.html), we need to obtain an acc
Please do not use "we" (this is done more often than just here)

```suggestion
If a service or an application is protected using [`XSUAA`](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/6373bb7a96114d619bfdfdc6f505d1b9.html), an access token from `XSUAA` is required to access the protected service or application.
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +Please note that the process of obtaining the `JWT` is internally carried out by the SAP Cloud SDK and developers need not worry about doing this explicitly.
```suggestion
Please note that the process of obtaining the `JWT` is internally carried out by the SAP Cloud SDK and application developers do not need to worry about doing this explicitly.
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +## Usage of Client Credentials and shortcomings
Title case

```suggestion
## Usage of Client Credentials and Shortcomings
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +Now, adding this obtained `JWT` as an `Authorisation` header to the request to the service, ensures that your request gets authorised and authenticated.
The HTTP Header is usually written in American English ([reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization)).
In general, I think we usually prefer American English (cc @artemkovalyov please correct me if I'm wrong here)

```suggestion
Now, adding this obtained `JWT` as an `Authorization` header to the request to the service, ensures that your request gets authorized and authenticated.
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +## Certificate based Authentication for services (Soon to be default)
Please check the go-live date once again.

```suggestion
## Certificate Based Authentication for Services

:::info Hint
Certificate based authentication is to be the default authentication mechanism on SAP BTP Cloud Foundry starting from Sept. 13th 2021.
:::
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +For e.g.
```suggestion
Example:
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +By default `XSUAA` managed certificates are only valid for 7 days and to obtain a new certificate, deletion and re-creation of service binding is required.
```suggestion
By default `XSUAA` managed certificates are valid only for 7 days.
To obtain a new certificate, deletion and re-creation of service binding is required.
```

2021-09-01 08:11 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +You can find more details on X.509 certificates [here](https://github.wdf.sap.corp/pages/CPSecurity/Knowledge-Base/03_ApplicationSecurity/X509Authentication/).
I'm not a fan of putting an internal link in our public docu. This is most certainly confusing for external customers... Maybe rather wait with this sentence until public documentation is available?

2021-09-01 11:31 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +You can find more details on X.509 certificates [here](https://github.wdf.sap.corp/pages/CPSecurity/Knowledge-Base/03_ApplicationSecurity/X509Authentication/).
I will remove this sentence for now and add it back when we have a link to public documentation available.

2021-09-01 11:49 UTC, Johannes-Schneider requested changes

2021-09-01 11:49 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +To obtain an access token or `JWT`, first we extract the `clientid`, `clientsecret` and `uri` from the service binding and then using the `url` from `xsuaa` service binding, trigger a [`token flow`](
There are still some `we`s in the documentation, which is not only a little bit too informal (who is `we`? Most likely you either mean the Cloud SDK or the application itself) but also violates compliancy AFAIK as usually `we` would be associated with SAP as a company.

2021-09-01 11:49 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +Please note that the process of obtaining the `JWT` is still internally carried out by the SAP Cloud SDK, we just use the `certificate` for this process now if the binding contains the `certificate`.
Here is another `we`.

2021-09-01 11:51 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +To obtain an access token or `JWT`, first we extract the `clientid`, `clientsecret` and `uri` from the service binding and then using the `url` from `xsuaa` service binding, trigger a [`token flow`](
Yes, I am still looking into changing them all.

2021-09-01 11:58 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +To obtain an access token or `JWT`, first we extract the `clientid`, `clientsecret` and `uri` from the service binding and then using the `url` from `xsuaa` service binding, trigger a [`token flow`](
Thanks for pointing it out, I will pay more attention to this while writing documents in future.

2021-09-01 13:27 UTC, Johannes-Schneider reviewed
One more minor suggestion from my side, otherwise LGTM.

2021-09-01 13:27 UTC, Johannes-Schneider commented on docs/java/features/connectivity/mtls.mdx
> +The only difference is that `certificate` is being used for this process now if the binding contains the `certificate`.
```suggestion
Please note that the process of obtaining the `JWT` is still internally carried out by the SAP Cloud SDK.
The only difference is that the provided `certificate` is used to authenticate the client.
```

2021-09-02 09:05 UTC, Johannes-Schneider approved these changes
Reads well 👍

2021-09-02 09:12 UTC, KavithaSiva commented
> Reads well 👍

Thanks a lot for your detailed and in depth review, it reads a lot better now :)

2021-09-07 07:52 UTC, artemkovalyov requested changes
Hey, it took a bit long. I was interrupted many times. I decided to fix some stuff for clarity.
Take a look at my suggestions.

2021-09-07 07:52 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +In general, if a service binding has a property `credentials: { credential-type: x509 }` then this is an indication that certificate based authentication can be used to access the service.
```suggestion
To adhere to the latest recommended security best practices by SAP, some re-use and kernel services have enabled certificate-based authentication.
As a consequence, SAP Cloud SDK also supports certificate-based authentication while accessing these services.
If a service binding has a property `credentials: { credential-type: x509 }` then this is an indication that you can use certificate-based authentication to access the service.
```

2021-09-07 07:52 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +This means that in the service binding in addition to the `client_secret` you will also find a `certificate` and `key` entry now.
```suggestion
`XSUAA` service is one of the services that has enabled certificate-based authentication.
This means that in the service binding in addition to the `client_secret` you will also find `certificate` and `key` entries now.
```

2021-09-07 07:52 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +The only difference is that the provided `certificate` is used to authenticate the client.
```suggestion
This certificate would now be used to establish a secure session to obtain the `JWT` instead of the client credentials token flow used previously.
The SAP Cloud SDK will as before fetch the `JWT` for you.
The only difference is we will use the `certificate` from your service binding to authenticate the client.
```

2021-09-07 07:52 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::
```suggestion
:::danger short certificate validity period

By default `XSUAA` managed certificates are valid only for 7 days.
To obtain a new certificate, deletion and re-creation of service binding are required.
The application also needs to be restarted to use the updated service binding.
Your call to the `XSUAA` to fetch a `JWT` will fail after your certificate expires.

:::
```

2021-09-07 07:52 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +Ensure that your `xs-security.json` contains the `instance-secret` as the first entry in property `credential-types`
```suggestion
If you prefer to continue using **Client Credentials** instead of **Certificate-based Authentication**, make sure your `xs-security.json` contains the `instance-secret` as the first entry in the property `credential-types`. 
```

2021-09-07 08:04 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +## Usage of Client Credentials and Shortcomings
I will prefer the old section title because I think I don't elaborate more on `mTLS` in this section to add it to the heading.

2021-09-07 09:45 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +:::
Is it not better to have a concrete date ?

2021-09-07 09:48 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +The only difference is that the provided `certificate` is used to authenticate the client.
I am just editing so that we don't have a `we` in the sentence. Johannes wrote earlier that this could be informal.

2021-09-07 10:14 UTC, artemkovalyov approved these changes
Handle the suggestions futher.

2021-09-07 10:14 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +To access a service protected by the  [`XSUAA`](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/6373bb7a96114d619bfdfdc6f505d1b9.html) you'll need a `JWT`.
```suggestion
Let's take an example of a service protected by the  [`XSUAA`](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/6373bb7a96114d619bfdfdc6f505d1b9.html).
To access a service you'll need a `JWT`.
```

2021-09-07 10:17 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +## Usage of Client Credentials and Shortcomings
We discussed about this and we feel the `Shortcomings of Client Credentials` is a better fit.

2021-09-07 10:58 UTC, merged