Minor updates in Certificate based Authentication
SAP/cloud-sdk pull request #461
Opened 2021-09-08 10:33 UTC by KavithaSiva

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-09-08 11:04 UTC, KavithaSiva reviewed
@artemkovalyov I wanted to quickly ask about changes you made yesterday along with some minor fixes.

2021-09-08 12:09 UTC, MatKuhr commented on docs/java/features/connectivity/mtls.mdx
> +
The statement is actually not correct, I should have shared that info as well. The XSUAA team confirmed with us that the default will not change

2021-09-08 12:11 UTC, MatKuhr commented on docs/java/features/connectivity/mtls.mdx
> +:::danger certificate renewal process
I think instead of `warn` there is `caution`. Danger is also fine I think...

2021-09-08 12:11 UTC, MatKuhr commented on docs/java/features/connectivity/mtls.mdx
> +For the `XSUAA` managed certificate use parameters below while creating a service binding.
```suggestion
For the `XSUAA` managed certificate use parameters below while creating a service **binding**.
```

2021-09-08 12:25 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +
Thanks for updating, I will remove this admonition then.

2021-09-08 17:17 UTC, artemkovalyov requested changes
Thanks for these fixes.  I'm happy to merge most of them.
I still think extra verboseness about what's ready and what's not, especially in the way it's formulated causes more confusion than helps.
I hope we can make a final run and merge your valuable updates.

2021-09-08 17:17 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::
This kind of information drives more confusion than helps usually. Most probably when someone uses it with Destination and Connectivity services it's already functioning as expected or smth will change even more fundamentally. Admonition about shortcomings in the implementation would be useful in this case after we finally understand the status or we've seen it really causes confusion from support. Here we're predicting what could cause problems that would help neither customers nor us.

2021-09-08 17:17 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +It also automatically adds the fetched `JWT` to the `Authorization` header when requesting a service to ensure that the request gets authenticated and authorized.
What do you think of such a variant:

The SAP Cloud SDK automatically
- fetches the `JWT` for you
- adds the fetched `JWT` to the `Authorization` header when requesting a service to ensure that the request gets authenticated and authorized

2021-09-08 17:17 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::danger certificate renewal process
```suggestion
:::caution certificate renewal process
```

2021-09-08 17:17 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::danger certificate renewal process
Let's have fewer red signs as things are not that bad.

2021-09-08 17:17 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::
```suggestion
```

2021-09-08 17:17 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::
Do we now use mTLS by default with Destination and Connectivity services? Do we fall back to client credentials? If so I'm strongly against this admonition.

2021-09-09 10:40 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +It also automatically adds the fetched `JWT` to the `Authorization` header when requesting a service to ensure that the request gets authenticated and authorized.
Looks better, done.

2021-09-09 10:47 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +:::
Depends on the service binding itself, if the `credential-type` is **x509** we use certificates to obtain the `JWT` and if it is `secret` then we use `clientsecret` instead. 

Currently, the bindings being created for Destination and Connectivity services do not contain `x509` credential type and that is why we have not been able to test this in an E2E manner.

2021-09-09 11:30 UTC, KavithaSiva reviewed
I also replaced usage of Client Credentials with secret as I felt this was more explicit.

2021-09-09 18:05 UTC, artemkovalyov requested changes
@KavithaSiva, let's remove the top admonition and consider my other suggestion that fixes grammar. I'm happy to approve when we fix it.

2021-09-09 18:05 UTC, artemkovalyov commented on docs/java/features/connectivity/mtls.mdx
> +:::
Can we remove it?

2021-09-10 07:45 UTC, KavithaSiva commented on docs/java/features/connectivity/mtls.mdx
> +:::
Done.

2021-09-10 07:47 UTC, artemkovalyov approved these changes
Thank you!

2021-09-10 07:52 UTC, merged