[Java] Add release notes for 3.53.0
SAP/cloud-sdk pull request #464
Opened 2021-09-13 06:38 UTC by Johannes-Schneider

## What Has Changed?

This PR adds release notes for the Java SDK for version 3.53.0

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-09-13 13:46 UTC, artemkovalyov requested changes
Check my suggestions. I hope I understood things correctly.

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +You can also add functions that return a collection inside batch requests and parse the results in similar manner.
```suggestion
You can also add functions that return a collection inside batch requests and parse the results yourself in a similar manner.
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- (Beta) Reading destinations from environment variables now allows you to configure authorization token forwarding to the target system.
```suggestion
- [**Beta**] Reading destinations from environment variables now allows you to configure authorization token forwarding to the target system.
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  This can be activated in the following ways
```suggestion
  You can activate in the following ways
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  **Note:** This means that token set via the `AuthTokenAccessor.executeWith(...)` will **not** be forwarded to the target system.
```suggestion
  **Note:** The settings above will override a token set with `AuthTokenAccessor.executeWith(...)` and it will **not** be passed to the target system. 
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- We now support adding headers to a specific destination using properties, so they will always be included when calling the target system.
```suggestion
- You can now add `headers` to a `destination` using the `property` method so that they will always be included when calling the target system. 
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  Usage: `.property("URL.headers.foo1", "bar1")`. Relevant section in documentation: [SDK Docs](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/sdk-connectivity-destination-service#pr
```suggestion
  Here's an example of the `property` method call: `.property("URL.headers.foo1", "bar1")`. Find more details on setting properties [here](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/sdk-connectivity-destination-service#provide-headers-for-destinations).
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- We now support adding query parameters to a specific destination using properties.
```suggestion
- You can now add query parameters to a destination using properties.
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  The query values should be provided without encoding. They will be encoded in the query string.
```suggestion
  The query values should be provided without encoding. They will be encoded in the query string by the SDK.
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  Example usage: `.property("URL.queries.airport", "Köln Bonn")`. The query string will include `airport=K%C3%B6ln%20Bonn`.
```suggestion
  Example of adding a query parameter using `property` method: `.property("URL.queries.airport", "Köln Bonn")`. 
  The rendered query string will look like: `airport=K%C3%B6ln%20Bonn`. 
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Removed unnecessary warning messages when not having an XSUAA or IAS service bound to the application.
```suggestion
- We removed unnecessary warning messages when generated when an XSUAA or IAS service is not bound to an application.
```

2021-09-13 13:46 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  processing those responses. This is fixed now and should handle headers the same way, regardless of capitalization.
```suggestion
- We fixed the issue where HTTP header keys of an OData response were not handled case-insensitive, causing problems with processing those responses. 
This is fixed now and should handle headers the same way, regardless of capitalization.
```

2021-09-13 13:50 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +functionResult = batchResponse.getReadResult(singleValueReturnFunction);
Yes, that is documented indeed. I'll link it here.

2021-09-13 13:51 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +You can also add functions that return a collection inside batch requests and parse the results in similar manner.
```suggestion
You can also add functions that return a collection inside batch requests and parse the results yourself in a similar manner.
Please refer to [our documentation](https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v2-client-in-sap-cloud-sdk-for-java#execute-batch-request) for more details.
```

2021-09-13 13:53 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +  This can be activated in the following ways
```suggestion
  You can activate this feature in the following ways
```

2021-09-13 13:55 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +  **Note:** This means that token set via the `AuthTokenAccessor.executeWith(...)` will **not** be forwarded to the target system.
```suggestion
  **Note:** The settings above will override a token set with `AuthTokenAccessor.executeWith(...)`. Moreover, authentication tokens set via `AuthTokenAccessor.executeWith(...)` will **not** be forwarded to the target system. 
```

2021-09-14 11:20 UTC, artemkovalyov approved these changes
LGTM

2021-09-14 11:20 UTC, merged