Release Notes for Java Version 3.54.0
SAP/cloud-sdk pull request #471
Opened 2021-09-20 14:07 UTC by MatKuhr

2021-09-21 10:56 UTC, Johannes-Schneider requested changes

2021-09-21 10:56 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +### New Functionality
```suggestion
### Known Issues

- We are aware of the vulnerability [CVE-2021-37137](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-37137) that affects [Netty](https://netty.io/news/2021/08/16/4-1-67-Final.html) in version `4.1.67.Final`. Unfortunately, however, we are not yet able to resolve that vulnerability due to [an issue](https://github.com/netty/netty/issues/11691) with the `4.1.68.Final` release of Netty, which prevents projects from compiling. We will update the related dependencies once the build issue has been resolved. In the meanwhile, consumers of the SAP Cloud SDK do not need to worry about the vulnerability as it affects only internal and deprecated modules that are not recommended to use.

### New Functionality
```

2021-09-21 10:56 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +[Maven Central](https://search.maven.org/search?q=g:com.sap.cloud.sdk*%20AND%20v:3.54.0) | [Javadoc](https://help.sap.com/doc/55bb1642ea614bf582d514ed34401136/1.0/en-US/index.html)
Point to slightly less outdated Javadoc (`3.51.0`)

```suggestion
[Maven Central](https://search.maven.org/search?q=g:com.sap.cloud.sdk*%20AND%20v:3.54.0) | [Javadoc](https://help.sap.com/doc/0d9c3f5f8d874f99a32444910d7a3504/1.0/en-US/index.html)
```

2021-09-21 12:01 UTC, MatKuhr commented on docs/java/release-notes.mdx
> +### New Functionality
Thanks for adding this 👍🏻

2021-09-21 20:01 UTC, artemkovalyov reviewed
Please, consider my comments where you find them relevant.

2021-09-21 20:01 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  Instead, the `VCAP_SERVICES` environment variable will be parsed at runtime for the necessary information.
```suggestion
-  The SDK now passes tenant information via `zone ID` instead of a `subdomain` to both XSUAA and IAS OAuth2 services.
- Resolving the provider tenant no longer requires an internal HTTP request. 
  Instead, the `VCAP_SERVICES` environment variable will be parsed at runtime for the necessary information.
```

2021-09-24 09:02 UTC, Johannes-Schneider approved these changes
LGTM.

2021-09-24 10:26 UTC, merged