doc for forwarAuthToken
SAP/cloud-sdk pull request #476
Opened 2021-09-23 14:59 UTC by FrankEssenberger

## What Has Changed?

Add section for forwardAuthToken. See for implementation https://github.com/SAP/cloud-sdk-js/pull/1619.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-09-24 14:02 UTC, artemkovalyov requested changes
Please, consider my suggestions and comments. To my feeling, it's so concise that some valuable context is lost.

2021-09-24 14:02 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +Include the `forwardAuthToken` to the destination and your JWT will be forwarded directly as `Authorization` header to the target system.
```suggestion
Include the `forwardAuthToken` to the destination configuration and your `JWT` will be forwarded directly as `Authorization` header to all the target systems without an extra round trip to the destination service.
```

2021-09-24 14:02 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +All you
Seem like this line is incomplete?

2021-09-29 07:22 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +You can use an environment destination to overcome this issue.
I tried to be more explicit. Have a second look.

2021-09-29 07:22 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +All you
I tried to be more explicit. Have a second look.

2021-09-29 13:16 UTC, artemkovalyov requested changes

2021-09-29 13:16 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +In the case of frequent service to service communication, requesting the destination service every time for a target specific `JWT` would mean a big overhead.
```suggestion
In the case of frequent service to service communication, requesting the destination service every time for a target-specific `JWT` would mean a big overhead.
```

2021-09-29 13:16 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +This makes the call to the destination service for a target specific token redundant.
```suggestion
This makes the call to the destination service for a target-specific token redundant.
```

2021-09-29 13:16 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +If you configured your target system in such a way, you can use an environment destination to stop the destination lookup right away.
What's `environment destination`?  Should it be set as an environment variable? Can we link to that section?

2021-09-29 13:16 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +If you configured your target system in such a way, you can use an environment destination to stop the destination lookup right away.
In the example below, you provide the destination inline still referring to the environment variable.

2021-09-29 13:16 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +Note that this approach is not possible for multi tenant scenarios, because the destination services takes care
```suggestion
Note that this approach is not possible for multi-tenant scenarios, because the destination services takes care
```

2021-09-29 13:16 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +Note that this approach is not possible for multi tenant scenarios, because the destination services takes care
This sentence is still unfinished?

2021-09-29 13:27 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +If you configured your target system in such a way, you can use an environment destination to stop the destination lookup right away.
yes because the methods sets the destination in the envioremnt varialbes with some checks. It is explained above already in the same section.

2021-09-29 14:43 UTC, artemkovalyov approved these changes
Looks good. Thanks.

2021-09-29 14:43 UTC, merged