Elaborate on how we version the documentation
SAP/cloud-sdk pull request #528
Opened 2021-11-02 11:04 UTC by artemkovalyov

## What Has Changed?

As we discussed I added notes on documentation versioning.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)

2021-11-02 15:17 UTC, florian-richter reviewed
Looks good with some small suggestions for improvement.

2021-11-02 15:17 UTC, florian-richter commented on docs/js/release-policy.mdx
> +- We maintain only the **latest major release** of the SAP Cloud SDK for JavaScript.
```suggestion
- We only provide new features and fixes for the **latest major release** of the SAP Cloud SDK for JavaScript.
```

2021-11-03 10:01 UTC, artemkovalyov commented
@florian-richter , give it another look.

2021-11-03 14:43 UTC, marikaner requested changes
LGTM, but I would like to suggest other titles for the tabs. I think major and deprecated could be hard to understand.

2021-11-03 14:43 UTC, marikaner commented on docs/js/release-policy.mdx
> +<Tabs groupId="version" defaultValue="major" values={[ { label: 'v2', value: 'major' }, { label: 'v1', value: 'deprecated' } ]}>
Can we use `v1` and `v2` as technical references and `"Version 1"` and `"Version 2"` as titles for the tabs? I think that would make it very clear.

2021-11-03 15:41 UTC, artemkovalyov commented on docs/js/release-policy.mdx
> +<Tabs groupId="version" defaultValue="major" values={[ { label: 'v2', value: 'major' }, { label: 'v1', value: 'deprecated' } ]}>
As we always have just 2 versions I thought this will make it easier to maintain with keeping major a default.

2021-11-03 15:41 UTC, artemkovalyov commented on docs/js/release-policy.mdx
> +<Tabs groupId="version" defaultValue="major" values={[ { label: 'v2', value: 'major' }, { label: 'v1', value: 'deprecated' } ]}>
Also with "Version 1", "Version 2" it's somewhat unclear about the version of what. I'd say we can use SDK 1.x, SDK 2.x or smth like this.

2021-11-03 15:41 UTC, artemkovalyov commented on docs/js/release-policy.mdx
> +<Tabs groupId="version" defaultValue="major" values={[ { label: 'v2', value: 'major' }, { label: 'v1', value: 'deprecated' } ]}>
```suggestion
<Tabs groupId="version" defaultValue="major" values={[ { label: 'SDK 2.x', value: 'major' }, { label: 'SDK 1.x', value: 'deprecated' } ]}>
```

2021-11-08 14:48 UTC, marikaner approved these changes

2021-11-08 17:21 UTC, florian-richter approved these changes

2021-11-08 17:21 UTC, merged