Service Binding Loader API docs v2
SAP/cloud-sdk pull request #534
Opened 2021-11-03 15:10 UTC by andrastemesi-sap

## What Has Changed?

Added Service Binding Loader API docs
## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - [x] Every sentence is on its own line
  - [x] Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - [x] You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-11-03 16:45 UTC, artemkovalyov commented
Hey @andrastemesi-sap , are you using PNGs for code snippets or it's for smth else?

2021-11-03 16:48 UTC, artemkovalyov reviewed
A couple of fixes. Please let me know what are the PNGs for.

2021-11-03 16:48 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +SAP Cloud SDK provides functionality to load service binding information when running the application in any Kubernetes runtime.
```suggestion
SAP Cloud SDK provides functionality to load service binding information when running the application in any Kubernetes environment.
```

2021-11-03 16:48 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +The following four classes implement this interface.
```suggestion
An interface offers only one method to load the existing service bindings for the current application.
The abstract method named `load()` will have different functionality based on the subclass.
The following four classes implement this interface.
```

2021-11-03 20:36 UTC, andrastemesi-sap commented
> Hey @andrastemesi-sap , are you using PNGs for code snippets or it's for smth else?

@artemkovalyov it is for class diagrams. They provide visualization for the architecture.

2021-11-03 20:40 UTC, andrastemesi-sap commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +SAP Cloud SDK provides functionality to load service binding information when running the application in any Kubernetes runtime.
Done.

2021-11-03 20:44 UTC, andrastemesi-sap commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +The following four classes implement this interface.
Here I am not sure. "An interface offers..." sounds to me as if we were referring to Java interfaces in general. If you don't like the original, maybe it could be "An interface that offers...", or "This/It is an interface that offers...". But at the end of the day I am not a native speaker either.

2021-11-03 21:31 UTC, artemkovalyov requested changes
It's pretty well written. I like you've added class diagrams. I think I'll consider adding mermaid charts to simplify this in the future. Please, consider my suggestions so that we can merge it.

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +**Please note that the API is still in an experimental state at this time.**
```suggestion
:::note Experimental API

Please note that the API is currently in an experimental state.

::: 
```

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +**Please note that the API is still in an experimental state at this time.**
Do we annotate it as Beta?

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +The following four classes implement this interface.
Agree. I corrected for clarity. I now understand what you've tried to achieve with the gerund. But it makes the sentence look incomplete even though you refer to the heading.

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +Used for transforming file system structures (e.g. files and directories) into service bindings, starting at a specific root location based on the provided `ParsingStrategy`.
Here as well put the subject in. This class, interface, ... is used for ...

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +Used for transforming environment variables into service bindings based on the provided `ParsingStrategy`.
And again :)

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +Used for merging the result of an arbitrary amount of given instances based on the provided `MergingStrategy`.
And here :)

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +We suggest that `ScpCfCloudPlatform` is used when running in a Kubernetes environment.
```suggestion
We suggest using `ScpCfCloudPlatform` when running in a Kubernetes environment.
```

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +The above-mentioned architecture can be used by calling the `Map<String, JsonArray> getVcapServices()` method.
```suggestion
You can leverage the above-mentioned architecture by calling the `Map<String, JsonArray> getVcapServices()` method.
```

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +We suggest that `ScpCfCloudPlatform` is used when running in a Kubernetes environment.
Active voice is preferred and suits this case.

2021-11-03 21:31 UTC, artemkovalyov commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +The above-mentioned architecture can be used by calling the `Map<String, JsonArray> getVcapServices()` method.
Also here write things the way you'd explain to your friend. Probably even `leverage` is not the best word, but make it an active case. I also didn't get the relation between the first sentence and this one.

2021-11-08 09:43 UTC, andrastemesi-sap commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +**Please note that the API is still in an experimental state at this time.**
Yes

2021-11-08 15:09 UTC, artemkovalyov reviewed
I think JS supports it through the configuration

2021-11-08 15:09 UTC, artemkovalyov commented on docs/components/data/features.js
> +    }
```suggestion
    js: {
      status: YES,
      docsLink: `[docs](${baseUrl}/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes)`,
      note: `Bindings are handled via configuration`
    }
```

2021-11-08 18:44 UTC, artemkovalyov commented on docs/components/data/features.js
> +    }
Thanks for updating the feature matrix. I added a link to the guide from JS

2021-11-09 07:50 UTC, cschubertcs commented
Looks content wise good!
Maybe some more words on the different forms of K8S secrets would make sense, as right now only the diagram shows that those classes exist.

In general I was thinking that a separate document, maybe under `Features` would make sense, as this topic is not limited to K8S, but would be ussed also on e.g. CF or Kyma.

2021-11-09 11:08 UTC, MatKuhr reviewed
looks good, but let's move this to a dedicated section. I'll craft a new one and then update.

2021-11-09 13:26 UTC, MatKuhr commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +- Service Operator (Kubernetes) Secret Key layout
There is also the secret ROOT key I think

2021-11-09 13:28 UTC, MatKuhr reviewed
otherwise looks good

2021-11-09 13:28 UTC, MatKuhr commented on docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
> +SAP Cloud SDK provides functionality to load service binding information when running the application in any Kubernetes environment.
When moving this to a more general place, we should also point out that really the whole range is supported: CF and K8s (in particular Gardener and Kyma).

2021-11-09 19:40 UTC, artemkovalyov commented
I think suggestions from @cschubertcs and @MatKuhr are reasonable. Let's move and generalize it to match the format of a separate guide. It shouldn't take much effort.

2021-11-10 08:53 UTC, newtork approved these changes
Is there sample code available already?

2021-11-10 10:27 UTC, MatKuhr approved these changes

2021-11-10 10:27 UTC, merged