mention about on prem 2020 VDM
SAP/cloud-sdk pull request #55
Opened 2020-12-11 12:55 UTC by TanviiG

## What Has Changed?
 https://sapjira.wdf.sap.corp/browse/CLOUDECOSYSTEM-8825.
Documentation updated to mention about S/4HANA On prem VDM offered by Cloud SDK.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on it's own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)

2020-12-13 21:06 UTC, MatKuhr commented on docs/java/getting-started.mdx
> +If you want to use a type safe **OData** client library for [**SAP S/4HANA On-Premise 2020**](https://api.sap.com/package/S4HANAOPAPI?section=Artifacts) then the following dependency should be added
I think we should make the option not between V2 and V4 but instead between Cloud and on-premise. Usually people are going to use either cloud or on premise but rarely both. So in the on-premise case people should not use s4hana-all.

2020-12-14 08:41 UTC, TanviiG commented on docs/java/getting-started.mdx
> +If you want to use a type safe **OData** client library for [**SAP S/4HANA On-Premise 2020**](https://api.sap.com/package/S4HANAOPAPI?section=Artifacts) then the following dependency should be added
Done

2020-12-14 14:08 UTC, MatKuhr commented on docs/java/getting-started.mdx
> +<dependency>
We should also think about whether or not the other dependencies within `s4hana-all` are necessary. I think the `s4hana-connectivity` will be needed. I am not sure about `s4hana-core` as it contains some type conversion logic. To be safe I would also add that here since those two are no longer added via `s4hana-all` since that is for the cloud version.

2020-12-14 23:00 UTC, artemkovalyov approved these changes
I think it's generally LGTM.

2020-12-16 08:58 UTC, florian-richter requested changes
S/4HANA needs to be prefixed with SAP

2020-12-16 08:58 UTC, florian-richter commented on docs/java/features/odata/overview.mdx
> +  The most popular type-safe client module contains a collection of all OData services of [SAP S/4HANA Cloud](https://api.sap.com/package/SAPS4HANACloud?section=Artifacts) and [SAP S/4HANA On-premise
```suggestion
  The most popular type-safe client module contains a collection of all OData services of [SAP S/4HANA Cloud](https://api.sap.com/package/SAPS4HANACloud?section=Artifacts) and [SAP S/4HANA On-Premise 2020](https://api.sap.com/package/S4HANAOPAPI?section=Artifacts).
```

2020-12-16 08:58 UTC, florian-richter commented on docs/java/getting-started.mdx
> +The dependencies differ with respect to the type of **S/4HANA** system([**SAP S/4HANA Cloud**](https://api.sap.com/package/SAPS4HANACloud?section=Artifacts) or [**SAP S/4HANA On-Premise 2020**](https
```suggestion
The dependencies differ with respect to the type of **SAP S/4HANA** system([**SAP S/4HANA Cloud**](https://api.sap.com/package/SAPS4HANACloud?section=Artifacts) or [**SAP S/4HANA On-Premise 2020**](https://api.sap.com/package/S4HANAOPAPI?section=Artifacts)):
```

2020-12-16 08:58 UTC, florian-richter commented on docs/java/getting-started.mdx
> +<Tabs groupId="s4hana" defaultValue="s4hanacloud" values={[ { label: 'S/4HANA Cloud', value: 's4hanacloud', }, { label: 'S/4HANA On-Premise 2020', value: 's4hana_onpremise', }]}>
```suggestion
<Tabs groupId="s4hana" defaultValue="s4hanacloud" values={[ { label: 'SAP S/4HANA Cloud', value: 's4hanacloud', }, { label: 'SAP S/4HANA On-Premise 2020', value: 's4hana_onpremise', }]}>
```

2020-12-16 09:27 UTC, florian-richter approved these changes

2020-12-16 10:10 UTC, TanviiG commented on docs/java/getting-started.mdx
> +<dependency>
ok I understand I will add the two mentioned dependencies

2020-12-16 12:02 UTC, merged