update v2 docs
SAP/cloud-sdk pull request #553
Opened 2021-11-16 10:19 UTC by tomfrenken

## What Has Changed?

Since the execute and executeRaw APIs change in v2, this PR contains the tabs approach to show both examples.

2021-11-16 20:38 UTC, artemkovalyov requested changes
Please, take labels and values as they are in release policy. It will let us easier maintain things at scale in the future.

2021-11-16 20:38 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +<TabItem value="one">
Let's adopt the same Tabs naming and implementation as [here](https://github.com/SAP/cloud-sdk/blob/main/docs/js/release-policy.mdx). Then we'll have it uniform across our docs and changing versions will be a simple "find and replace". The value will universally stay the same which simplifies maintenance further. That's where unification will help a lot to my conviction.

2021-11-17 07:42 UTC, tomfrenken commented on docs/js/features/connectivity/destination.mdx
> +<TabItem value="one">
I agree, I've updated the docs with your approach 👍

2021-11-17 12:38 UTC, artemkovalyov approved these changes
LGTM, let's keep default value as deprecated before the release of v2

2021-11-17 12:38 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +<Tabs groupId="version" defaultValue="major" values={[
```suggestion
<Tabs groupId="version" defaultValue="deprecated" values={[
```

2021-11-17 12:38 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +<Tabs groupId="version" defaultValue="major" values={[
```suggestion
<Tabs groupId="version" defaultValue="deprecated" values={[
```

2021-11-18 18:19 UTC, merged