SAP Application Router Guide
SAP/cloud-sdk pull request #574
Opened 2021-12-06 11:47 UTC by tomfrenken

## What Has Changed?

I added a guide for the usage of the SAP Application Router. with the SAP Cloud SDK.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-12-06 14:56 UTC, artemkovalyov requested changes
It looks pretty good. Check my suggestions + run prettier on it.
Can we collect all of this in an App and push it to the samples repo?

2021-12-06 14:56 UTC, artemkovalyov commented on docs/js/guides/how-to-use-the-approuter.mdx
> +We will show you how to secure your application and utilize multi-tenancy for principal propagation with a nestJS example.
```suggestion
In this guide, we will show you how to use the SAP Application Router together with the SAP Cloud SDK.
You will learn how to secure your application and configure multi-tenancy for principal propagation with an SDK-based application example powered by [nestJS](https://nestjs.com/).
```

2021-12-06 14:56 UTC, artemkovalyov commented on docs/js/guides/how-to-use-the-approuter.mdx
> +Since we use an Identity Provider (IdP) to authenticate ourselves, the request is redirected to an IdP and then redirected back to the application router.
```suggestion
## SAP Application Router

When we want to enable multi-tenancy for our application, we use the [SAP Application Router](https://www.npmjs.com/package/@sap/approuter).
The application router’s primary purpose is to be the single entry point of a microservice-based application and act as the application’s reverse proxy.
Its responsibilities consist of dispatching requests to backend microservices, authenticating users, and serving static content.
The application router checks if a given request has a valid JSON Web Token (JWT) when accessing a target service.
If the request contains a valid JWT, the application router forwards the request to the target service; if the request does not contain a valid JWT, the user must authenticate.
Since we use an Identity Provider (IdP) to authenticate, the request is redirected to an IdP where a user gets authenticated and then redirected back to the application router for passing further according to its desired destination.
```

2021-12-06 14:56 UTC, artemkovalyov commented on docs/js/guides/how-to-use-the-approuter.mdx
> +Since we use an Identity Provider (IdP) to authenticate ourselves, the request is redirected to an IdP and then redirected back to the application router.
A simple diagram here would have been great! Should we try to use mermaid?
I'll send you a code snippet.

2021-12-06 14:56 UTC, artemkovalyov commented on docs/js/guides/how-to-use-the-approuter.mdx
> +We can optionally also specify a specific `identityProvider` which is used for the authentication.
```suggestion
We can optionally also specify a specific `identityProvider` that is used for the authentication.
```

2021-12-06 14:56 UTC, artemkovalyov commented on docs/js/guides/how-to-use-the-approuter.mdx
> +To deploy our approuter in SAP BTP Cloud Foundry, we need to configure it first.
```suggestion
### Approuter Setup

To deploy our approuter in SAP BTP Cloud Foundry, we need to configure it first.
```

2021-12-06 14:56 UTC, artemkovalyov commented on docs/js/guides/how-to-use-the-approuter.mdx
> +To secure our application endpoints, we utilize the [passport](http://www.passportjs.org/packages/passport-jwt) library.
```suggestion
## Securing your Application

To secure our application endpoints, we utilize the [passport](http://www.passportjs.org/packages/passport-jwt) library.
```

2021-12-06 14:57 UTC, artemkovalyov commented
Can you remove package-loc.json for now? Or re-run the install as some dependencies were updated. I also want to add mermaidJS for diagrams.

2021-12-15 11:40 UTC, tomfrenken commented
@artemkovalyov I've added a mermaid diagram and removed the package.json changes.

2021-12-16 10:57 UTC, artemkovalyov approved these changes
Look good

2021-12-16 12:44 UTC, merged