Discussion basis for meeting
SAP/cloud-sdk pull request #599
Opened 2020-10-19 15:55 UTC by FrankEssenberger

## Context

Some draft for the discussion.

2020-10-21 15:53 UTC, marikaner commented
Should this be merged?

2020-10-22 08:35 UTC, FrankEssenberger commented
Not yet. When I added my recherche on the two topics I move the status to ready for review.

2020-10-23 11:34 UTC, FrankEssenberger commented
Here with the questions answer. @artemkovalyov you wanted to investigate how other people solve the problem of dynamic log level setting. Feel free to put you findings to the document `dynamic-log-levels.md`

2020-10-26 00:30 UTC, artemkovalyov commented
@FrankEssenberger, after asking around in our JS slack group and a couple of friends JS devs who work on Node backend projects the suggestions were like this:

- [Open Telemetry for JS](https://github.com/open-telemetry/opentelemetry-js) - 3 votes, tracing framework, Node 10 and above, web-supported.
- [CLS-rtracer](https://github.com/puzpuzpuz/cls-rtracer) - a lib on top of AsyncLocalStorage, has NPM package, up to date
- The offered pattern was always to pass the context around down the calling stack to access tracing ID, etc.

I think we can take a look at the two libs above and maybe have a quick PoC with the most promising. They can maybe offer more than just context with setting some request headers, autogenerating tracing id's and letting customizing tracing parameters to take care of tenant-id, etc. cc @marikaner @jjtang1985

2020-10-26 08:57 UTC, artemkovalyov requested changes
@FrankEssenberger , I added my findings in the comment. If you find them relevant let's add them to the options, otherwise, we can consider this done.

2020-10-26 09:58 UTC, FrankEssenberger commented
I added them but I think for the current problem we do not really get much from the two libs.

2020-10-26 11:45 UTC, artemkovalyov approved these changes
Thanks for evaluating what the community suggested.

2020-10-26 15:21 UTC, artemkovalyov commented
> I added them but I think for the current problem we do not really get much from the two libs.

Sure, still the latter validates partially the use of a AsyncLocalStore. Also, that would be our way I'd skip support for this particular feature for Node <13 and clearly communicate this in the docs. We can ask if this makes sense for the customer.

2020-10-26 15:28 UTC, FrankEssenberger commented on knowledge-base/architectural-decisions-records/logging-cls-storage.md
> +  - Via a `withTenantLogging` method on the request builder permanently in the code if your application wants it.
Also fine. We provide a central method on the logger which can be used to switch it on.

2020-10-26 15:29 UTC, FrankEssenberger commented on knowledge-base/architectural-decisions-records/dynamic-log-levels.md
> +It seems like the lib can not be used directly since it does not consider really dynamic adjustment, the same as winston.
yes added the link also here.

2020-10-26 15:40 UTC, FrankEssenberger commented
> > I added them but I think for the current problem we do not really get much from the two libs.
> 
> Sure, still the latter validates partially the use of a AsyncLocalStore. Also, that would be our way I'd skip support for this particular feature for Node <13 and clearly communicate this in the docs. We can ask if this makes sense for the customer.

I would switch it off per default. An explain in the docs that you can switch it on for node 12,13 and 14 and explain that for node < 14 it has severe performance implications.

2020-10-27 09:23 UTC, merged