Add SAP Cloud SDK CLI documentation
SAP/cloud-sdk pull request #64
Opened 2020-12-16 08:08 UTC by florian-richter

## What Has Changed?

Documentation for the SAP Cloud SDK CLI that goes into detail on each of the commands.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on it's own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)

2020-12-17 17:02 UTC, marikaner requested changes
Looks good, there are just a few points to take into consideration.

2020-12-18 08:16 UTC, FrankEssenberger commented on docs/community/tech-ed.mdx
> +You'll find detailed instructions on how to do it in the `README` of the repository.
Which readme and repository is referred here to? Perhaps a link.

2020-12-18 09:05 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +$ sap-cloud-sdk add-cds
Are the two commands the same or does `sap-cloud-sdk init --addCds` the init and add cds whereas `sap-cloud-sdk addCds` does no init and only ads the cds? If this is the case I would spend an extra sentence like:
`Either directly in the init step: XXX or later in an already existing project via YYY`

2020-12-18 09:21 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +- `--force`: Do not fail if a file or npm script already exists and overwrite it.
does this also avoid yes/no question?

2020-12-18 09:25 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +If you don't know the command at this moment, you can adjust it manually in the `manifest.yml`.
This is of course correct. However, for the node buildpack it will run `npm start` per default and there is not need to set it all. Also you can pass it in the command line. Perhaps you can link this article https://docs.cloudfoundry.org/devguide/deploy-apps/start-restart-restage.html and say that we will focus on the command for starting the app in the manifet.

2020-12-18 09:25 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +The consent is maintained in the `sap-cloud-sdk-analytics.json`.
```suggestion
The consent is stored in the `sap-cloud-sdk-analytics.json`.
```

2020-12-18 11:01 UTC, florian-richter commented on docs/js/features/cli/generator.mdx
> +title: Generate Clients for OData
I would recommend to document both generators in this file, therefore `generator.mdx`. But I'd be happy to adjust.

2020-12-18 11:05 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +This is possible for any existing project that uses `npm`.
we use `npm` install in the CLI. this will cause issues in yarn projects.

2020-12-18 11:28 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +Add frontend-related npm scripts which are executed by our CI/CD toolkit.
This is copy paste from the CLI help.

2020-12-18 11:31 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +When deploying to Cloud Foundry, it needs to know the command to start your application.
"It" is Cloud Foundry. I don't think the suggestion improves the sentence.

2020-12-18 11:38 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +If you prefer different tooling, we recommend you set up your project first and use the CLI to add the SAP Cloud SDK afterward.
https://grammarist.com/usage/afterward-afterwards/ 

> There is no difference between afterward and afterwards. Neither is more correct or incorrect than the other, and both appear throughout the English-speaking world. North American writers tend to favor afterward, while English speakers from outside the U.S. and Canada tend to favor afterwards. But this is not a rule, and exceptions are easily found.

Therefore it is more consistent to use afterward as the rest of the text is US English.

2020-12-18 11:58 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +If you don't know the command at this moment, you can adjust it manually in the `manifest.yml`.
The CLI requires the user to enter something so I rather not confuse the user by saying it is optional in the CF CLI but not in the SDK CLI

2020-12-18 11:58 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +- `--force`: Do not fail if a file or npm script already exists and overwrite it.
no, usually it throws if it encounters files or scripts that already exists.

2020-12-18 12:38 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +If you give your consent, the SAP Cloud SDK will collect some anonymized information on your project and computer.
This is copy-pasted from the linked guide (https://github.com/SAP/cloud-sdk-cli/blob/main/usage-analytics.md)

2020-12-18 13:09 UTC, marikaner commented on docs/js/features/cli/generator.mdx
> +title: Generate Clients for OData
Sounds good to me

2020-12-18 13:10 UTC, marikaner commented on docs/js/features/cli/generator.mdx
> +Right now the generator need to be installed globally to be called through the CLI.
```suggestion
Right now the generator needs to be installed globally to be called through the CLI.
```

2020-12-18 13:11 UTC, marikaner commented on docs/js/features/cli/generator.mdx
> +In the future the OData generator, the OpenAPI generator and the CLI will be integrated.
I would formulate that a little more vague. This basically is a promise and future might be never...

2020-12-18 13:13 UTC, marikaner commented on docs/js/features/cli/init.mdx
> +This is possible for any existing project that uses `npm`.
We should fix that. I guess there is no simple workaround? If yes, mention it here, if not consider creating a ticket for fixing that...

2020-12-18 13:16 UTC, marikaner approved these changes
LGTM

2020-12-18 13:20 UTC, FrankEssenberger approved these changes
LGTM only minor comments. Enjoy your holidays after merging.

2020-12-18 13:20 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +After the initialization is finished, the CLI displays the recommended next steps.
Perhaps add one sentence that these steps are necessary to configure the deployment to CF. Than it is clear what you are going to do.

2020-12-18 13:20 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +Manual deployments can be helpful in the beginning but are strongly discouraged for productive environments.
```suggestion
Manual deployments via [cf push](https://docs.cloudfoundry.org/devguide/push.html) can be helpful in the beginning but are strongly discouraged for productive environments.
```

2020-12-18 13:20 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +The new project will be based on the nest CLI.
At least on their homepage they call it `Nest` or `NestJS` https://docs.nestjs.com/. So we should also use a capital `N`.

2020-12-18 13:20 UTC, FrankEssenberger commented on docs/js/features/cli/init.mdx
> +Of course, it also includes the most current version of the SAP Cloud SDK as a dependency.
I think we do not want to use phrases like `Of course`, `easiliy`, `obviously` etc.

2020-12-18 13:20 UTC, FrankEssenberger commented on docs/overview/feature-matrix.mdx
> +- SAP Cloud SDK for JavaScript/TypeScript ships one client library npm package per SAP S/4HANA service.
`one client library npm package` is hard to read. Perhaps: the client library for each S/4HANA serivce are shipped as seperate npm packes.

2020-12-18 15:51 UTC, florian-richter commented on docs/js/features/cli/init.mdx
> +This is needed for any project that is built with TypeScript or Babel.
But `ts-node` is not available on CF and slower than compiled TS so I don't think this is recommended.

2020-12-18 16:00 UTC, merged