[Java] 3.63.0 Release Notes
SAP/cloud-sdk pull request #671
Opened 2022-02-04 10:26 UTC by cschubertcs

## What Has Changed?

Add release notes for version `3.63.0`.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-02-04 10:36 UTC, MatKuhr commented on docs/java/release-notes.mdx
> +- Javadoc: <https://help.sap.com/doc/e95b7f89bb45412b943760333df7a016/1.0/en-US/index.html>
autoformatting I guess, but not sure why these brackets are added...

2022-02-04 10:36 UTC, MatKuhr approved these changes

2022-02-04 11:07 UTC, newtork commented on docs/java/release-notes.mdx
> +- Javadoc: <https://help.sap.com/doc/e95b7f89bb45412b943760333df7a016/1.0/en-US/index.html>
I wasn't aware this is [proper Markdown syntax](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses)

2022-02-06 21:01 UTC, artemkovalyov requested changes
I'd suggest this clarity adjustment. Let me know if they make sense.

2022-02-06 21:01 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  This method can be used to to exclude read-only fields, as well as dependent properties that are not tied to key properties from your `PUT` request payload.
```suggestion
- Update the OData VDM to the [newest release 2202 of SAP S/4HANA Cloud](https://blogs.sap.com/2022/01/26/highlights-of-the-sap-s-4hana-cloud-2202-release/).
  This includes completely new services available as usual in packages: 
 - `com.sap.cloud.sdk.s4hana.datamodel.odata.services` 
 - `com.sap.cloud.sdk.s4hana.datamodel.odatav4.services`
 You will also find new operations in previously existing services, and new entity types.
  The SDK supports all OData services listed in the [SAP API Business Hub for SAP S/4HANA Cloud](https://api.sap.com/products/SAPS4HANACloud/overview).
- Add a new method (`excludingFields(...)`) to exclude specific fields from OData V2 and V4 `PUT` requests (i.e. `replacingEntity()`).
  This method can be used to exclude read-only fields, as well as dependent properties that are not tied to key properties from your `PUT` request payload.
```

2022-02-07 08:44 UTC, cschubertcs commented on docs/java/release-notes.mdx
> +- Fix an issue with Destination initialization, where the `"Authorization"` header value is constructed with improper scheme capitalization: e.g. instead of `"bearer [...]"` it will now correctly con
I would make a small adaptation to remove the duplicate `now` in the second sentence.
But reads much better!

2022-02-07 08:46 UTC, cschubertcs commented on docs/java/release-notes.mdx
> +- Javadoc: <https://help.sap.com/doc/e95b7f89bb45412b943760333df7a016/1.0/en-US/index.html>
True, not necessary.
But yes, you can wrap links in `<...>`. Not sure what the benefit of this is, besides limiting their "length" (so that text doesn't become part of the link by accident).
```suggestion
- Javadoc: https://help.sap.com/doc/e95b7f89bb45412b943760333df7a016/1.0/en-US/index.html
```

2022-02-08 20:16 UTC, artemkovalyov approved these changes
LGTM

2022-02-10 21:12 UTC, artemkovalyov commented
@Johannes-Schneider, what about merging this? The release is through.

2022-02-11 09:23 UTC, merged