chore: add some docuementation one resilience
SAP/cloud-sdk pull request #680
Opened 2022-02-08 15:40 UTC by FrankEssenberger

## What Has Changed?

Added some information on resilience. This should be merged after this PR: https://github.com/SAP-samples/cloud-sdk-js/pull/92 is in.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
~~- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~~

2022-02-08 16:42 UTC, marikaner commented on docs/js/features/connectivity/destination-cache-isolation.mdx
> +The `JWT` contains a `user_id` but the destination flow is user<span class="x x-first x-last">-</span>independent.
Why do we need the "<span class="x x-first x-last">-</span>" foo? We didn't do that above for "multi-tenant"

2022-02-08 17:17 UTC, marikaner requested changes
I like it, but have some suggestions.

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +In general, a circuit-breaker is a safety part preventing your wires to melt in case to much power is consumed.
```suggestion
In electronics, a circuit-breaker is a safety device preventing your wires to melt in case too much power is consumed.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +In software development the circuit-breaker does not protect actual wires from melting but resources from overloading and helping them recover.
```suggestion
In software development, the circuit-breaker does not protect actual wires from melting but resources from overloading, while helping them recover.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +Circuit-breakers are typically used for HTTP request and behave in the following way:
```suggestion
Circuit-breakers are typically used for HTTP requests and behave in the following way:
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- From this moment, requests are directly blocked and not executed.
```suggestion
- From this moment on, requests are immediately blocked and not executed.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +  This prevents the system from getting to many requests if it is in a unhealthy state.
```suggestion
  This prevents the system from getting too many requests if it is in an unhealthy state.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +Many circuit-breakers do not close to 100% directly, but go to a half-open state.
```suggestion
Many circuit-breakers do not go into a complete closed state, but go into a half-open state.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- FailureThreshold: Failure rate above which the circuit-breaker will open.
Maybe write it like this:
```suggestion
- "failure threshold": Failure rate above which the circuit-breaker will open.
```

This does not imply that this is an existing variable name (because of PascalCase) - it just describes the parameter.

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +We prepared an example using the [opossum](https://nodeshift.dev/opossum/) circuit-breaker in our [samples repository](https://github.com/SAP-samples/cloud-sdk-js/samples/resilience-examples).
```suggestion
You can find an example using the [opossum](https://nodeshift.dev/opossum/) circuit-breaker [here](https://github.com/SAP-samples/cloud-sdk-js/samples/resilience-examples).
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +Also for this pattern there are libraries available like [async-retry](https://www.npmjs.com/package/async-retry) which makes every asynchronousyarn method perform some retries if they do not resolve
```suggestion
For retries there are libraries available like [async-retry](https://www.npmjs.com/package/async-retry) which make every asynchronous function perform some retries if they do not resolve.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +Also if something fails consistently, it does not help to press the same button multiple times.
Not sure if this sentence is needed ;)
```suggestion
Also, if something fails consistently, it does not help to press the same button multiple times.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- The source of error is out of your domain to fix.
```suggestion
- The source of the error is out of your domain to fix.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- Consistent errors should not trigger a retry. For example a HTTP request failing with 401 should not trigger a retry because the user is simply unauthorized.
```suggestion
- Consistent errors should not trigger a retry. For example an HTTP request failing with 401 should not trigger a retry because the user is simply unauthorized.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- The number of retires should be limited to a low digit number and there should be some appropriate waiting time between retires.
```suggestion
- The number of retires should be limited to a low digit number and there should be some appropriate waiting time between retries.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- Fallback: Something to be done when the breaker is open.
Maybe also consider: The part after the colon is not a real sentence, so it shouldn't have a `.` in the end.

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- minTimeout: How long is the initial waiting time for the first retry.
Same as above, consider:
```suggestion
- "mininmum timeout": initial waiting time for the first retry
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +- Bail: A option to stop the retry for certain failure cases is useful in many cases.
```suggestion
- Bail: An option to stop the retry for certain failure cases is useful in many cases.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +  Also adding some random time deviation is distributing the load of parallel retires.
```suggestion
  Also adding some random time deviation is distributing the load of parallel retries.
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +We prepared an example using the [async-retry](https://www.npmjs.com/package/async-retry) library in our [samples repository](https://github.com/SAP-samples/cloud-sdk-js/samples/resilience-examples).
```suggestion
You can find an example using the [async-retry](https://www.npmjs.com/package/async-retry) library [here](https://github.com/SAP-samples/cloud-sdk-js/samples/resilience-examples).
```

2022-02-08 17:17 UTC, marikaner commented on docs/js/guides/how-to-add-resilience.mdx
> +If you use retries together with a circuit-breaker chose the options for the two accordingly.
```suggestion
If you use retries together with a circuit-breaker choose the options for the two accordingly.
```

2022-02-09 16:04 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination-cache-isolation.mdx
> +The `JWT` contains a `user_id` but the destination flow is user<span class="x x-first x-last">-</span>independent.
I think artem introduced this because the line breaks are nicer with this `-` but is is only for formating I think @artemkovalyov  perhaps you can comment?

2022-02-10 13:18 UTC, merged