doc: Add documentation on transpilation
SAP/cloud-sdk pull request #681
Opened 2022-02-08 16:37 UTC by marikaner

## What Has Changed?

I added some docs on how the OData generator is influenced by dependencies and transpilation. I am not sure whether it is explained too complicated...
After the first feedback round I would add a similar documentation on OpenAPI.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-02-09 16:39 UTC, florian-richter requested changes
I think it should be split into 2 sections. 

1. Generate using the generator as a global dependency
2. Generate using the generator as a devDependency

It should have pretty clear and easy commands that a basic user can copy/paste without thinking too much.
Advanced users would probably also like to understand the why and get a recommendation.

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +By default, it transpiles the generated sources to JavaScript and provides a `package.json` for the client (this differs from the OpanAPI generator).
```suggestion
By default, it transpiles the generated sources to JavaScript and provides a `package.json` for the client (this differs from the OpenAPI generator).
```
As a reader I ask myself: Why does it provide a `package.json`? Especially if I need to install dependencies manually anyways...

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +Therefore, for transpilation you need a local reference to those packages.
```suggestion
Therefore, you need a local reference to those packages for transpilation.
```

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +The generated clients depend on the `@sap-cloud-sdk/odata-v2` or `@sap-cloud-sdk/odata-v4` packages, depending on the OData version of the service.
```suggestion
The generated clients depend on the `@sap-cloud-sdk/odata-v2` or `@sap-cloud-sdk/odata-v4` packages, depending on the OData version of the service.
```
As a reader: Is this reflected in the generated package.json?

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +Those packages are not installed for you, so that you can decide where to install them (e.g. in your project or in the subdirectory of your client).
```suggestion
Those packages are not installed automatically. You need to install them either in your project or in the client directory.
```
Installing in the client directory is (AFAIK) not possible without at least running the build once before (either failing it during transpilation or skipping transpilation via flag). Then you would need to run the generator again but make sure to not "cleanOutputDir"... otherwise the dependency is gone again and it fails...

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +If you installed the generator globally, transpilation will fail unless you install the required odata packages.
```suggestion
If you installed the generator globally, transpilation will fail unless you install the required package (`sap-cloud-sdk/odata-v2` or `sap-cloud-sdk/odata-v4`).
```

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +If you installed the generator as a `devDependency`, transpilation will work, however, for productive use, you may have to define the dependency productively.
I am confused... if this is the case why would I install it as a devDependency in the first place? But why would this be the case? Why "may have to"? What is different in production?

2022-02-09 16:39 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +If you installed the generator as a `devDependency`, transpilation will work, however, for productive use, you may have to define the dependency productively.
```suggestion
If you installed the generator as a `devDependency`, transpilation will work automatically.
However, for productive use, you may have to define the dependency productively.
```

2022-02-10 15:08 UTC, marikaner commented
> I think it should be split into 2 sections.
> 
> 1. Generate using the generator as a global dependency
> 2. Generate using the generator as a devDependency
> 
> It should have pretty clear and easy commands that a basic user can copy/paste without thinking too much. Advanced users would probably also like to understand the why and get a recommendation.

Thank you for the feedback, I changed quite a lot and turned it around a bit. I had the separation mentioned by you, but changed it a bit again. Not sure if this is a "Verschlimmbesserung" ;)

Let me know what you think

2022-02-10 16:35 UTC, florian-richter commented on docs/js/features/odata/generate-odata-client.mdx
> +If you want to generate JavaScript code and install the generator globally, you have to install the `@sap-cloud-sdk/odata-v2` or `@sap-cloud-sdk/odata-v4` package in your project.
This seems helpful 👍 I like it

2022-02-11 13:21 UTC, marikaner commented on docs/js/features/odata/generate-odata-client.mdx
> +You can use the SAP Cloud SDK generator both as a command-line interface (CLI) and programmatically.
I removed the passive voice, that's why ;)
Now, I changed it a bit, let me know what you think.

2022-02-15 08:18 UTC, florian-richter approved these changes

2022-02-15 08:19 UTC, merged