chore: add documentation on query parameter with priority
SAP/cloud-sdk pull request #707
Opened 2022-02-25 13:22 UTC by FrankEssenberger

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-03-04 12:49 UTC, tomfrenken approved these changes
LGTM - just a few notes

2022-03-04 12:49 UTC, tomfrenken commented on docs/js/features/connectivity/query-parameters.mdx
> +In this document we explain where how query parameters
What?

2022-03-04 12:49 UTC, tomfrenken commented on docs/js/features/connectivity/query-parameters.mdx
> +- Provided by user on request level.
```suggestion
- Provided by the user on request level.
```

2022-03-04 12:49 UTC, tomfrenken commented on docs/js/features/connectivity/query-parameters.mdx
> +For version 1.0 encoding is done one OData related query parameters without a way to configure it.
```suggestion
For version 1.0 encoding is done on OData related query parameters without a way to configure it.
```

2022-03-04 15:29 UTC, florian-richter requested changes

2022-03-04 15:29 UTC, florian-richter commented on docs/java/release-policy.mdx
> +- compatibility to latest features of SAP Business Technology Platform
I agree that this should be changed, but someone from the Java team should review as I don't think it's our place to change their release policy (ping @MattKuhr)

2022-03-04 15:29 UTC, florian-richter commented on docs/js/features/connectivity/query-parameters.mdx
> +As partially described in the [destination guide](./destination#additional-headers-and-query-parameters-on-destinations) there are multiple origins for query parameters:
```suggestion
As partially described in the [destination guide](./destination#additional-headers-and-query-parameters-on-destinations), there are multiple possible origins for query parameters:
```

2022-03-04 15:29 UTC, florian-richter commented on docs/js/features/connectivity/query-parameters.mdx
> +or the `executeHttpRequest` method of the generic http-client:
```suggestion
or the `executeHttpRequest` method of the generic `http-client`:
```

2022-03-04 15:29 UTC, florian-richter commented on docs/js/features/connectivity/query-parameters.mdx
> +In the newer version we allow to specify the origin of the header, whereas for version 1.0 it is `custom` per default.
```suggestion
In version 2, we allow to specify the origin of the header. 
For version 1, it is always `custom`.
```

2022-03-04 15:29 UTC, florian-richter commented on docs/js/features/connectivity/query-parameters.mdx
> +Note the difference between version 1.0 and 2.0 of the SAP Cloud SDK.
```suggestion
Note the difference between version 1 and 2 of the SAP Cloud SDK.
```

I think we should not use `X.0` when referring to these versions as this implies it is only for that specific minor release.

2022-03-04 15:29 UTC, florian-richter commented on docs/js/features/connectivity/query-parameters.mdx
> +Note the difference between version 1.0 and 2.0 of the SAP Cloud SDK.
Do you know if we have a docs style guide where we could mention this?

2022-03-04 15:29 UTC, florian-richter commented on docs/js/features/connectivity/query-parameters.mdx
> +The `parameterEncoder function is applied to the keys and values of all parameters of the request. In case you have the need to encode all parameters also the custom ones, we exported a `encodeAllPar
```suggestion
The `parameterEncoder` function is applied to the keys and values of all parameters of the request. 
In case you have the need to encode all parameters including custom ones, we exported a `encodeAllParameters` method to do that. 
Simply pass this method as the `parameterEncoder` to the `executeHttpRequest` call.
```

2022-03-09 08:18 UTC, FrankEssenberger commented on docs/java/release-policy.mdx
> +- compatibility to latest features of SAP Business Technology Platform
You are right @florian-richter . Vale was complaining about it and made the build red for me would be great if a java colleague could comment.

2022-03-09 08:20 UTC, FrankEssenberger commented on docs/js/features/connectivity/query-parameters.mdx
> +Note the difference between version 1.0 and 2.0 of the SAP Cloud SDK.
I agree and I will try to remember not to use the `.` versions. I do not know if there is a style guide...

2022-03-10 09:44 UTC, FrankEssenberger commented
ON epositive review other points tackeled as well.

2022-03-10 09:44 UTC, merged