[Java] Release Notes 3.67.0
SAP/cloud-sdk pull request #782
Opened 2022-04-14 12:33 UTC by KavithaSiva

## What Has Changed?

This PR adds the Java release notes for the latest Cloud SDK release (3.67.0).

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] ~You verified all new and changed links still work (changing the `id` or name of a file can break links)~
- [x] ~You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~

2022-04-22 10:44 UTC, artemkovalyov requested changes
Take a look at my suggestions.

2022-04-22 10:44 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- To fix critical [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965) vulnerability in Spring, we had to update [Spring BOM](https://search.maven.org/search?q=g:org.springframework%2BA
```suggestion
- To fix the critical [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965) vulnerability in Spring, we had to update [Spring BOM](https://search.maven.org/search?q=g:org.springframework%2BAND%2Ba:spring-framework-bom) to `5.3.18` and to maintain compatibility had to also update [XSUAA Client Library](https://github.com/SAP/cloud-security-xsuaa-integration) to `2.11.15`.
```

2022-04-22 10:44 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  This deprecated module will remain in upcoming Cloud SDK v4.
```suggestion
- The module `auditlog-scp-cf` is considered **deprecated**.
  The audit logging API used to implement the integration is outdated and no longer adheres to product guidelines.
  In the future, Cloud SDK may provide an update leveraging the recommended API. Until then the users have an option to continue using the deprecated logic at their own risk, or directly consume the recommended audit logging API - without the Cloud SDK convenience layer.
  Please, create an issue here if you are interested in the consumption of `auditlog-scp-cf` via the SAP Cloud SDK.
  This deprecated module will be removed in the upcoming Cloud SDK v4.
  The module targeting Neo integration can be consumed as before.
```

2022-04-22 11:48 UTC, Johannes-Schneider commented on docs/java/release-notes.mdx
> +  This deprecated module will remain in upcoming Cloud SDK v4.
Based on @artemkovalyov suggestion, but with a link to ease the issue creation:

```suggestion
- The module `auditlog-scp-cf` is considered **deprecated**.
  The audit logging API used to implement the integration is outdated and no longer adheres to product guidelines.
  In the future, Cloud SDK may provide an update leveraging the recommended API. Until then the users have an option to continue using the deprecated logic at their own risk, or directly consume the recommended audit logging API - without the Cloud SDK convenience layer.
  Please, [create an issue](https://github.com/SAP/cloud-sdk/issues/new?assignees=&labels=feedback&template=feedback.md&title=) if you are interested in the consumption of `auditlog-scp-cf` via the SAP Cloud SDK.
  This deprecated module will be removed in the upcoming Cloud SDK v4.
  The module targeting Neo integration can be consumed as before.
```

2022-04-22 12:07 UTC, KavithaSiva commented on docs/java/release-notes.mdx
> +  This deprecated module will remain in upcoming Cloud SDK v4.
I am not sure about the removal of the module in V4, I thought the [decision](https://github.wdf.sap.corp/MA/sdk/pull/6798#issuecomment-4401144) taken was to continue shipping it in deprecated state in V4 too.

2022-04-25 10:32 UTC, KavithaSiva commented on docs/java/release-notes.mdx
> +This deprecated module will be kept in the upcoming [SAP Cloud SDK v4 and removed in the SAP Cloud SDK v5](https://sap.github.io/cloud-sdk/docs/java/release-policy)
I will be skeptical of saying that the module will be removed in SDK v5 and just mention that it will be available in SDK v4. This gives us flexibility I think. What do you think @artemkovalyov 

```suggestion
This deprecated module will be kept in the upcoming SAP Cloud SDK v4.
```

2022-04-26 13:40 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +This deprecated module will be kept in the upcoming [SAP Cloud SDK v4 and removed in the SAP Cloud SDK v5](https://sap.github.io/cloud-sdk/docs/java/release-policy)
Agree, you can remove it.

2022-04-26 13:45 UTC, merged