[js] truststore configuration
SAP/cloud-sdk pull request #795
Opened 2022-05-09 12:54 UTC by FrankEssenberger

Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/372

## What Has Changed?

Documentation for the trust store configuration added.

Closes SAP/cloud-sdk-backlog#372

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
~~- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~~

2022-05-09 14:09 UTC, marikaner commented on docs/java/release-notes.mdx
> +  Please, [create an issue](https://github.com/SAP/cloud-sdk/issues/new?assignees=&labels=feedback&template=feedback.md&title=) if you are interested in the consumption of `auditlog-scp-cf` via the S
??

2022-05-09 14:16 UTC, marikaner commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +2. The content of your conversation remains private ensure by some encryption
Those are sentences, so here you need a fullstop.

```suggestion
1. You are talking to the party you expect you talk to.
2. The content of your conversation is encrypted and therefore private.
```

2022-05-09 14:16 UTC, marikaner commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  ...
Vale! Maybe use `- etc.` ?

2022-05-09 14:54 UTC, FrankEssenberger commented
> I just started looking at the PR, but then realized, that the scope might be much more than we need. Do we really need to explain the background in such detail? I only expected to have the last to sections in our docs...

I totally agree that the scope is much more than needed, however I think the issue with trust versus authentication and the different formats are complicated and a comprehensive guide would have helped me.

2022-05-09 15:23 UTC, tomfrenken approved these changes
LGTM, just a few comments

2022-05-09 15:26 UTC, tomfrenken commented
To add to @FrankEssenberger comment, the trust setup was to me initially confusing as well, so I think it's fine (even though it's as you mentioned scoped bigger than just what the SDK does)

2022-05-10 07:24 UTC, marikaner commented
> > I just started looking at the PR, but then realized, that the scope might be much more than we need. Do we really need to explain the background in such detail? I only expected to have the last to sections in our docs...
> 
> I totally agree that the scope is much more than needed, however I think the issue with trust versus authentication and the different formats are complicated and a comprehensive guide would have helped me.

Makes a lot of sense to me. Do you think it would make sense to move these parts to the guides then? And just keep the feature related parts in the features section? Also @tomfrenken

2022-05-10 07:37 UTC, florian-richter requested changes
Sorry for the many comments. Hopefully these are all quick fixes.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +## Truststore Configuration
```suggestion
## Trust Store Configuration
```
[pp] As described above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +This is called `client certificate authentication` or two way SSL because the identity of server and client is verified using private and public keys.
```suggestion
This is called `client certificate authentication` or two-way SSL because the identity of server and client is verified using private and public keys.
```
[pp] see above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +### Two Way SSL
```suggestion
### Two-Way SSL
```
[pp] see above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +### One Way SSL
```suggestion
### One-Way SSL
```
[pp] Most online articles I found spell it with a hyphen: https://developer.visa.com/pages/working-with-visa-apis/two-way-ssl
[req] Disable SSL in the Heading Acronyms rule (or locally disable this rule)

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  ...
```suggestion
```
[pp] The introduction sentence for this list hints that this is not a complete list. Therefore no ellipsis is needed.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +To ensure this the secure socket layer (SSL) later called transport layer security (TLS) was developed.
```suggestion
To ensure this the secure socket layer (SSL) — later called transport layer security (TLS) — was developed.
```
[pp][q] I think an em dash looks better than commas. I used the proper em dash in the suggestion, though maybe we should agree if we use a proper em dash (—) or the shorter hyphen (-) as it is easier to type.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +2. The content of your conversation remains private ensure by some encryption
```suggestion
2. The content of your conversation remains private through the use of secure encryption
```
[nth] "some" makes it feel very vague. Is ROT13 also "some encryption"? It would certainly not make it a private conversation.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +1. You are actually talking to the person you think you talk
```suggestion
1. You are actually talking to the correct person, not an imposter 
```
[req] Grammar is wrong in the current version, but my recommendation is [pp]

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +- `Keystore`: A keystore is an object containing keys.
```suggestion
- Key store: A key store is an object containing keys.
```
[pp] See above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  You need a password to open a keystore.
```suggestion
  You need a password to open a key store.
```
[pp] See above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  Note that a keystore may also contain just a certificate but in general the term is used for the object containing pairs.
```suggestion
```
[nth] See above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  In most cases these are private and public key pairs as introduced above.
```suggestion
  Usually these are private and public key pairs as introduced above, but it may contain a certificate instead.
```
[nth] Combined this with the sentence below.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +- `Truststore`: A truststore contains public keys i.e. certificates.
```suggestion
- Trust store: A trust store contains public keys like certificates.
```
[pp] See above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  Depending on the format also a truststore is protected by a password.
```suggestion
  Some formats allow you to protect the trust store with a password.
```
[nth][pp] Passive voice and trust store.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  Typical formats are `.JKS`, `.CRT`, `.PEM` and `.PUB` and `.DER`.
```suggestion
  Typical formats are `.JKS`, `.CRT`, `.PEM`, `.PUB`, and `.DER`.
```
[req] Double "and"
[pp] Oxford comma

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  Typical formats are `.JKS`, `.P12`, `.PFCKS` and `.PKCS7`
```suggestion
  Typical formats are `.JKS`, `.P12`, `.PFCKS`, and `.PKCS7`
```
[pp][q] I prefer the Oxford comma. This should be decided in our docs style guide.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +For X.509 certificate there are two encodings base64 ASCII (e.g. `.PEM`) and binary (e.g. `.DER`).
```suggestion
For X.509 certificate there are two encodings: base64 ASCII (e.g. `.PEM`) and binary (e.g. `.DER`).
```
[pp] I think it reads much better with a colon.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +The SAP Cloud SDK does this for you if you maintain the truststore configuration via the destination service.
```suggestion
The SAP Cloud SDK does this for you if you maintain the trust store configuration via the destination service.
```
[pp] see above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +- Configure the destination to use [ClientCertificateAuthentication](sap destination service TrustStoreLocation) and provide the keystore information like keystore name and password.
`[ClientCertificateAuthentication](sap destination service TrustStoreLocation)`

[req] The link here needs to be configured correctly.

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +- Configure the destination to use [ClientCertificateAuthentication](sap destination service TrustStoreLocation) and provide the keystore information like keystore name and password.
```suggestion
- Configure the destination to use [ClientCertificateAuthentication](sap destination service TrustStoreLocation) and provide the key store information like key store name and password.
```
[pp] See above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +The SAP Cloud SDK for JavaScript supports only `.P12` and `.PFX` as formats for the keystore.
```suggestion
The SAP Cloud SDK for JavaScript only supports formats `.P12` and `.PFX` for key stores.
```

2022-05-10 07:37 UTC, florian-richter commented on styles/Vocab/SAP/accept.txt
> +truststore
```suggestion
```
[pp] see above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +title: How the SAP Cloud SDK handles Trust and Keystores
```suggestion
title: How the SAP Cloud SDK handles Trust and Key Stores
```
[pp] I think it should be spelled as two words when not in a code context (e.g. like in this _German_ wikipedia article: https://de.wikipedia.org/wiki/Certificate_Trust_Store)
[q] Is it "Trust- and Key Stores" or "Trust and Key Stores"?

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +sidebar_label: Trust and Keystores
```suggestion
sidebar_label: Trust and Key Stores
```
[pp] see above

2022-05-10 07:37 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +description: This article describes how configures trust and keystores in the SAP Business Technoligy Platform and how the SDK handles them..
```suggestion
description: This article describes how configures trust and key stores in the SAP Business Technology Platform and how the SAP Cloud SDK handles them..
```
[req] Type and SAP Cloud SDK
[pp] key store

2022-05-10 09:27 UTC, tomfrenken commented
Yes, I think splitting it up would be the cleanest approach.
Regarding @florian-richter comments, I think `keystore` and `truststore` are actually written like that since they are concepts, not literal key stores / trust stores (my Grammarly also considered them written wrong though). Although I see Wikipedia and article pages using both forms 🤔

2022-05-10 10:44 UTC, FrankEssenberger commented
I would prefer to write `keystore` and `truststore` as one word to indicated that I do not mean a store of trust and keys but the concept. But ther you can discuss. I thought about it and actually I would move the whole document to `guides` since there is not SDK setup needed. You just do it on the destination object and it should work.

2022-05-10 12:07 UTC, florian-richter commented
For me it feels obvious that "key store" is "key storage" rather than "place to buy keys". "Keystore" as one word would indicate it is a product or concept name (= a proper noun and therefore always capitalized). I don't think "keystore" (lowercase) as a closed compound word is correct as (to my knowledge) this is only occurs for very commonly used words that used to be open or hyphenated compound words (e.g. on-line -> online, e-mail -> email).

Therefore I am pro "key store" but I think the inconsistency how it is used in other articles makes it acceptable to use either spelling (therefore this is also marked [pp] everywhere 😉 )

2022-05-10 12:08 UTC, florian-richter commented on docs/js/features/connectivity/trust-and-key-stores.mdx
> +  Typical formats are `.JKS`, `.CRT`, `.PEM` and `.PUB` and `.DER`.
⬆️ this comment is still open

2022-05-17 08:25 UTC, marikaner approved these changes
LGTM.
I guess we don't need any docs in the features as this would be another case of works as designed right?

2022-05-17 13:58 UTC, merged