Replace and add new images
SAP/cloud-sdk pull request #807
Opened 2022-05-12 15:14 UTC by marikaner

## What Has Changed?

- Added some new images + improved the overview page for JS
- Removed some unused images
- Replaced some existing images

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-05-13 13:26 UTC, FrankEssenberger commented on static/img/.links.md
> +3. Select "Save as Picture...".
minor: there is a vale warning due to the `...`

2022-05-13 13:28 UTC, FrankEssenberger commented on static/img/.links.md
> +3. Select "Save as Picture...".
From the file name `.links.md` I did not know that it contained the description on `how-to-generate-images` - perhaps you can do something more explicit.

2022-05-13 13:39 UTC, FrankEssenberger commented on static/img/.links.md
> +3. Select "Save as Picture...".
Also could you either give here and/or in the PPT give some guidance how to get a dark mode version of an normal mode PPT - especially the imagines are not clear to me. Do you have to manually go to the SAP image DB and select the black version or can you invert it in power point?

2022-05-13 13:39 UTC, FrankEssenberger requested changes
Content wise fine. I left some comment regarding the image generation

2022-05-13 16:07 UTC, deekshas8 requested changes

2022-05-16 09:58 UTC, marikaner commented on docs/js/overview.mdx
> +They contain OData and OpenAPI specific abstractions, that the (pre-)generated client libraries use to expose their APIs.
I meant to express that this applies to pregenerated and generated clients. Maybe just omitting the word altogether would be better?

2022-05-16 09:59 UTC, marikaner commented on docs/js/overview.mdx
> +### The core libraries
```suggestion
### The Core Libraries
```

2022-05-16 09:59 UTC, marikaner commented on docs/js/overview.mdx
> +The HTTP client library is a very thin HTTP client, that allows you to execute requests by leveraging the concept of destinations.
```suggestion
The HTTP client library is a thin HTTP client, that allows you to execute requests by leveraging the concept of destinations.
```

2022-05-16 10:00 UTC, marikaner commented on docs/js/overview.mdx
> +The OData v1, v2 and OpenAPI libraries build the foundation for (pre-)generated client libraries.
```suggestion
The OData v2, v4, and OpenAPI libraries build the foundation for (pre-)generated client libraries.
```

2022-05-16 10:00 UTC, marikaner commented on docs/js/overview.mdx
> +### Pregenerated client libraries
```suggestion
### Pregenerated Client Libraries
```

2022-05-16 11:14 UTC, marikaner commented on docs/js/overview.mdx
> +They contain OData and OpenAPI specific abstractions, that the client libraries (custom and pregenerated) use to expose their APIs.
```suggestion
The OData v2, v4, and OpenAPI libraries build the foundation for client libraries (custom and pregenerated).
They contain OData and OpenAPI specific abstractions, that the client libraries use to expose their APIs.
```

2022-05-16 12:22 UTC, marikaner commented on static/img/.links.md
> +3. Select "Save as Picture...".
Removed all instructions from here and moved it to the PPT.

2022-05-16 14:49 UTC, deekshas8 approved these changes
With the updated package diagram, LGTM !

2022-05-17 14:06 UTC, FrankEssenberger approved these changes
Like the instruction in the pptx and the new file name.

2022-05-17 14:06 UTC, merged