docs(js): update logging.mdx
SAP/cloud-sdk pull request #814
Opened 2022-05-17 16:56 UTC by ZhongpinWang

## What Has Changed?

Update js docs `logging.mdx`. Relates to SAP/cloud-sdk-backlog#380, SAP/cloud-sdk-js#2481.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-05-18 07:34 UTC, florian-richter requested changes
Typo needs to be fixed, otherwise seems like an improvement 👍

2022-05-18 07:34 UTC, florian-richter commented on docs/js/features/logging.mdx
> +`cds.env.features.kibana_formatter` has higher priority than `NODE_ENV`.
```suggestion
If `cds.env.features.kibana_formatter` is set, it has a higher priority than `NODE_ENV`.
```
[nth] Clarity

2022-05-18 07:34 UTC, florian-richter commented on docs/js/features/logging.mdx
> +If using `nodejs_buildpack` on Cloud Foundary, `NODE_ENV` is set to `production` by default.
```suggestion
If using `nodejs_buildpack` on Cloud Foundry, `NODE_ENV` is set to `production` by default.
```
[req] Typo

2022-05-25 08:06 UTC, marikaner commented on docs/js/features/logging.mdx
> +and in the logs, you would find a related entry
```suggestion
and in the logs, you would find a related entry:
```

2022-05-25 08:14 UTC, marikaner requested changes
Just formatting and passive voice in the last sentences, no biggies.

2022-05-25 08:14 UTC, marikaner commented on docs/js/features/logging.mdx
> +`setLogLevel` > `level` field in `createLogger` > `setGlobalLogLevel` > default level `info`
[req] I had a hard time reading it, because I didn't know which part starts where, can you just make a list out of it?

2022-05-25 08:14 UTC, marikaner commented on docs/js/features/logging.mdx
> +`setLogFormat` > `format` field in `createLogger` > `setGlobalLogLevel` > default format determined by `NODE_ENV`
[req] Same here.
[q] If you make it a list, does it make sense to maybe start from the default and than go down in the order of granularity?

2022-05-25 08:14 UTC, marikaner commented on docs/js/features/logging.mdx
> +If `nodejs_buildpack` is used to deploy your app on Cloud Foundry, `NODE_ENV` is set to `production` by default.
[req] Try to provide passive voice. 
e.g. The SAP Cloud SDK provides two log formats...
[Google TW style guide](https://developers.google.com/style/voice?hl=en)

2022-05-25 09:20 UTC, ZhongpinWang commented on docs/js/features/logging.mdx
> +`setLogLevel` > `level` field in `createLogger` > `setGlobalLogLevel` > default level `info`
I changed it into a table.

2022-05-25 09:20 UTC, ZhongpinWang commented on docs/js/features/logging.mdx
> +`setLogFormat` > `format` field in `createLogger` > `setGlobalLogLevel` > default format determined by `NODE_ENV`
Same as above.

2022-06-02 07:50 UTC, marikaner requested changes
I just have one minor request for the tables - either change them to lists (which I would prefer) or add the missing headers.

2022-06-02 07:50 UTC, marikaner commented on docs/js/features/logging.mdx
> +| 4     | `info`                                             | default log level                             |
applies to both tables:

[pp] I think the table is a nice idea, but I also think that a list would be enough.
[req] If you keep the table, each column should have a header.

```suggestion
1. log level for a specific message context or logger (`setLogLevel('info', messageContextOrLogger)`)
2. `level` field in `createLogger` (`createLogger({..., level: "info"})`)
3. global log level (`setGlobalLogLevel('info')`)
4. default log level (`info`)
```

or

```suggestion
1. `setLogLevel('info', messageContextOrLogger)` - log level for a specific message context or logger
2. `createLogger({..., level: "info"})` - `level` field in `createLogger`
3. `setGlobalLogLevel('info')` - global log level
4. `info` (default log level)
```

2022-06-13 07:51 UTC, marikaner approved these changes
👍

2022-06-13 07:55 UTC, merged