[js] add documentation on dest properties
SAP/cloud-sdk pull request #825
Opened 2022-05-23 16:16 UTC by FrankEssenberger

## What Has Changed?

Add a short section on the destination properties which are considered by the SDK.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
~~- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~~

2022-05-24 12:23 UTC, marikaner requested changes
Mostly minor stuff, just one sentence, that I would really try to simplify and a few questions.

2022-05-24 12:23 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +This property leads to a header field `sap-client` with the specified value in the HTTP request.
[pp] "This property leads to" sounds a bit strange - The SDK does something with the property, which is just there.

```suggestion
The property `sap-client` is considered by the SAP Cloud SDK.
When this property is set, it is used as the header parameter `sap-client` with the specified value in the HTTP request to the target system.
```

2022-05-24 12:23 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +There are two destination property used to establish trust to systems using certificates not issued by trusted certificate authorities:
[req] Typo
[req] The sentence is hard to read

```suggestion
By default, SAP BTP only trusts certain certificate authorities.
If you want to make HTTPS requests against systems that use certificates from other certificate authorities, you can configure the following properties:
```

2022-05-24 12:23 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +<br />
[q] I think to keep the theme consistent everywhere, we shouldn't do this. How bad is it?
```suggestion
```

2022-05-24 12:23 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +/>
[q] General: I am not sure if it is worth creating images for all of these. Do you think it would be enough to just have one for all of them in the introduction of this section?

2022-05-27 11:43 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +<br />
Then there is no line break between the pictures.

2022-05-27 11:44 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +/>
I think so too. I will take one image and remove the other

2022-06-02 07:36 UTC, FrankEssenberger commented on docs/js/features/connectivity/destination.mdx
> +/>
ALso removed the other trust pic because it was to much.

2022-06-02 07:39 UTC, marikaner approved these changes
👍

2022-06-02 07:39 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +/>
👍

2022-06-02 07:54 UTC, merged