[JS] add information on custom JWT
SAP/cloud-sdk pull request #840
Opened 2022-06-02 13:13 UTC by FrankEssenberger

## What Has Changed?

Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/546

Add small info on custom JWTs

2022-06-03 08:50 UTC, marikaner requested changes
Why are there changes in the Java docs?

2022-06-03 08:50 UTC, marikaner commented on docs/java/features/multi-tenancy/thread-context.mdx
> +- `x-app-specific-header: customer-value`
[req] typo?
```suggestion
- `x-app-specific-header: custome-value`
```

2022-06-03 08:50 UTC, marikaner commented on docs/java/release-notes.mdx
> +- SAP Buisiness Rules OpenAPI client library received breaking change to the field `List<TextPredefinedResults> predefinedResults` which is renamed to `List<TextPredefined> predefined` after updating
[req] typo

```suggestion
- SAP Business Rules OpenAPI client library received breaking change to the field `List<TextPredefinedResults> predefinedResults` which is renamed to `List<TextPredefined> predefined` after updating to the latest version of the SAP Business Rules service
```

2022-06-03 08:50 UTC, marikaner commented on docs/js/guides/how-to-retrieve-jwt.mdx
> +In some cases you want to use a JWT which is not issued by the XSUAA and approuter.
[nth] Vale suggestion
```suggestion
Sometimes you want to use a JWT which is not issued by the XSUAA and approuter.
```

2022-06-03 08:50 UTC, marikaner commented on docs/js/guides/how-to-retrieve-jwt.mdx
> +In this case the SAP Cloud SDK will not do a validation but the destination service does.
[nth] Maye make it more active.
```suggestion
In this case the SAP Cloud SDK does not validate the token, but the destination service does.
```

2022-06-03 08:50 UTC, marikaner commented on docs/js/guides/how-to-retrieve-jwt.mdx
> +If you use such a custom JWTs without the approuter and XSUAA, it is your responsibility to do the access control on the application.
[req] typo
[q] Should access control be specified in more detail?
```suggestion
If you use a custom JWT without the approuter and XSUAA service, it is your responsibility to do the access control in the application.
```

2022-06-03 08:50 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +If you use JWTs not issued by the XSUAA you can configure validation by the destination service using the `x_user_token.jwks` or `x_user_token.jwks_uri` property.
[req] Isn't it "XSUAA service"?
```suggestion
If you use JWTs not issued by the XSUAA service you can configure validation by the destination service using the `x_user_token.jwks` or `x_user_token.jwks_uri` property.
```

2022-06-03 08:50 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +For more details on the JWTs have a look at the more detailed guide(../../guides/how-to-retrieve-jwt.mdx).
[req] Fix link + "the" is not necessary
```suggestion
For more details on JWTs have a look at the more detailed [guide](../../guides/how-to-retrieve-jwt.mdx).
```

2022-06-07 07:01 UTC, FrankEssenberger commented on docs/java/features/multi-tenancy/thread-context.mdx
> +- `x-app-specific-header: customer-value`
I guess Java does not run the prettier all the time.

2022-06-07 07:04 UTC, FrankEssenberger commented on docs/java/features/multi-tenancy/thread-context.mdx
> +- `x-app-specific-header: customer-value`
I guess the change was introduced by the prettier. I am not sure about your suggestion what is `custome` mean?

2022-06-15 13:59 UTC, tomfrenken approved these changes
LGTM but I guess Marika has to re-review @marikaner

2022-06-15 14:28 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +  className="center"
[q] Are you sure?

2022-06-15 14:28 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +  className="center"
[q] Also, seems incorrect to me...

2022-06-15 14:29 UTC, marikaner approved these changes
LGTM, but please make sure "className" is correct. Is this a react construct?

2022-06-16 08:57 UTC, merged