[ThreadContext] Update Async Execution Docs
SAP/cloud-sdk pull request #852
Opened 2022-06-13 13:05 UTC by MatKuhr

2022-06-13 13:10 UTC, MatKuhr commented on docs/java/features/multi-tenancy/thread-context.mdx
> +ThreadContextExecutor customExecutor = new ThreadContextExecutor()
TBD: Do we want to advertise this style? 

Alternatives would be:
```java
 Tenant myTenant = new DefaultTenant("foo");

Callable myTaskWithTenant = () -> TenantAccessor.executeWithTenant(myTask, myTenant);
ThreadContextExecutors.submit(myTaskWithTenant);
```
or:
```java
ThreadContext contextWithTenant = ThreadContextAccessor.getCurrentContext().duplicate().removeProperty("Tenant");
contextWithTenant.setPropertyIfAbsent("Tenant", Try.success(Property.of(myTenant)));

ThreadContextExecutors.submit(myTaskWithTenant, contextWithTenant);
```

2022-06-14 12:51 UTC, Johannes-Schneider reviewed
Generally, the documentation makes sense to me.
Some of the formulations could be improved though.

2022-06-14 12:51 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +As the name suggests the `ThreadContext` is bound to a thread, more specifically to the one it was created.
```suggestion
As the name suggests, the `ThreadContext` is bound to a thread, more specifically to the one it was created in.
```

2022-06-14 12:51 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +If asynchronous operations need to access the information, it has to be propagated to the new threads.
```suggestion
In consequence, other threads, i.e. asynchronous operations, cannot access the stored information if it hasn't been explicitly propagated.
```

2022-06-14 12:51 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +The operation can be submitted via:
```suggestion
The operation can be executed asynchronously via:
```

2022-06-14 12:51 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +This will use a default `ThreadContextExecutorService` based on a `CachedThreadPool` to create a new Thread and run the task.
```suggestion
By default, this will use a `ThreadContextExecutorService` based on a `CachedThreadPool` to create a new Thread and run the task.
```

2022-06-14 14:08 UTC, MatKuhr commented on docs/java/features/multi-tenancy/thread-context.mdx
> +ThreadContextExecutor customExecutor = new ThreadContextExecutor()
+1 on the third, I mentioned it mostly for completeness :D 

Additional downside of (1) is that the customer needs to interact with `ThreadContextExecutor` which is relatively easy to misuse (potentially less so if we apply [this improvement](https://github.wdf.sap.corp/MA/sdk/pull/7033#discussion_r4315070)).

We could also just describe both..

2022-06-14 14:10 UTC, MatKuhr commented on docs/java/features/multi-tenancy/thread-context.mdx
> +This will use a default `ThreadContextExecutorService` based on a `CachedThreadPool` to create a new Thread and run the task.
I would keep this as is,  to emphasise that this will always use "a default executor", namely the one set via `setDefault`

2022-06-14 14:15 UTC, MatKuhr commented on docs/java/features/multi-tenancy/thread-context.mdx
> +### Configuring the Executor
I also thought about that, but found that people might not read on and miss the Spring integration, which is probably more relevant to most readers.

2022-06-14 14:19 UTC, MatKuhr commented on docs/java/features/multi-tenancy/thread-context.mdx
> +The `ThreadContextExecutors` class leverages a default `ExecutorService` that can be configured.
Yes, I only mention `ExecutorService` here to keep it as simple as possible. This is the thing that people are probably most interested in changing (and we do that as well in the example). I figured the detail is not too important and we can just leave the more specific subtype out here.

2022-06-15 08:49 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +This will use a default `ThreadContextExecutorService` based on a `CachedThreadPool` to create a new Thread and run the task.
Okay, I see your point.

Nevertheless, I think the formulation _"a default executor"_ is not exactly describing what we want to convey here.
At least if I were reading this, I would ask myself _"What is a **default** executor? Is there a non-default one?"_.
Therefore, the actual method names `getDefault` and `setDefault` might not be optimal, as there is nothing else but this single "thingy", right?
At least I would assume if there is a `getDefault` that I somehow can also get a customized instance (similar to what the Apache HttpClient Builder is doing: You may use `HttpClients.default()` or `HttpClients.custom()`).

---

Overall, the most important part here (IMO) is that **all** submitted operations will be executed **in a single instance** of our interface.
And, yes, the instance that should be used to actually run the operations can be changed.
What do you think?

2022-06-15 09:03 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +ThreadContextExecutor customExecutor = new ThreadContextExecutor()
> We could also just describe both

Yeah, I think we should just mention both usages here.
Besides the technical "downsides" of the suggestion (2), I think it should be mentioned first since the semantic is just crystal clear and it is overall harder to get wrong.
Nevertheless, for more customizability (e.g. changing multiple values at once), suggestion (1) should be preferred.

2022-06-15 11:41 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +The `ThreadContextExecutors` class leverages a default `ExecutorService` that can be configured.
Okay, fine with me.

2022-06-15 12:56 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +This will use a default `ThreadContextExecutorService` based on a `CachedThreadPool` to create a new Thread and run the task.
Next attempt for a clearer description 😅

```suggestion
Operations that are submitted this way will be executed by a single instance of `ThreadContextExecutorService`.
By default, this instance is based on a `CachedThreadPool`, which manages the concurrency internally.
```

2022-06-15 12:59 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +The `ThreadContextExecutors` class leverages a default `ExecutorService` that can be configured.
```suggestion
The `ThreadContextExecutors` class leverages a single `ThreadContextExecutorService` instance that can be configured.
```

2022-06-15 13:01 UTC, Johannes-Schneider commented on docs/java/features/multi-tenancy/thread-context.mdx
> +            .withListeners(new TenantThreadContextListener(myTenant));
Should we maybe modify a second value to make the example a little more complete?

2022-06-16 07:20 UTC, CharlesDuboisSAP requested changes

2022-06-16 07:20 UTC, CharlesDuboisSAP commented on docs/java/features/multi-tenancy/thread-context.mdx
> +    return ThreadContextExecutors.getDefault();
```suggestion
    return ThreadContextExecutors.getExecutor();
```

2022-06-16 07:29 UTC, Johannes-Schneider reviewed
Aside from what @CharlesDuboisSAP suggested: LGTM!

2022-06-16 07:34 UTC, merged