[JS] Extend documentation sevice binding transformation
SAP/cloud-sdk pull request #889
Opened 2022-07-01 11:42 UTC by FrankEssenberger

## What Has Changed?

see title

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)

2022-07-05 08:59 UTC, florian-richter requested changes
Some minor fixes necessary

2022-07-05 08:59 UTC, florian-richter commented on docs/js/features/connectivity/destination.mdx
> +- Extract the URL form the service binding
```suggestion
- Extract the URL from the service binding
```
[req] typo

2022-07-05 08:59 UTC, florian-richter commented on docs/js/features/connectivity/destination.mdx
> +Contributions providing transform function are highly welcome.
```suggestion
Contributions providing transform functions are highly welcome.
```
[req] possibly a typo

2022-07-05 15:20 UTC, deekshas8 reviewed
Minor comments

2022-07-07 07:55 UTC, florian-richter approved these changes

2022-07-07 08:03 UTC, merged