Adjust documentation for destination look via issuerlinter prettier
SAP/cloud-sdk pull request #89
Opened 2021-01-08 16:39 UTC by FrankEssenberger

## What Has Changed?

Added a section for destintaion lookup using the issuer field.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-01-08 16:50 UTC, marikaner approved these changes
Only minor stuff, commit at your disgression.

2021-01-08 16:50 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +There are situations where you do not have a JWT issued by the XSUAA but need to lookup a destination e.g. background processes.
I think lookup is not a verb, but look up is.
```suggestion
There are situations where you do not have a JWT issued by the XSUAA but need to look a destination up e.g. in background processes.
```

2021-01-08 16:50 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +.execute({destinationName: 'myDestination'},{iss:yourIssuerValue})
```suggestion
.execute(
  { destinationName: 'myDestination' },
  { iss:yourIssuerValue }
 )
```

2021-01-08 16:50 UTC, marikaner commented on docs/js/features/connectivity/destination.mdx
> +In principle only the host of the url is relevant but since the same parsing and replace methods are used for the `iss` and `userJWT` case please provide the URL as stated before.
```suggestion
In principle only the host of the url is relevant but since the same parsing and replacement methods are used as for the JWT handling, the URL has to be provided in the format above.
```

2021-01-11 19:50 UTC, artemkovalyov approved these changes
Consider my minor fixes. Otherwise good to go.

2021-01-11 19:50 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +```
```suggestion
```js
.execute(
  { destinationName: 'myDestination' },
  { iss: yourIssuerValue }
 )
```
```

2021-01-11 19:50 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +:::
```suggestion
:::note
If a JWT is used in the destination lookup a validation of the provided token is performed.
This validation ensures that the JWT has not been manipulated.
If only the `iss` is provided no such validation is performed.
Note that the given subdomain value defines from which tenant destinations are fetched.
So a wrong value may break the isolation for tenants.
It is your responsibility as a developer to ensure that the provided value for the `iss` property is valid.
:::
```

2021-01-11 19:50 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +In principle only the host of the url is relevant but since the same parsing and replacement methods are used as for the JWT handling, the URL has to be provided in the format above.
```suggestion
The value for `iss` is supposed to be the same as in a JWT issued from the XSUAA e.g. `https://yourSubdomain.localhost:8080/uaa/oauth/token`.
In principle only the host of the URL is relevant but since the same parsing and replacement methods are used for the JWT handling, the URL has to be provided in the format above.
```

2021-01-12 22:01 UTC, artemkovalyov requested changes

2021-01-12 22:01 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SDK automatically parses the response of the destination service and uses the provided authentication information for the request to the target system.
```suggestion
The SAP Cloud SDK automatically parses the response of the destination service and uses the provided authentication information for the request to the target system.
```

2021-01-12 22:01 UTC, artemkovalyov commented on docs/js/features/connectivity/destination.mdx
> +The SDK automatically parses the response of the destination service and uses the provided authentication information for the request to the target system.
This should make Vale happy

2021-01-12 22:05 UTC, artemkovalyov approved these changes
LGTM

2021-01-12 22:05 UTC, merged