Split Documentation for Languages
SAP/cloud-sdk pull request #898
Opened 2022-07-07 11:21 UTC by Johannes-Schneider

## What Has Changed?

This PR splits the documentation for Java and JavaScript / TypeScript apart so that they can be versioned independently from each other.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-07-13 09:20 UTC, florian-richter reviewed
It compiles and seems to work but I have some questions...

2022-07-13 09:20 UTC, florian-richter commented on docs-common/overview/feature-matrix.mdx
> -import FeatureTable from '../components/FeatureTable';
> [WARNING] Docs markdown link couldn't be resolved: (../overview/feature-matrix.mdx) in /Users/d065362/dev/cloud-sdk-docs/docs-java/release-notes.mdx for version current

I get this warning when running `npm start`

2022-07-13 09:20 UTC, florian-richter commented on docs-java/features/odata/type-safe-client-odata-v4.mdx
> +// import NotImplemented from '../../../components/NotImplemented.js';
[q] Is this intended?

2022-07-13 09:20 UTC, florian-richter commented on docusaurus.config.js
> -          items: [
[q] Should these links be removed? Could we put them elsewhere?

2022-07-13 09:20 UTC, florian-richter commented on sidebarsDocsCommon.js
> +}
```suggestion
}

```
[nth]

2022-07-13 09:20 UTC, florian-richter commented on sidebarsDocsJava.js
> +}
```suggestion
}

```
[nth]

2022-07-13 09:20 UTC, florian-richter commented on sidebarsDocsJs.js
> +}
```suggestion
}

```
[nth]

2022-07-13 10:47 UTC, deekshas8 commented on docs-common/overview/feature-matrix.mdx
> -import FeatureTable from '../components/FeatureTable';
This should be fixed now

2022-07-13 10:55 UTC, deekshas8 commented on docs-java/features/odata/type-safe-client-odata-v4.mdx
> +// import NotImplemented from '../../../components/NotImplemented.js';
The decision was to remove them from the top navbar. The links are there on the [Get Support](https://sap.github.io/cloud-sdk/docs/overview/get-support) page.

2022-07-13 11:46 UTC, deekshas8 commented on docs-java/features/odata/type-safe-client-odata-v4.mdx
> +// import NotImplemented from '../../../components/NotImplemented.js';
Good catch.
@Johannes-Schneider could you please take a look here? Changing the path to `../../../src/components/NotImplemented.js` works.

2022-07-13 14:02 UTC, tomfrenken requested changes
Overall looks good, just some minor improvements and it can be merged.

2022-07-13 14:02 UTC, tomfrenken commented on docusaurus.config.js
> +        createRedirects(existingPath) {
[q] Could you potentially add a redirect here in case any other 404 would occur?
Or some other 404 page?

2022-07-13 14:02 UTC, tomfrenken commented on sidebarsDocsCommon.js
> +    someSidebar: [
[req] maybe rename this, `someSidebar` is maybe a little PoC'ish 👀

2022-07-13 14:02 UTC, tomfrenken commented on sidebarsDocsJava.js
> +    someSidebar: [
[req] same here

2022-07-13 14:02 UTC, tomfrenken commented on sidebarsDocsJs.js
> +    someSidebar: [
[req] same here

2022-07-14 06:27 UTC, Johannes-Schneider commented on docs-java/features/odata/type-safe-client-odata-v4.mdx
> +// import NotImplemented from '../../../components/NotImplemented.js';
I changed it to `@site/src/components/NotImplemented.js` and also un-commented the usage of this component (further down).

2022-07-14 08:17 UTC, marikaner reviewed
I requested some changes and left some questions. No blockers.

2022-07-14 08:17 UTC, marikaner commented on docusaurus.config.js
> +          sdkSwitch: true
[pp] I assume that this is the `showAlways` from the PoC. I initially called it `sdkSwitch` as well, but later decided to rename it, because I think `showAlways` explains its purpose better.

2022-07-14 08:17 UTC, marikaner commented on docusaurus.config.js
>            showLastUpdateTime: true,
[pp] This is totally unrelated, but it annoys me every time I see it. I would like to remove the `showLastUpdateAuthor` and `showLastUpdateTime` as I find it irrelevant (especially if the last author was dependabot).

2022-07-14 08:17 UTC, marikaner commented on docusaurus.config.js
> +        remarkPlugins: [require('mdx-mermaid')],
[q] Do we need this here, if it is already in the preset?

2022-07-14 09:07 UTC, deekshas8 commented on docusaurus.config.js
>            showLastUpdateTime: true,
Done

2022-07-14 09:10 UTC, deekshas8 commented on docusaurus.config.js
> +      }
Works without the undefined as well.

2022-07-14 09:17 UTC, deekshas8 commented on docusaurus.config.js
> +        remarkPlugins: [require('mdx-mermaid')],
Removed it from plugin sections

2022-07-14 10:07 UTC, tomfrenken approved these changes
LGTM

2022-07-14 10:13 UTC, merged