Add release notes for the 3.36.0 Java release
SAP/cloud-sdk pull request #91
Opened 2021-01-12 17:06 UTC by MatKuhr

## What Has Changed?

Explain what you have changed.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2021-01-12 17:19 UTC, MatKuhr commented
I don't know why the vale check fails, I have only changed the release notes where vale reports no violations:

```bash
vale docs/java/release-notes.mdx
> 0 errors, 0 warnings and 0 suggestions in 1 file.
```

2021-01-12 21:52 UTC, artemkovalyov requested changes
Rephrased some parts for readability.

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +  Please use the buildpack version `sap_java_buildpack_1_29` for this use case.
```suggestion
- Because of issues with the latest SAP Java Buildpack the TomEE based archetype for Cloud Foundry does not work with Java 11. Use `sap_java_buildpack_1_29` if you require TomEE with Java 11. We'll update here when it's fixed.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Remove dependencies from SDK Bill-of-Material (BOM)
```suggestion
- We removed the following dependencies from the SAP Cloud SDK Bill-of-Material (BOM)
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Introduce support for String-based filter functions `endswith`, `startswith` and `substringof` in the OData V2 VDM.
```suggestion
- Introduce support for String-based filter functions `endswith`, `startswith` and `substringof` in the OData V2 type-safe client also know as VDM.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Replace the deprecated constant `org.apache.commons.codec.Charsets.UTF_8` in the HelloWorldControllerTest class of the Spring archetype by its recommended successor `java.nio.charset.StandardCharse
```suggestion
- We replaced the deprecated constant `org.apache.commons.codec.Charsets.UTF_8` in the HelloWorldControllerTest class of the Spring archetype by its recommended successor `java.nio.charset.StandardCharsets.UTF_8`.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Add Maven module `s4hana-api-odata-v4` into `s4hana-all` to enable type-safe OData v4 client library for SAP S/4HANA Cloud Edition.
```suggestion
- We added Maven module `s4hana-api-odata-v4` into `s4hana-all` to enable type-safe OData v4 client library for SAP S/4HANA Cloud Edition.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue where OData V2 Update requests with PATCH contained incorrectly serialized date values.
```suggestion
- We fixed incorrect serialization of `date` values for OData v2 requests using a `PATCH` request method.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue where OData Batch requests sent an invalid `Accept` header.
```suggestion
- We fixed an issue where OData Batch requests were sending an invalid `Accept` header.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Fix an issue where OData Batch response API did not conveniently throw or wrap an exception for failing HTTP response code health checks.
```suggestion
- We fixed an issue where the API for OData Batch response did not conveniently throw or wrap an exception for failing HTTP response code health checks.
```

2021-01-12 21:52 UTC, artemkovalyov commented on docs/java/release-notes.mdx
> +- Remove a log message that incorrectly indicated an error when receiving OData responses without payload
```suggestion
- We removed a log message that incorrectly indicated an error when receiving an OData response without payload.
```

2021-01-12 21:54 UTC, artemkovalyov commented
@MatKuhr , seems like the latest update to 2.7 changed the checking algorithm a bit. I fixed it.

2021-01-13 11:26 UTC, MatKuhr commented
In the past we avoided past tense and formulations like `we updated` or `You now can`. I now just adapted according to your suggestions, but I think we need to discuss this in the team and align on a convention.

2021-01-13 15:27 UTC, artemkovalyov approved these changes
LGTM

2021-01-13 16:36 UTC, merged

2021-01-13 20:12 UTC, artemkovalyov commented
> In the past we avoided past tense and formulations like `we updated` or `You now can`. I now just adapted according to your suggestions, but I think we need to discuss this in the team and align on a convention.

Sure, I'm indifferent to the modal as long as it makes sense and reads naturally. The subjectless form doesn't work for the public release notes.