Add documentation
SAP/cloud-sdk pull request #911
Opened 2022-07-13 11:43 UTC by tomfrenken

## What Has Changed?

This PR restructures some of our docs so that a few sections are now properly displayed in the sidebar.
Additionally, documentation regarding `setRequiredFields` and `setIgnoredFields` is now added.

2022-07-14 07:11 UTC, florian-richter approved these changes

2022-07-14 07:56 UTC, marikaner requested changes

2022-07-14 07:56 UTC, marikaner commented on docs/js/features/odata/common/operations/set-required-fields.mdx
> +If updating an entity requires a specific field, even though it didn't change, you can use the `setRequiredFields` method.
[req] I think we should also mention what it is good for. So what will happen if I use this function (=> will be in the body of the request).

2022-07-14 07:56 UTC, marikaner commented on docs/js/features/odata/common/operations/update.mdx
> -
[req] I think there is no link to the etag section here, correct?

2022-07-14 07:56 UTC, marikaner commented on docs/js/features/odata/common/operations/ignore-or-overwrite-version.mdx
> +Entities can only be updated or deleted if [ETags](#handling-of-etags) match.
[nth] This sentence is basically duplicate in the delete request builder - can we improve this?

2022-07-14 08:08 UTC, deekshas8 requested changes
Looks good, two minor improvements.

2022-07-14 08:08 UTC, deekshas8 commented on docs/js/features/odata/common/operations/ignore-or-overwrite-version.mdx
> +In the example above the ETag 'etag' is being used instead of the original one.
```suggestion
In the example above, the ETag 'etag' is used instead of the original one.
```

2022-07-14 08:08 UTC, deekshas8 commented on docs/js/features/odata/common/operations/ignore-or-overwrite-version.mdx
> +In the example above the ETag 'etag' is being used instead of the original one.
```suggestion
In the example above, the ETag 'etag' is used instead of the original one.
```

2022-07-14 08:08 UTC, deekshas8 commented on docs/js/features/odata/common/operations/replace.mdx
> +To replace or update the whole entity use `replaceWholeEntityWithPut`:
```suggestion
To replace or update the whole entity, use `replaceWholeEntityWithPut`:
```

2022-07-21 15:39 UTC, marikaner requested changes
I have some more requests. This time I added more explicit suggestions.

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +Check out our [ETag](#handling-of-etags) section for more information.
[nth] In the text above we say that PUT + PATCH can be used and that "only changed" fields will be updated. I think it would be nice to improve the description as follows:

- State that the update request builder allows to change existing entities. Do not mention PUT and PATCH for this. We already state that PATCH is used by default for the changed fields.
- To understand what changed fields are we should explain it somehow. Maybe we can add this to the example and first do a GET and change one property and then do the update. With this it will become much more clear that the data that is sent should only contain the changed property. (also state it in the text). This is a nice basis for the PUT section and also the setIgnored/Required fields.

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/odata-v2-client.mdx
> +### Replace the Entity
[pp] Consider adding "with `PUT`" to make it easier to search

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/odata-v4-client.mdx
> +### Update Whole Entity
[req] Please make sure that the titles for v2 and v4 are aligned.

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/common/operations/set-ignored-fields.mdx
> +If you want to ignore specific fields which changed since the last update of an entity, you can use the `setIgnoredFields` method.
[req] Technically it is not correct that the properties have not changed since the last update. Rather since the last get request in your app. Maybe just avoid it. I am still missing the purpose of "ignoring". Consider my suggestion:

```suggestion
If you changed properties on an entity, that you do not want to send in the payload of the update request, use the `setIgnoredFields` method to ignore them.
```

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/common/operations/set-ignored-fields.mdx
> +In the following example, the `PATCH` request won't contain changes that were made to the `FIRST_NAME` property of the business partner.
[nth] Maybe it would be nice to add the step of changing the first_name property and another property to the example and stating what the payload of the request would look like.

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +If updating an entity requires a specific field, even though it didn't change, you can use the `setRequiredFields` method.
```suggestion
If you want to send properties in the payload of the update request, that you did not change, use the `setRequiredFields` method to add them.
```

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +In the following example, the `PATCH` request will contain the `FIRST_NAME` property of the business partner, even if it didn't change.
[nth] Same suggestion as for ignore.

2022-07-21 15:39 UTC, marikaner commented on docs-js/features/odata/common/operations/replace.mdx
> +To replace or update the whole entity, use `replaceWholeEntityWithPut`:
[nth] Can a partial entity be updated? I would keep it as replace (I think I originally wrote this...).
```suggestion
To replace an entity instead of just updating specific fields, use `replaceWholeEntityWithPut`:
```

2022-07-27 11:27 UTC, marikaner approved these changes
I still made some suggestions, but I already approved :)

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-ignored-fields.mdx
> +// Finally we update the business partner with the updated last name, ignoring the changes to their first name.
What do you think?

```suggestion
// Send a PATCH request with `{ "LastName" : "Smith" }`  and do not include the changed first name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-ignored-fields.mdx
> +// First we get a businesspartner with the id of "1".
```suggestion
// Get a business partner
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-ignored-fields.mdx
> +// Then we change the business partner's first name to "Steve" and their last name to "Smith".
```suggestion
// Change first name and last name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-ignored-fields.mdx
> +// Finally we update the business partner with the updated last name, ignoring the changes to their first name.
What do you think?

```suggestion
// Send a PATCH request with `{ "LastName" : "Smith" }`  and do not include the changed first name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +// First we get a businesspartner with the id of "1".
```suggestion
// Get a business partner
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +// First we get a businesspartner with the id of "1".
```suggestion
// Get a business partner
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +// Then we change the business partner's last name to "Smith".
```suggestion
// Change last name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +// Then we change the business partner's last name to "Smith".
```suggestion
// Change last name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +// Finally we update the business partner with the updated last name, but still include their first name in the "PATCH" request.
What do you think?

```suggestion
// Send a PATCH request with `{ "LastName" : "Smith", "FirstName": "Steve" }`  and include the first name although it was not changed
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/set-required-fields.mdx
> +// Finally we update the business partner with the updated last name, but still include their first name in the "PATCH" request.
What do you think?

```suggestion
// Send a PATCH request with `{ "LastName" : "Smith", "FirstName": "Steve" }`  and include the first name although it was not changed
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +The Update request builder allows you to change existing entities.
```suggestion
The update request builder allows you to change existing entities.
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +// First we get a businesspartner with the id of "1".
```suggestion
// Get a business partner
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +// Then we change the business partner's first name to "Steve".
```suggestion
// Change first name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +// Finally we update the business partner with the updated first name.
```suggestion
// Send a PATCH request with `{ "FirstName" : "Steve" }`
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +// First we get a businesspartner with the id of "1".
```suggestion
// Get a business partner
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +// Then we change the business partner's first name to "Steve".
```suggestion
// Change first name
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +// Finally we update the business partner with the updated first name.
```suggestion
// Send a PATCH request with `{ "FirstName" : "Steve" }`
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +so in this case the first name, is sent to the `BusinessPartner` service using `PATCH`.
This sentence reads weird, but I am not so happy with my suggestion either. Maybe it is now duplicate with the example?

```suggestion
In the example above we changed the first name of the given business partner.
The payload sent to the service with PATCH includes only the first name.
```

2022-07-27 11:27 UTC, marikaner commented on docs-js/features/odata/common/operations/update.mdx
> +Be aware that update requests will fail if their ETag doesn't match.
```suggestion
Be aware that update requests will fail if their ETags don't match.
```

2022-07-27 11:53 UTC, merged