Add doc to destination for service binding
SAP/cloud-sdk pull request #943
Opened 2022-08-02 10:25 UTC by ZhongpinWang

## What Has Changed?

Add documentation for `destinationForServiceBinding` and `serviceBindingTransformFn`.

Closes SAP/cloud-sdk-backlog#678.

## Manual Checks?

- [ ] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [ ] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [ ] You formatted all changed files with prettier (`npm run prettier`)
- [ ] You tested if the documentation still builds (`npm run build`)
- [ ] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [ ] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-08-08 14:06 UTC, florian-richter requested changes

2022-08-08 14:06 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +A simple example:
```suggestion
Example code:
```
[nth] Avoid 'simple' and other [weasel words](https://en.wikipedia.org/wiki/Weasel_word) if possible

2022-08-08 14:06 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +.execute({ destinationName: 'service-name', serviceBindingTransformFn })
```suggestion
serviceInstance.execute({ destinationName: 'service-name', serviceBindingTransformFn })
```
[pp] I prefer if an example has valid TS syntax

2022-08-08 14:06 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
>  :::
This can be removed now that we have the version split.

2022-08-08 14:06 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +To search the destination explicitly from service bindings, call <LinkToLatestJsApiDocs slug="functions/sap_cloud_sdk_connectivity.destinationForServiceBinding" name="destinationForServiceBinding" />
```suggestion
To search the destination explicitly for service bindings, call <LinkToLatestJsApiDocs slug="functions/sap_cloud_sdk_connectivity.destinationForServiceBinding" name="destinationForServiceBinding" /> function with the service name and options.
```
[q] Not sure if my suggestion is correct but it seems incorrect to say "from service bindings" in this context.

2022-08-08 14:06 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +For example:
```suggestion
```
[pp] Not all examples need a prefix like this in my opinion.

2022-08-10 07:56 UTC, ZhongpinWang commented on docs-js/features/connectivity/destination.mdx
> +Currently, 5 services are supported out of the box:
I changed it to the way in SAP/cloud-sdk#946.

2022-08-10 08:11 UTC, ZhongpinWang commented on docs-js/features/connectivity/destination.mdx
>  :::
Done.

2022-08-10 08:15 UTC, ZhongpinWang commented on docs-js/features/connectivity/destination.mdx
> +To search the destination explicitly from service bindings, call <LinkToLatestJsApiDocs slug="functions/sap_cloud_sdk_connectivity.destinationForServiceBinding" name="destinationForServiceBinding" />
😄 Good point. I feel like it is also a bit questionable to use 'for' in `destinationForServiceBinding`. Isn't the goal to find a destination from a bunch of service bindings? @florian-richter

2022-08-11 07:23 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +To search the destination explicitly from service bindings, call <LinkToLatestJsApiDocs slug="functions/sap_cloud_sdk_connectivity.destinationForServiceBinding" name="destinationForServiceBinding" />
Not sure. Maybe @frank-essenberger or @jjtang1985 could clarify? But given the function name, I guess the text should reflect it.

2022-08-11 07:24 UTC, florian-richter approved these changes
Looks good. That one question remains, but I guess it doesn't really matter too much.

2022-08-11 07:30 UTC, FrankEssenberger commented on docs-js/features/connectivity/destination.mdx
> +To search the destination explicitly from service bindings, call <LinkToLatestJsApiDocs slug="functions/sap_cloud_sdk_connectivity.destinationForServiceBinding" name="destinationForServiceBinding" />
Hm, I am not a big fan of this sentence overall, since we have the getDestionation() which will do a few things in a row, where `destinationForServiceBinding` is one of them. So I would perhaps use something like:

`If you only want to consider the service bindings for creating destination you can call 'destinationForServiceBinding'. This will search the bound services for a name matching the provided destination name and try to create a destination object for that service.`

2022-08-11 08:03 UTC, FrankEssenberger commented on docs-js/features/connectivity/destination.mdx
> +To search the destination explicitly from service bindings, call <LinkToLatestJsApiDocs slug="functions/sap_cloud_sdk_connectivity.destinationForServiceBinding" name="destinationForServiceBinding" />
I will adjust this in a follow up PR I have open anyway.

2022-08-11 08:03 UTC, FrankEssenberger approved these changes

2022-08-11 08:03 UTC, merged