add xsuaa as supported service via service binding
SAP/cloud-sdk pull request #946
Opened 2022-08-04 14:13 UTC by FrankEssenberger

Add the xsuaa as supprted service via service binding.

2022-08-08 14:08 UTC, florian-richter requested changes

2022-08-08 14:08 UTC, florian-richter commented on docs-js/features/connectivity/destination.mdx
> +- `xsuaa`
Above it says "5 services types" which should be "7 service types" now...

2022-08-09 10:13 UTC, FrankEssenberger commented on docs-js/features/connectivity/destination.mdx
> +- `xsuaa`
I extended the docs a bit, now it has some overlap with https://github.com/SAP/cloud-sdk/pull/943 but the one who gets merged last has to align I guess.

2022-08-11 07:26 UTC, florian-richter approved these changes
LGTM

2022-08-11 08:27 UTC, merged