[Java] Kyma On-Prem Connectivity Workaround
SAP/cloud-sdk pull request #954
Opened 2022-08-11 07:19 UTC by Johannes-Schneider

## What Has Changed?

This PR adds a workaround for the currently broken On-Premise connectivity from within the Kyma environment.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

2022-08-11 07:40 UTC, Johannes-Schneider commented on docs-java/environments/sap-btp-kyma-environment.mdx
> +Some of the most recent changes of the Kyma runtime environment render the SAP Cloud SDK's On-Premise connectivity unfunctional.
```suggestion
Recent changes of the Kyma runtime environment prevent the SAP Cloud SDK's On-Premise connectivity from working as intended.
```

2022-08-11 07:52 UTC, MatKuhr approved these changes
Lgtm; assuming the formatting works out

2022-08-11 07:52 UTC, MatKuhr commented on docs-java/environments/sap-btp-kyma-environment.mdx
> +            return Collections.emptyList();
Why don’t we cover principal propagation? Is it specific to the untrusted mode?

2022-08-11 07:52 UTC, MatKuhr commented on docs-java/environments/sap-btp-kyma-environment.mdx
> +            return Collections.emptyList();
At this point a warning might make sense, not sure if there is a scenario where the onprem call afterwards could still succeed

2022-08-11 07:56 UTC, newtork commented on docs-java/environments/sap-btp-kyma-environment.mdx
> +            .getOrElse(AuthenticationType.NO_AUTHENTICATION) != AuthenticationType.PRINCIPAL_PROPAGATION ) {
Maybe slightly less code...?
```suggestion
        if( !authentication.contains(AuthenticationType.PRINCIPAL_PROPAGATION) ) {
```

2022-08-11 08:23 UTC, newtork requested changes
Please check whether this could be a "workaround" instead
```
static{
  PrincipalPropagationStrategy.setDefaultStrategy(PrincipalPropagationStrategy.COMPATIBILITY);
}
```

IF not, please dismiss my review.

2022-08-11 11:39 UTC, Johannes-Schneider commented
Converted to a draft since we are evaluating whether the suggestion from @newtork is also working.

2022-08-15 06:41 UTC, Johannes-Schneider commented
The customer didn't reply yet, so we are assuming that the suggested workaround is good enough for the moment (as it has been tested).

2022-08-15 06:45 UTC, merged